### ISSUE TITLE
45.2 : Scheduled repair no longer proceeds after advancing the day

### ISSUE THREAD

**Issue by Question2** [MegaMek/mekhq#1029]
Scheduled repairs used to automatically proceed after advancing the day, now they do not.

![image](https://user-images.githubusercontent.com/1191378/50721460-22a88b80-1114-11e9-9060-9459deac8963.png)

For example, the grasshopper's right torso was assigned to Elsbeth, and the repair task is listed as scheduled, but advancing the day will not cause Elsbeth to work on it. You have to manually tell Elsbeth to work on it every single day till its done, and no other tech teams can touch the repair task till its finished.

Techs used to work on scheduled tasks automatically, but this seems to have been broken at some point.

[a.zip](https://github.com/MegaMek/mekhq/files/2729273/a.zip)

**Comment by sixlettervariables** [comment]
I'm not seeing that issue on the latest dev (0.45.3). Here are the steps I took, to double check I'm doing this the same as you are:
1. Right click on the RT and set the Mode to x4
2. Click on Elisabeth and click Do Task
3. Click Advance Day

The work shows it is being done, and one of three things happens:
1. There is not enough time left.
2. The work succeeds.
3. The work fails.

**Comment by molemanBT** [comment]
This happens regularly in my save on 45.2, I can upload that too later if you wish?

**Comment by sixlettervariables** [comment]
Yes that'd be great.

**Comment by Question2** [comment]
I dont have 45.3 to test this and I dont think its available for download yet, but what I did was mass-repair, which left the RT, then advanced the day. The time on the RT did not decrease as I kept advancing the day, and I had to manually click the "do task" button every day till it got fixed.

This seems to happen with all the high time items like repairing damaged torsos or replacing missing limbs.

**Comment by bczretribution** [comment]
this was issue 3 in my multi-issue post from a few days ago.  I only had it the once that I noticed (i don't seem to have it happen as much as you Q2) and haven't repeated it, but I can corroborate that it is happening.  I have been trying to get a save with the issue but havnt had any luck yet.  I will post it here if i get one

**Comment by bczretribution** [comment]
just had a case of this happen 
![continue repair](https://user-images.githubusercontent.com/34722287/50941542-54428f00-1453-11e9-8058-094224c2ad18.jpg)

attached are 2 campaign saves one day apart to show the pre and post situation, hope this helps
[glitch (2).zip](https://github.com/MegaMek/mekhq/files/2743291/glitch.2.zip)

**Comment by Question2** [comment]
I have noticed that if i close mekhq and load the save again, the scheduled repair does advance normally.

**Comment by molemanBT** [comment]
I have a feeling this may be an issue that occurs as your campaign/save file gets bigger? I've never had it in the early stages, but it happens every single time I get some years into a campaign (current: 3 years, although it was happening at 2 years as well) with more mechs (24) and more techs (8).

This may just be that there's obviously more repairs to do on larger fleets, so it's more obvious, but I don't think so.

I honestly think the best thing to do might be to run a battle yourself and then do the repairs afterwards? I know you guys are busy so may not have time, but if it's something that corrects after a reload (this is not something I've noticed), that may not be capturable otherwise?

I have attached my campaign file (i have no custom mechs) and MUL. Do you need me to provide you with anything else?
[error.zip](https://github.com/MegaMek/mekhq/files/2812173/error.zip)

**Comment by Question2** [comment]
I had just started a fresh campaign and was only using about a lance's worth of stuff, so I dont think the issue is related to a large campaign file size.

**Comment by pjfarland** [comment]
This sounds like the issue I was having and reported a while back.

I believe the issue was caused by assigning new units to a tech doing a multi-day repair. The tech runs out of time because of the maintenance and never finishes the job.

**Comment by sixlettervariables** [comment]
We've had a number of fixes in this general area that would have resolved many of the possible causes. If this still persists on a more recent release of MHQ please reopen this issue. Thanks!
