### ISSUE TITLE
MekHQ plugins feature + missing mekhq.jar (windows)

### ISSUE THREAD

**Issue by cosxy** [MegaMek/mekhq#1186]
### Environment
MekHQ version: 45.3 and 45.4
Operating system:  Windows
(java -version)
Java version: 1.8.0_201
Java SE runtime environment build 1.8.0_201-b09
Java hotspot client VM  build 25.201-b09
Jython version: jython-standalone-2.7.0.jar

### Description
The windows version release is missing the MekHQ.jar file in the 'mekhq-0.45.3(root)/lib' folder. As a work around I copied the Linux release file into the folder. Needs to be included if wanting to reference the hq classes for new plugins.

not sure if this is a bug or if I didn't get far enough in my testing. I placed jython.jar in the plugins folder and the example python script(personnel_test.py) from 'mekhq-0.45.3(root)/docs/plugins.txt' (line number 194). 
Got the following error:
WARN [mekhq.module.ScriptPluginManager] {SwingWorker-pool-1-thread-1}
could not find script engine for extension txt

Initial thought is that the plugin feature isn't fully working for python scripts?

The download links for the most recent linux build is pointing to windows build on the megamek site(https://www.megamek.org/downloads). The mekhq-0.45.4.tar.gz 
PS note: has batch files instead of shell scripts.

### Files
Missing 'mekhq-windows-0.45.4(root)/lib/mekhq.jar'

Linux/Unix: https://github.com/MegaMek/mekhq/releases/download/v0.45.4/mekhq-windows-0.45.4.zip

mekhq.module.ScriptPluginManager not finding or handling python scripts and passing to jython.jar.

**Comment by neoancient** [comment]
We don't have a Linux build. We have a Windows-only package, which has the jar files wrapped in EXEs, and a generic build which includes start scripts for Unix-type systems, which includes Linux but also OSX, CygWin, and others, and also includes Windows batch files. The MekHQ jar can be obtained in several ways, one of which is to get it from the generic package. When using Maven or Gradle, the dependency can be configured using the url `https://github.com/MegaMek/mavenrepo/raw/master` for the repository. The group is org.megamek and the module is mekhq. You can also download it directly from the MegaMek/mavenrepo repository on GitHub. In order to work with the MekHQ module one would normally have the source available, and the jar can be built from the source by running `gradle.bat jar` (Windows) or `gradlew jar` (Unixy systems) from the root directory.

The message in the log about the txt file occurs because it checks every file in the plugins directory, recursively, and tries to find a script interpreter based on the file extension. That message is generated by readme.txt. Ideally it would skip txt files, as it does jar files, but this feature is in the very early stages. A more robust and versatile plugin system should be coming soon, whenever I get time to put the finishing touches on it.
