### ISSUE TITLE
feature request: +-100m loan button

### ISSUE THREAD

**Issue by bczretribution** [MegaMek/mekhq#1354]
in the take a loan interface, it would be nice to have buttons for + or - 100mil for those larger loans.

**Comment by sixlettervariables** [comment]
I worked on this and the current UX doesn't end up supporting a button with `+100mil` on the face. I played around with various ways to make that work, but ultimately didn't find a good way, without Java putting ellipses on the button.

One consideration is going to `+100M` rather than `mil`. Thoughts?

**Comment by VicenteCartas** [comment]
+100M -100M sounds good.

**Comment by bczretribution** [comment]
Can't speak to project goals, but as the user that would work fine for me, Function holds precedence over verbiage in my opinion

**Comment by sixlettervariables** [comment]
This will land in 0.47.3.
