### ISSUE TITLE
2x C3 Master Mechs not working properly

### ISSUE THREAD

**Issue by CrowSplat** [MegaMek/mekhq#136]
As posted on the forums. Mechs with 2 C3 Master units are unable to be set as company level master. Only 1 master unit is functional as only 3 network slots are available. These mechs also cannot use there C3 units to slave to another master, although other masters can slave to them.

[C3 Test30670101.zip](https://github.com/MegaMek/mekhq/files/419297/C3.Test30670101.zip)

**Comment by Dylan-M** [comment]
As posted in the thread, this is working just fine. You have to configure it.

http://imgur.com/WwEo7ql

http://imgur.com/dok2WG5

**Comment by CrowSplat** [comment]
Those images are from MegaMek yes? I am referring to setting up the C3 in the TO&E in MekHQ.

**Comment by HammerGS** [comment]
I think the issue is in MekHQ.  When I load the test Campaign and try to set up Configuration 2 (TW pg 132).  The sunder has Dual Masters so I should be able to link the Atlas and and Cyclops to it.

The Sunder would then have 3 slots for slave units.  The Atlas and Cyclops would have room for 3 slave's each.

In the revised attached save you can see the last two Catapults can't connect but according to the diagram should be able to.

MM will let you configure them correctly in the lounge.

MUL FILE SHOWING WORKING IN MM
[C3 Hammer.zip](https://github.com/MegaMek/mekhq/files/419317/C3.Hammer.zip)

REVISED SAVE GAME SHOW ISSUE>
[C3 Test Connected.zip](https://github.com/MegaMek/mekhq/files/419313/C3.Test.Connected.zip)

**Comment by CrowSplat** [comment]
Which would have to be done EVERY time I get a scenario for the unit in question... Whereas other configurations need to be configured in MekHQ once and done

**Comment by HammerGS** [comment]
@CrowSplat I agree, I've just provided additional information for us to be able to trouble shoot and fix the issue.

But one of the coders needs to review it again and reopen the ticket.  I only play with data.

**Comment by CrowSplat** [comment]
Yeah, Sorry if I came off as rude. It was frustrating to see the issue closed and marked invalid when the solution presented was irrelevant to the issue.

It's not a huge issue as I'm sure not many people go for full company C3, and there are workarounds. Mostly just bringing it up to let it's existence be known.

**Comment by pheonixstorm** [comment]
First thing I see is that the dual master mech (in my test a Battlemaster) does not have the network menu.
The single master mechs do have this menu for assignment as company level master and to connect to the dual master.

Connecting the two single masters to the dual master unit only leaves one slot free so the dual master can only connect one additional slave rather than the 3 extra slots it should have open plus the slot for the company master.

I know this worked awhile back so will try to look into how far back this bug goes later today.

**Comment by Dylan-M** [comment]
I had hoped to have time to look at this today, but instead I'm going to the car dealership to see about buying a new car.

**Comment by pheonixstorm** [comment]
I had to go back to around 0.3.5 to get this to partially work. In 0.3.5 you can correctly setup a company network but the option to turn the dual master into the company level master is still missing as is the network menu. I was able to configure a full company network though unlike 0.3.10 which still has the issue posted above.

**Comment by arlith** [comment]
The problem, at least when I briefly looked (I didn't have enough time to really figure out what was going on), was with `Entity.c3CompanyMasterIndex`.  This is used to determine if a unit is a company master, but is only ever set in `Entity.hasC3MM`, which looks like it would cause issues in MHQ.

**Comment by Dylan-M** [comment]
@pheonixstorm: Please learn [git bisect](https://git-scm.com/docs/git-bisect) for this type of debugging. It is the only definitive way to determine which commit introduced the bug without testing commits manually.

**Comment by pheonixstorm** [comment]
I didn't use git bisect since it was easier to first find the release where the problem did not occur (menu issue) while the issue with the company master not being usable goes farther back. I could have used it and thought about it but bit not feel like recompiling when downloading back to 0.3.5 was faster to at least find a starting point for bisect w/o going back to the first commit.

**Comment by neoancient** [comment]
MHQ uses c3MasterIsUUID in some places and c3Master in others. Fixing it to use the UUIDs in all places is not enough to fix it because it relies on methods in Entity that use c3Master.

**Comment by neoancient** [comment]
In the meantime, you can configure it if you assign all C3 slaves to their master units first, then assign the independent masters to the company command 'Mech. Here is the file that @HammerGS shared, configured in HQ.
[C3 Test.zip](https://github.com/MegaMek/mekhq/files/523538/C3.Test.zip)

**Comment by neoancient** [comment]
A little sleep and fresh eyes and it turned out to be much simpler.
