### ISSUE TITLE
Hangar Tab: Unmaintained Unit View

### ISSUE THREAD

**Issue by ajac09** [MegaMek/mekhq#1595]
![image](https://user-images.githubusercontent.com/62312925/77763989-e65b9680-7009-11ea-9da2-8caad31e7c61.png)

I want up here a "unmaintained unit view"
and a mass way to add more then one person to units here or an auto add feature  that will put unassigned techs to a unit. 

also a gm mode for instant fixing the entire force with a single button push.
Also space maps and campaigns be kind of fun to do multiple maps for a mission from space to planet.

sorry alot here being unable to do much at home wtih the virus and IT work from home is BORING I been playing with mekhq alot lol

**Comment by Windchild292** [comment]
No worries about the RFEs, however please open each one in different issues.

Hangar Tab: Unmaintained Unit View (although this could be done by just sorting by status then by tech crew, as that would sort out any mothballed units) would be a good name for the first one, and I don't think there is anything specific about that otherwise

The second bit (mass adding personnel to units), do you mean mass assign techs to units? Cause that is coming in the next release, along with bulk hire personnel (I've done a major rejig of the right click menu).
This one is coming next release, bulk restore on right click GM menu.
Space stuff is... a work in progress. You can currently make custom scenarios and they can be space based.

**Comment by ajac09** [comment]
Maybe just make it a click box maybe that auto sorts or something I just feeling lazy lol
