### ISSUE TITLE
Request for Against the Bot: Take control of the integrated/house units?

### ISSUE THREAD

**Issue by binaryspica** [MegaMek/mekhq#1808]
### Environment
Ver 0.47.6

### Description
The liaison command is fine, but they are making headache in the most times. Although they will accompany to us, but they never lead my command(because the bot controls the unit), and most of them are only use fragile and faster light battlemech, makes most of them rush to the enemy formation and make the officer tip of the spear. Even if I want to make a defensive position, such a rushing VIP makes the move impossible. Their fragility is also the reason to losing them on the battle.

So, can't we take control of the unit? I know reducing the aggression may helps, but it is not the solution for the most times.

**Comment by NickAragua** [comment]
You do have control of the liaison. You do not, by design, have control over the house/integrated units under those command clauses. Reducing aggression and increasing self-preservation will help. Another approach is that you can edit the bot's settings to give them a retreat edge that's the same as your deployment edge, and then they'll simply retreat. You're still on the hook for any scenario objectives involving them, though, so that's a bit of a tradeoff.

**Comment by binaryspica** [comment]
Can I control the liaison? They are always take the one bot faction that is same team with me, make them to out of control.
