### ISSUE TITLE
Cannot change portrait on personnel with existing non-default portrait

### ISSUE THREAD

**Issue by AaronGullickson** [MegaMek/mekhq#1816]
### Environment
MekHQ 0.47.6, Java 8, Mac OSX

### Description
If you try to change the portrait of a person who already has a portrait, no change is made, and no errors are written to the log. This does not happen if the person has the default portrait. You can work around this problem at the moment by first assigning the person the default portrait (which works) and then assigning the portrait you want.

I have tested this on three campaigns, including one of the default campaigns, with the same results. To replicate, just open any of the default campaigns and try to change a portrait.

**Comment by Kendricke** [comment]
Same issue here with an additional obsrvation.  Portraits randomized on new characters are randomizing to wrong role (Combat/Infantry instead of Mechwarrior) and then I can't even select the correct role folder for a new portrait unless I FIRST change portrait to default before reselecting a new portrait.  

Additionally, if I change portrait to default first then randomize, it AGAIN does not select correct role.

**Comment by Windchild292** [comment]
So, the issue is that you can't change portraits within the same portrait grouping, unless it is the general group.

**Comment by HammerGS** [comment]
Yeah, I think thats the basic issue.

**Comment by Windchild292** [comment]
It is a boolean logic issue, the if statement looks for either not equalling the value, not both. PR will be open in a few minutes.
