### ISSUE TITLE
Clan Technology SPA for Techs

### ISSUE THREAD

**Issue by scJazz2** [MegaMek/mekhq#187]
Please re-add or re-code SPAs for Clan Tech Familiarization.

SPA: Clan Tech Novice... +1 for Clan Tech repairs
SPA: Clan Tech Professional... +2 for Clan Tech repairs

Only available to IS Technicians.

**Comment by Dylan-M** [comment]
So, I think this would be better implemented as a 3 level skill, that decreases the modifier by the skill values (0, 1, 2).

**Comment by scJazz2** [comment]
The Slack chat went back and forth about skill or SPA. My one concern is that a Clan Tech could buy the skill in the current framework (AFAIK). An SPA could just exclude the "Clanner" checkbox and not allow it for purchase.

**Comment by Akjosch** [comment]
For the record, here's my take on this (which includes concepts from BT as well as GURPS):

* People have a Tech Rating they are comfortable with, going from A to F. For SL era, clans and IS in the later 31th century, this rating is "E". For other people, the rating is "D".
* When working on technology that's exceeding their personal tech rating, they get modifiers to the TN: +2 for one TR the item is above, +5 for two, +9 for three (someone from a backwater C-rated planet trying to repair cutting edge F-rated equipment), impossible for anything more.
* XP can be spent to upgrade one's rating, at a default rate of something like 100 XP/level.

Options:

* For new hires, this can depend on the technical sophistication of the planet the unit is on.
* There can be sub-ratings ("Early E", "Late E" and so on), since it's a MekHQ-only feature and we aren't slavishly tied to the official ratings or rules anyway (if we add two sub-ratings between each, the modifiers would then go +1, +1, +2, +3, +4, +5, +6, +7, +9, impossible for each sub-rating step; for one extra sub-rating, it's +1, +2, +3, +5, +7, +9, impossible).
* If implementing as a skill, name it something like "technical familiarity" and start at something more than 0 for new hires. I'd then go with a skill level of 6 for most of the IS, 8 for most of the clan sphere, with the TRs corresponding to every second skill level (A=0, B=2, C=4, D=6, E=8, F=10) and modifiers as above.

**Comment by purpledragon2** [comment]
@Akjosch: I'm not feeling this.  I believe it would make it unnecessarily complicated.  You would have to keep track of two skills per tech (tech/whichever and then your proposed skill).  That doubles the amount of skills those techs would have to have.  Then, you'd have to have something that keeps track of where the tech comes from, not necessarily where they hired on at, though that would be easier.  Then you'd have to have the tech level, not the technology level, but the technician available level for each planet.  

I believe it would be better served as an SPA the way scJazz2 stated.

**Comment by Akjosch** [comment]
1. We are already keeping track of some 30 skills per person, tech or not. The computer wouldn't care if it was 3000.
2. Where someone comes from is per default where you hire them, optionally a neighbouring planet (which you can query easily already). We need to keep track of this information for a lot more in the near future anyway, like the name generator to use or starting skill randomisation.
3. That's what the the technical sophistication (first) part of the USILR code is for.

**Comment by pheonixstorm** [comment]
The most serious issue with what you outlined Akjosch is the 100xp/level. That is impossible for default play, and using ralgiths idea would really be ideal.  We only need something to handle IS techs working on Clan tech.

**Comment by Akjosch** [comment]
The 100 xp is just an example. If implemented as a skill, everyone would be able to set those values for themselves most easily anyway.

My suggestion aims at making Clan tech into something that's *not* this magical, mysterious "thing" that only the initiated acolytes have any chance at understanding (we already have ComStar and the HPG network for that). It's just a set of skills and basic practices which everyone who grows up around sufficiently advanced technology picks up on during their formative years and will have to learn the hard way as an adult if growing up on a backwater planet.

**Comment by mkerensky** [comment]
I would love to see MHQ do something like this with the USILR codes for each planet, and I do think the base tech level makes sense now that the IS can produce clan-spec equipment in the Republic era.  For SPAs at least, it seems to me that each MHQ XP is worth about 25 AToW XP.

**Comment by pheonixstorm** [comment]
@NickAragua @Windchild292 With HQ having a SPA for Clan Tech this can probably be closed unless anyone feels the current setup can take further refinements.

**Comment by Windchild292** [comment]
This has been resolved.
