### ISSUE TITLE
Give pilots a loyalty rating

### ISSUE THREAD

**Issue by VampireSeraphin** [MegaMek/mekhq#197]
For the next AtB update, can we give pilots a loyalty rating? This would take the place of the current misc mod system already in place. It would be different only in that it carries over and need not be set every retirement roll.

**Comment by Dylan-M** [comment]
This is actually an interesting concept. It could be done for opposing pilots too, and affect both how easy/difficult it is to get them to defect to your unit while also influencing their loyalty to your unit if they defect. The loyalty to the previous unit doesn't need to be a direct transfer to how loyal they would be to your unit, just have influence on it.

Say, if it's based on 0-100, with 100 being so loyal they'll never defect to 0 being will fight for whomever pays them the most, you can have varying degrees. Only the values of 0 and 100 should be a 1:1 transfer, since they're not likely to ever change. However, someone who is only 30% loyal to their current unit may be 70% loyal to yours if they defect, because maybe your unit treats them better or whatever.

**Comment by VampireSeraphin** [comment]
That would be really interesting. Mainly what I wanted to do was have some pilots who would never retire from the unit, but others who roll normally.

**Comment by Dylan-M** [comment]
Aye, but it can have many more implications. Even outside of AtB.

**Comment by VampireSeraphin** [comment]
Sure, and I like you idea. You could play with it a bunch of ways. Give you the option to pay cbills to force a defection roll on a prisoner as a bribe that increases their loyalty rating to you. It could affect how much ransom is paid by/for a prisoner when that option finally gets added. Probably lots more yet to be thought of.

**Comment by purpledragon2** [comment]
"Say, if it's based on 0-100, with 100 being so loyal they'll never defect to 0 being will fight for whomever pays them the most, you can have varying degrees. Only the values of 0 and 100 should be a 1:1 transfer, since they're not likely to ever change. However, someone who is only 30% loyal to their current unit may be 70% loyal to yours if they defect, because maybe your unit treats them better or whatever."

The only thing I think that might should be different here is that 0 would be take any job against player's unit and 50 would be fight for whomever.  Of course then adjust the other values accordingly.  Maybe HQ could then track a couple or a few "NPCs" in the background that could pop up for some of those "personal challenge" type of missions until such time as one or the other is unable to fight anymore.  Then you could have "recurring" enemies showing up on occasion.

**Comment by mchapman1970** [comment]
This concept would be great, and you could have the loyalty rating go up and down depending on how the member is treated, what type of campaigns you have, other outside forces,  whether the unit is winning or losing, if the unit is in the red or black financially I could go on...

**Comment by molemanBT** [comment]
I would like it if my leader/company commander had a very high rating so they'd almost never voluntarily retire, at least under the age of 50 or so? Have had them retire once or twice for no particular reason, and had to reactivate them.
