### ISSUE TITLE
AtB generates empty unit markets with traditional RATS

### ISSUE THREAD

**Issue by VampireSeraphin** [MegaMek/mekhq#204]
I figured out why atb was generating empty unit markets. In 3.32 and earlier if the in game year predates the chosen traditional RAT MekHq grabs the earliest RAT year and rolls. It could even fill the market with no RAT selected.

In the latest release, AtB only rolls on a RAT if the in game date is after the earliest RAT year. Eg a game in 3025 using XOTL RATS will generate no units in the market because the rats or 3028, but work fine in 3030.

**Comment by neoancient** [comment]
I made this change because we were getting bug reports of units appearing before their intro dates when the problem was that the user had not configured the campaign to use appropriate RATs. After thinking about it a bit more I think I was a bit overzealous and should restore the behavior of using the earliest available from those chosen. The problem was coming mostly from the last-ditch solution of defaulting to the primary canon souce (Total Warfare) if nothing else matched, and that's probably the only part I should have changed.
