### ISSUE TITLE
mekhq hangar bay shoulder damage or arm damage - after replacement

### ISSUE THREAD

**Issue by raenarre** [MegaMek/mekhq#206]
Repairable parts in Left Arm must be salvaged or scrapped first. They can then be re-installed.
error code 1 - in hangar bay
Left Arm is destroyed.
error code 2
only 2 things in the damage area listing for the mech

next issue/same issue
You cannot repair an arm with a damaged shoulder. This arm must be scrapped and replaced instead.
this is after scrapping and buying and replacing the arm.
same message as before replacing. damage is still there.

[mekhq shoulder damage arm damage errors 10-2016.docx](https://github.com/MegaMek/mekhq/files/542259/mekhq.shoulder.damage.arm.damage.errors.10-2016.docx)

**Comment by scJazz2** [comment]
To the best of what I can see this is working as intended.
Right click on the Arm and Select Scrap.
It looks like the replacement arm will arrive in a few days. Then you can replace it.

User Error?

**Comment by pheonixstorm** [comment]
What is the docx file supposed to be?

**Comment by HammerGS** [comment]
The word docx is screen shoots.  It appears that it is working correctly.

**Comment by raenarre** [comment]
i was able to scrap the first armi ordered a new partit came ini replaced itit still shows the messageafter replacement 
Paul Coulter
Event Horizon Games1496 Garner Station BlvdRaleigh, NC, 27603
www.EventHorizonGames.com
919-977-4009

**Comment by neoancient** [comment]
I'm not entirely sure what the problem is. The images show two different 'Mechs. The first is a Thunderbolt with a damaged shoulder. The second and third are a Spider with a destroyed arm (all internal structure has been damaged). The message for the first one is normal for a 'Mech with a damaged shoulder or hip. The message in the second image is normal for a 'Mech with a destroyed section that has not had all the equipment (including armor and actuators) removed. The third is normal for equipment that belongs in a destroyed section that has not been replaced.

Here is a detail list of the steps needed to make the repairs. Please indicate at which point the problem occurs:
1. In both cases the equipment needs to be removed (salvaged or scrapped) from the arm. Right-click on the 'Mech in the repair table and select "Salvage."
2. Find all equipment located in that arm, including armor and actuators, and either salvage them or right-click and scrap.
3. Right-click on the 'Mech and change back to repair.
4. In the case of the Thunderbolt with the damaged shoulder, right-click on the arm and choose scrap.
5. When you have a replacement part you can replace the arm and reinstall all the equipment.

**Comment by neoancient** [comment]
No problem found, issue creator has not provided any information that supports the claim that there is a bug.
