### ISSUE TITLE
47.11 Rare Award Tracker issue + workaround

### ISSUE THREAD

**Issue by gsparks3** [MegaMek/mekhq#2155]
Issue: the Award Tracker breaks if your campaign save has two Scenarios with the same Date, Type, and Mission ID. This is quite rare, but actually happened to me naturally, and I managed to reproduce it on a newly created campaign to verify that it wasn't just my old campaign being weird again. 

There are two levels of the issue - in the first level, the save fails to load properly at all, showing the error below:
![image](https://user-images.githubusercontent.com/59574316/96317525-e5597900-0fdc-11eb-94bb-d2cfee6b666b.png)
A campaign save demonstrating this issue is attached below.
[Bugtest2unfixed.cpnx.gz](https://github.com/MegaMek/mekhq/files/5394550/Bugtest2unfixed.cpnx.gz)

This can be _partially_ resolved by going to the Briefing Room panel, right-clicking on one of the scenarios in question, and editing the Scenario Name to something else, as shown below, and then saving the campaign. 
![image](https://user-images.githubusercontent.com/59574316/96319540-f5be2380-0fdd-11eb-9020-6867f8e85942.png)
A campaign save adjusted this way is attached below. This will eliminate the above error, and be accurately reflected in the Scenarios tab of the Award Tracker spreadsheet. 
[Bugtest2fixed.cpnx.gz](https://github.com/MegaMek/mekhq/files/5394578/Bugtest2fixed.cpnx.gz)
![image](https://user-images.githubusercontent.com/59574316/96319644-459cea80-0fde-11eb-89d4-0f643d1c691f.png)

However, this results in a _different_ error. In the actual Campaign Kills pivot table, the two scenarios will be merged into one, with only one Scenario:id displayed (note the "15", matching the table above, but "10" is missing). Also note that 8 kills are displayed, from two distinct lances (each lance deployed to only one scenario, with 4 kills each). 
![image](https://user-images.githubusercontent.com/59574316/96320081-50a44a80-0fdf-11eb-9af8-5de92d8b0b3d.png)
This appears to be because those scenario IDs are pulled from the personnel Mission Logs, which are unaffected by a post-facto name change in the Briefing Room. If _both_ scenario names are edited, the DateType from the Personnel Mission Logs no longer matches any of the Scenario names, and the summary breaks in a different way (see below), pulling the kills into an unnamed contract and scenario. 
![image](https://user-images.githubusercontent.com/59574316/96324153-48074080-0fee-11eb-9f8f-ea7016733a39.png)

As a workaround, if a player is aware of this issue and notices that two scenarios have been rolled with matching Dates and Types, they can rename one or both scenarios in the briefing room _before_ deploying to the scenario and resolving it. This writes the altered name to the Personnel Mission Log, completely avoiding the issue. If any effort is made to fix this, a hack to make this happen automatically might be the simplest method. Otherwise it can simply be left as a workaround, given that it's an extremely rare occurrence - having enough lances active to roll scenarios on the same day is already rare, and having both scenarios be the same type is even rarer.

**Comment by gsparks3** [comment]
Update: the issue can be fully resolved, post-facto, by renaming one of the missions in the Briefing Room panel, identifying the personnel associated with said mission, going to the Personnel panel, and manually editing the Mission Log entry for each of the associated personnel to match. 

From Bugtest2fixed above: 
![image](https://user-images.githubusercontent.com/59574316/97085452-9e2a4400-15eb-11eb-97ac-d0e45ca3b162.png)
1. Rightclick the desired Personnel in the Personnel menu.
2. Select "Edit Mission Log"
3. Select the entry for the mission that was edited in the Briefing Room panel and choose Edit Mission.
4. Manually edit the mission name to match whatever was entered in the Briefing Room panel - in this case, Hold the Line (Defender) 2
5. Repeat until the Mission Log has been updated for all associated personnel. 
6. Save the campaign and use the new save with the Award Tracker. 

This fully resolves the issue, as shown below. Note that Gamma Lance is now properly associated with scenario ID 10. 
![image](https://user-images.githubusercontent.com/59574316/97085637-96b76a80-15ec-11eb-9a5f-c29a6f544aff.png)
The final adjusted save is provided below. 
[Bugtest2fixed3.cpnx.gz](https://github.com/MegaMek/mekhq/files/5433101/Bugtest2fixed3.cpnx.gz)

Given that a fully post-facto workaround is available for this already rare issue, I am considering the issue closed. Should it arise for anyone else, the documentation on the workaround is available here.

**Comment by BullseyeSmith** [comment]
@gsparks3 Very impressive. The Mission Logs are what ties the missions & scenarios (horizontal axis of Campaign Kills) to the individuals that did the killing (vertical axis of Campaign Kills). While the Mission Logs do contain the unique person ID of the killer, they do not contain the unique scenario ID where the kill happened. That would require some java coding (@Windchild292, ...you still Da Man). To work around this, I use the only information available to both tables to tie them together; the date of the scenario & the type of scenario (hence the date-type column). If you change the name or date of a scenario after it is recorded in the mission log of the involved personnel, then the system cannot find a match. It acknowledges that they have a kill on the record, but it isn't matched to any of the scenario date-types, so it is listed on the horizontal axis as (blank).

**Comment by GiovanniBertuccio** [comment]
[AwardTracker_v4.xlsx](https://github.com/MegaMek/mekhq/files/10787201/AwardTracker_v4.xlsx)
The attached file should fix these issues

- Scenarios with the same name and date
- Pilots deployed to different scenarios on the same date
- Excel version errors related to CONCAT() versus CONCATENATE()

It works the same way by using the Settings tab to set a file path, using Data-> Refresh All, then under the Summary tab refresh the pivot table.

I expect this will never fail to merge, and instead will produce slightly wrong results; pilots that get kills in two different scenarios with the same name on the same date will have kills from both scenarios summed as if they were the same scenario.  This is an even rarer edge case than just two scenarios with the same name and date, so it should rarely be incorrect.
I haven't rigorously checked where it fails though.

I removed the reliance on the CONCAT() function, it still exists in some places, but will not break the parts that summarize kills.

It is slower and larger than the previous version because to ensure reliability I sequentially merge separate tables, instead of using a pivot table to merge many tables in a single step. Apparently Excel is very space inefficient this way and makes what should be kilobytes of info into megabytes.

I didn't restore the color-coding largely because I used the names of the missions and scenarios in the pivot table rather than the numerical IDs, and pivot tables don't behave the same when doing that.

I could not fix other issues that are related to how information is stored in the campaign data files.
Now, each person's kills are summarized as if they were always in the force they are in on the date the campaign was saved, rather than the force they were in on the date they got their kill.
To be accurate for a mission, pilots should retain their force assignment the entire mission, and the tracker should be run at the end of each mission immediately before rolling for retirement to be accurate. Only the most recent mission results should be used.

To be accurate regardless of changes in force assignments, and just to make this easier in general, the kills table would need these values
```date,	pilotId,	killed,	killer, scenario_ID, scenario name,	mission_ID, mission, unit_ID, regiment, battalion, company, lance```

Where each value for regiment, battalion, company, lance is the force ID of the killer unit on the date of the kill.
Instead of listing regiment, battalion, etc, it might work to use another sub-table that lists the force ID tree of the killer unit, but I haven't thought hard about that.
