### ISSUE TITLE
Enhancement: Alphabetize job-role dropdown menu within personnel tab

### ISSUE THREAD

**Issue by servo01** [MegaMek/mekhq#2159]
Being able to sort by Primary Role has been great, but the drop down menu might benefit from a little additional organization:

- Alphabetize listings for ease of navigation

- Standardize naming convention by using either "Conventional Infantry" or "Soldier" (but not both) 

- Add feature that allows sorting by subcategories in addition to specific job roles (i.e. being able to list ALL admin roles or ALL medical rolls as well as the more specific sorting for Admin/Type or separate listings for Medics and Doctors, etc..)

**Comment by Windchild292** [comment]
1) The roles are purposefully not alphabetized, but they are grouped into Combat and Support, then by the higher used formats with anything similar grouped under it. To implement it as described and actually be useful (so the general filters are located at the top of the list and extended filters at the bottom) would require manual intervention based on multiple factors, which is not worth doing for code maintainability reasons at a minimum.
2) Bug, fixed in #2163 
3) #2165
