### ISSUE TITLE
No Dynamic Opfor Generated in Special Mission

### ISSUE THREAD

**Issue by Setakka** [MegaMek/mekhq#2175]
### Environment
MekHQ 47.11
Windows 10
JDK 14.0.2

### Description
AtB generated a Star League Special Mission, and the related allied tech unit.  Failed to generate opfor after I assigned a unit to deploy.  Tested with multiple units of all 4 weight classes.
![image](https://user-images.githubusercontent.com/69232800/97376573-b5875c80-188b-11eb-9ab7-932b10fdaa63.png)

### Files
[Ottini Rangers30420308.cpnx.gz](https://github.com/MegaMek/mekhq/files/5448831/Ottini.Rangers30420308.cpnx.gz)
[Ottini Rangers.zip](https://github.com/MegaMek/mekhq/files/5448835/Ottini.Rangers.zip)
[Setakka AtB.xml.txt](https://github.com/MegaMek/mekhq/files/5448841/Setakka.AtB.xml.txt) (mekhq preset, remove .txt)
[unitQuirksOverride.xml.txt](https://github.com/MegaMek/mekhq/files/5448844/unitQuirksOverride.xml.txt) (remove .txt)
[megameklog.txt](https://github.com/MegaMek/mekhq/files/5448845/megameklog.txt)
[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/5448846/mekhqlog.txt)

**Comment by Windchild292** [comment]
Nothing in the logs, nor anything obvious in the campaign file.

**Comment by gsparks3** [comment]
From the campaign file, the allied mech is an Eisenfaust-2, which is a Primitive Mech. The official AtB rules for the Star League Cache 1 mission type say that if the cache mech is Primitive you can just keep it without a fight. This seems to be demonstrated by no opfor being generated for the mission; you just deploy whatever and immediately win because there are no enemies. I've had this happen before in my own campaigns. 

While displaying an empty opfor is a little odd, I would say this is working as intended.

**Comment by Windchild292** [comment]
Working as intended.
