### ISSUE TITLE
Possible Regression: Unable to export Personnel in 0.46.1 Stable

### ISSUE THREAD

**Issue by sixlettervariables** [MegaMek/mekhq#2180]
I'm not sure if this is the appropriate place to say this, but I think I'm supposed to comment on previous bugs instead of starting a one, even if they're closed. I am having this issue, same as #985 and this forum post: https://forum.megamek.org/thread-2608.html If I try to export personnel to an XML, I get a blank error popup, and no XML file. This happens regardless of whether it's my campaign or one of the pre-loaded campaigns. This happens regardless of where I try to save the file.

I am using 46.1. I'm not sure if my mekhqlog is applicable, but it's attached (apparently it's supposed to tell me what version of java I have, but I don't see that).
[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/5468334/mekhqlog.txt)

_Originally posted by @Felderburg in https://github.com/MegaMek/mekhq/pull/1015#issuecomment-719865122_

**Comment by Felderburg** [comment]
Per comments in slack, I am attaching cpnx files where this issue occurs for me. 2 are campaigns that come pre-loaded with the program, the third is my own.
github doesn't allow .cpnx files, so I have zipped the three.
It's worth noting that I confused xml and csv in my initial post; I am unable to export personnel or units to a CSV file. The two xml exports, and exporting finances to csv, appear to work properly (in that they create a file; I haven't looked at the xml files to verify that they are correct, but the finances csvs seemed fine).
[felderburgcpnz.zip](https://github.com/MegaMek/mekhq/files/5468384/felderburgcpnz.zip)

**Comment by Felderburg** [comment]
Just in case, the edited ranks file.
The only other files I've messed with are portraits and camo, adding pictures there (although I assume it's not the issue, since the default campaigns use portraits that came with the install).
[ranks.zip](https://github.com/MegaMek/mekhq/files/5468405/ranks.zip)

**Comment by Windchild292** [comment]
I've done some work on personnel export, namely fixing blank csv format, since then. Can you try on the latest develop?

**Comment by Felderburg** [comment]
Downloaded 47.11, that appears to have fixed the issue. The csv file has "?" for the "toughness" column for every person, even though I did modify toughness for a couple (and the others should still say 0). I also don't see that MIA personnel are marked as MIA. But the export does work, so this issue is resolved.

**Comment by Windchild292** [comment]
Seems like Toughness has a bug, and... MIA should be noted under Personnel Roles like active

**Comment by Felderburg** [comment]
Unless I'm missing something, I don't see any indication that the two MIA people are marked as MIA (mechwarrior "cardiac" and astech Zarkos).
[Felderburg_30270301_ExportedPersonnel.zip](https://github.com/MegaMek/mekhq/files/5471535/Felderburg_30270301_ExportedPersonnel.zip)

**Comment by Windchild292** [comment]
Subsumed by #2181
