### ISSUE TITLE
Incorrect Campaign Ops Transport Rating with No Dropships

### ISSUE THREAD

**Issue by dericpage** [MegaMek/mekhq#221]
If there are no dropships (and therefore no bays), the Campaign Ops Unit Rating is scoring a 10 for transportation when it should be scoring a -10.

**Comment by pheonixstorm** [comment]
not sure how related this is, but w/o a DS I am also getting this
![negativetransport](https://cloud.githubusercontent.com/assets/1787879/19950309/05af1368-a12d-11e6-8b1a-c5f3ab94e668.png)
and with, under the FMMr/CO rating
![incompletetransport](https://cloud.githubusercontent.com/assets/1787879/19950314/0e07a480-a12d-11e6-94b7-1b07d7279962.png)

The DS capacity is 45 heavy and 8 light. If it isn't related I will open a new ticket anf post the images again with two campaign files.

**Comment by dericpage** [comment]
It's a separate issue relating to how heavy vee bays can be used for light vees.  It doesn't affect the actual score but does look bad.

**Comment by pheonixstorm** [comment]
Checked with a different dropship type
![dsrating](https://cloud.githubusercontent.com/assets/1787879/19952012/44c3421c-a138-11e6-8bcb-ce30bbdadc09.png)

The DS used is a Gazelle so 15 of 20 tanks have a bay. This falls below the threshold so score should be -5. Will the PR fix that portion of what I have found?

**Comment by Dylan-M** [comment]
Umm, incorrect.
Light bays, you have 7 with 12 vees. 712=-5.
Heavy bays you have 15, but only need 8. So, you have 15-8=7.
Remaining light vees placed in empty heavy vee bays: 7-5=2 free bays after everything has a bay. That is correct. Your only real issue is the first one with no dropship showing -8.

**Comment by pheonixstorm** [comment]
Huh? If a Gazelle has 15 hvy bays and there are 20 total tanks, how do you get 2 free bays?

**Comment by pheonixstorm** [comment]
I see the problem now, the 7 in the light bay section is the leftover from the heavy vehicle bays. NOT additional bays that can be used. So it turns out that will cause issues in itself if the counts aren't clarified. As it stands it looks like there are a total of 22 available bays not 15 which is the actual capacity.

**Comment by dericpage** [comment]
I've created a new [issue](https://github.com/MegaMek/mekhq/issues/228) for the heavy vs light vehicle bay problem.

**Comment by Dylan-M** [comment]
@dericpage Look at how I handled it for the Overview tab. I think that works correctly.

**Comment by dericpage** [comment]
I've merged my changes and this should be fixed with the next release.
