### ISSUE TITLE
Request: Show Advanced Medical Die Rolls and Results in Daily Log

### ISSUE THREAD

**Issue by mkerensky** [MegaMek/mekhq#226]
Any chance of adding some transparency to the advanced medical rolls and results to the daily log?

**Comment by pheonixstorm** [comment]
You mean that clutter that was taken out? Pretty sure it could make it back in as an option. Probably not until after stable though.

**Comment by Dylan-M** [comment]
The answer to this is a resounding no. There are so many "dice" rolls involved in just a single injury, it isn't practical.

**Comment by Akjosch** [comment]
I moved most of the medical logging to the personal log anyway. The question isn't if we can, the question is always if we *should*.
```

Medical status for Hosni Lamaalem
[3067-01-04 12:00:00] Darcey Wren performed some amazing work in treating Bruised Right Leg (1 fewer day(s) to heal).
[3067-01-04 12:00:00] Darcey Wren performed some amazing work in treating A Broken Rib (2 fewer day(s) to heal).
[3067-01-04 12:00:00] Darcey Wren performed some amazing work in treating Cut Right Arm (1 fewer day(s) to heal).
[3067-01-04 12:00:00] Successfully treated Hosni Lamaalem fo 3 injuries
[3067-01-04 12:00:00] Bruised Right Leg healed

```

For the record, the plan is to display those in the medical detail dialogue only.

**Comment by Dylan-M** [comment]
That isn't logging all the dice rolls like was requested though, just what actually went on.

**Comment by jayof9s** [comment]
Yeah and just for awareness; the best way to understand what kind of clutter Dylan is mentioning would be to look through the rules (in the docs folder, I believe) but for each injury:

A roll made to determine if each hit was critical (1-5 rolls)
A roll is made for each injury to determine where they apply
A roll is made to determine which side for arms/legs
A roll is made for certain injury location/levels if there are multiple options

And it's been a while since I wrote the rules or did them by hand so I may be forgetting something. You can run through one by hand just to get a good idea of how many rolls that is but as they said, it would be very cluttered for what can be from 3-12+ rolls per injured person depending on the number of hits.

**Comment by Dylan-M** [comment]
Not to mention we did change things in the code as well. Since computers can do percentages that are difficult on dice, we changed a lot of your "rolls" from like 2d6 or whatever to a percentage chance (essentially < X on d100)

**Comment by jayof9s** [comment]
Actually, a lot of them already were d100 in my original rules since I was originally using a RNG and not dice and I wanted more granularity. But yeah, it doesn't look like what you'd expect from a Battletech dice roll.

**Comment by mkerensky** [comment]
Where is the personal log Akjosch quotes?  That's the sort of info I'm looking for - just wanted to know when my doctors succeed, fail or gain XP  and how my patients are winding up with so many permanent sprains :P.   Also, it would be nice to know if a patient got a bionic replacement or not, and how long it is taking to adjust to that. The document just says it may take a year, and doesn't really specify whether or not all lost limbs get replaced or what.

**Comment by Akjosch** [comment]
Nobody implemented any bionic replacements yet, as far as I know.

In any case, the refactor/cleanup is happening here: https://github.com/Akjosch/mekhq/tree/am_refactor2 - I'm in the "testing the crap out of it" stage and will make a PR later today. A few features are still missing (notably the ability to GM edit the injuries), but the detailed log entries are in.

Still no actual dice rolls though. I don't plan to add those for now.

**Comment by jayof9s** [comment]
Limb replacements were never implemented and while I documented rules for them, I mostly left it up to GMs, so it isn't an automatic process.

**Comment by mkerensky** [comment]
Good to know about the bionics.  I'll stop waiting on those guys to recover on their own...

How does a doctor gain XP?   X number of successful die rolls, like an admin or tech?  I have critical success XP turned on for rolling a 12, and I've had the daily log show a doctor get XP for a critical success once. Does that happen on a 100, or any critical success value according to the doctor's skill level?

Lastly, do doctors get any sort of penalty for being 'shorthanded' on medics?

**Comment by jayof9s** [comment]
Doctors should gain XP based on successful die rolls like admin/techs. And if critical success XP is on they should gain it for any roll that qualifies. In theory. Although I would have to see how it's coded to know if that's actually happening. It also might require a bit of rethinking since XP for critical success/failure wasn't a feature when I was designing the system and can happen quite a bit of elite/green doctors respectively.

As far as I know about short-handed, doctors without enough medics simply can't do their job but it's been a while.
