### ISSUE TITLE
Cannot repair broken LAM

### ISSUE THREAD

**Issue by JonhyBurner** [MegaMek/mekhq#2266]
MekHQ 47.14

So I had a busted mothballed Phoenix Hawk LAM for a while and decided to repair it using recently gained funds.  It had a missing torso (and arm), no avionics and a few other minor things.

I repaired the armor and actuators just fine, but can't replace the torso. It asks to remove salvage parts, but the location has none. When I try to scrap the component, it scraps instead an equivalent part in the warehouse. GM mode doesn't allow me to repair this either.

I can, however, use the GM tools at the hangar tab and restore the unit, but even then I have to do it more than once to fully repair it. Breaking other Mechs with GM mode and repairing them out of it works just fine.

[mekhqlog.zip](https://github.com/MegaMek/megamek/files/5648078/mekhqlog.zip)
[megameklog.zip](https://github.com/MegaMek/megamek/files/5648079/megameklog.zip)

[Busted LAM.cpnx.gz](https://github.com/MegaMek/mekhq/files/5648091/Busted.LAM.cpnx.gz)
[Busted LAM after one(1) GM restore.cpnx.gz](https://github.com/MegaMek/megamek/files/5648081/Busted.LAM.after.one.1.GM.restore.cpnx.gz)
[customs.zip](https://github.com/MegaMek/megamek/files/5648083/customs.zip)

**Comment by sixlettervariables** [comment]
The underlying entity does not seem to have any damage to the right torso, hence the issue with the replacement of the missing right torso.

Looking into the problem with GM Restore, but its likely the same issue.

**Comment by sixlettervariables** [comment]
Okay, I see the issue with the torso but I'm a bit out of my league on what the right fix is.
1. MHQ tracks a single Avionics part and a single Landing Gear part.
2. The LAM in question spreads those parts across multiple locations.
3. The underlying entity reports those critical slots as Repairable.
4. Because at least one critical slot in the location reports it is Repairable, you cannot remove the torso.

**Comment by sixlettervariables** [comment]
You have to GM restore it twice because:
1. During the first run through the parts, it cannot fix the Right Arm because it is missing a Right Torso still.
2. The Right Torso gets fixed.
3. You run the second time through and now it can fix the Right Arm.

**Comment by sixlettervariables** [comment]
I have a fix for the GM Restore issue (#2281).

After scrapping the avionics and landing gear, MHQ still believed there was equipment in the location.

@neoancient thoughts on MissingMekLocation::checkFixable and LAMs?
https://github.com/MegaMek/mekhq/blob/f1c853b9d33b0166e2e0654679653e40605cd237/MekHQ/src/mekhq/campaign/parts/MissingMekLocation.java#L240-L258
The landing gear and avionics both report repairable, even though both needed to be fixed. MHQ doesn't handle their multiple locations well.

**Comment by neoancient** [comment]
Avionics and landing gear are system slots, so you could add that to the check for shoulder and hip, which can't be removed. In the case of landing gear this is probably sufficient, because one of the crits is in the CT which is a non-removable location. Avionics is in each side torso and the head, so it's possible for it to be the last slot in an existing location.

**Comment by sixlettervariables** [comment]
Okay, I have some proposed code that makes this feel a bit better. I'll put up a PR to discuss.
