### ISSUE TITLE
47.16 Salvageable component in destroyed location shows TN, but is grayed out/Impossible in Repair mode

### ISSUE THREAD

**Issue by gsparks3** [MegaMek/mekhq#2387]
### Environment
47.16
Windows 10
Java 11.0.8

### Description
Salvaged a Stalker from my last fight. Had a missing leg from where I kicked it off, with two salvageable heat sinks left in the destroyed location. "Replace leg" task is grayed out and Impossible difficulty because "Repairable parts in Right Leg must be salvaged or scrapped first", which is normal. However, usually this causes the "Salvage [item]" task to pop up in a nice green in the Repair menu so you can rip the offending parts out easily. Currently, despite displaying a very feasible difficulty in the description box, that salvage task (in Repair mode, importantly) is grayed out, and if attempted proves to be Impossible rather than the listed difficulty. See below.

![image](https://user-images.githubusercontent.com/59574316/105272525-879e7500-5b67-11eb-85fa-7d6cafcc6f65.png)
Only one Heat Sink visible since I already tried to salvage the other one - note the result:
![image](https://user-images.githubusercontent.com/59574316/105272909-48bcef00-5b68-11eb-8d66-e5b59061c9cf.png)
Had to GM-mode Complete that task after this, since an Elite tech had "failed" to salvage the item and it was now considered truly unsalvageable.

However, if the unit is switched to Salvage mode, the salvage task appears green as it should, and can be completed. 
![image](https://user-images.githubusercontent.com/59574316/105274455-3db78e00-5b6b-11eb-8ce8-eafd7b7b8434.png)
![image](https://user-images.githubusercontent.com/59574316/105274680-a7d03300-5b6b-11eb-9fe4-15deeb4a454d.png)
(tested without saving, so you can test as well)

### Files
[Coppercoats.cpnx.gz](https://github.com/MegaMek/mekhq/files/5846591/Coppercoats.cpnx.gz)
No custom units or other files. 
[megameklog.txt](https://github.com/MegaMek/mekhq/files/5846605/megameklog.txt)
[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/5846606/mekhqlog.txt)
Logs don't appear to have anything related, but megameklog DOES appear to have an odd unrelated equipment unscrambling error (LRM 10 trying to associate itself with a PXH-1D?). Might be a separate issue in and of itself.

**Comment by gsparks3** [comment]
Another instance:
![image](https://user-images.githubusercontent.com/59574316/106218828-1afa2a80-61a6-11eb-9ae2-470faa17e9d9.png)
Grasshopper with two jump jets in a missing leg and a medium laser in a missing torso that are grayed out, plus a leg actuator in the same missing leg that is properly salvageable. All properly display the actual difficulty for the salvage task when selected.

[Coppercoats.cpnx.gz](https://github.com/MegaMek/mekhq/files/5890979/Coppercoats.cpnx.gz)

**Comment by sixlettervariables** [comment]
Okay this is one of those fun ones.
1. The task table gets its answer via Campaign::getTargetFor
2. The Do Task button and the Target Roll box get its answer via Campaign::getTargetFor

So why the difference? Well, the Do Task button and Target Roll box don't play fair and silently reset the tech on the part to the selected tech.
https://github.com/MegaMek/mekhq/blob/b1f5d7678e7b3b4c1590c13a7859f232748af561/MekHQ/src/mekhq/gui/RepairTab.java#L473-L483

That causes Campaign::getTargetFor to go down a different path because it believes you're salvaging the part, skipping the EquipmentPart::checkFixable message that the right leg is destroyed.

I don't have a good answer for the fix, as I feel confident changing the code in either spot will just break something else.

**Comment by sixlettervariables** [comment]
Well, I have a maybe fix...not sure of the ramifications.

**Comment by gsparks3** [comment]
I do find it interesting that it shows up differently for the actuator vs the non-actuator components. Not sure what causes _that_.

**Comment by sixlettervariables** [comment]
Actuators have their own part types rather than being EquipmentParts.

**Comment by JonhyBurner** [comment]
I'm reporting another repair bug, might relate to the same thing?

A Javelin with a damaged arm, failed the repair, had to scrap it, but after restoring the components the armor was still showing gray, with no option to repair it. The mech shows as undamaged in the hangar, but appears on the repair bay. Scrapping the grayed out armor allows me to repair it normally.

[Grand Campaign of Lisbon30290913.cpnx.gz](https://github.com/MegaMek/mekhq/files/5898259/Grand.Campaign.of.Lisbon30290913.cpnx.gz)
[megameklog.zip](https://github.com/MegaMek/mekhq/files/5898260/megameklog.zip)
[mekhqlog.zip](https://github.com/MegaMek/mekhq/files/5898261/mekhqlog.zip)

Save before the repairs:
[Grand Campaign of Lisbon30290908.cpnx.gz](https://github.com/MegaMek/mekhq/files/5898273/Grand.Campaign.of.Lisbon30290908.cpnx.gz)

**Comment by sixlettervariables** [comment]
@JonhyBurner not the same problem, that specific piece of armor has a minimum repair skill of more than Elite (aka its ruined). I think its a bit odd given there is no armor left in the location, but that's the reason.

**Comment by sixlettervariables** [comment]
@gsparks3 I'm going to go ahead and revert the fix I did. Looking at the code again, my fix was for a bug that isn't a bug in practice because MekHQ automagically switches to salvage in that situation. Now this is by convention and isn't guaranteed going forward if we were to introduce a new way of doing repairs or salvage, but for now that's the case.
