### ISSUE TITLE
AtB Contract Generation for Federated Commonwealth / Possible RAT issues

### ISSUE THREAD

**Issue by Thom293** [MegaMek/mekhq#251]
First - thank you for the awesome project.  Cant tell you how many hours I have spent with this.

Bug:

AtB Contract generated late 3058
Federated Commonwealth is the employer.  (according to wiki, Lyrans seceded in 3057, so it doesn't technically exist anymore).  
If it matters, Duchy of Small is enemy (part of Chaos March and also related to Lyran split, so more historical craziness during this time).
Light on my history, I accept and proceed to planet - start date February 3059.
Contract proceeds normally, but two problems arise:
I have a Liason contract, but during battle generation, it will not generate the 1 ally unit. Presumably because there is not RAT for Federated Commonwealth during this year.  If you go to GM tools and try to generate a mech - it will not generate one either - but if you switch to another entity, it will (Fed Suns, for example).
I edited contract and changed employer to Fed Suns and it started generating ally units correctly.  Again - I am presuming this is RAT/Timeline related.

Also - perhaps unrelated, because I have seen it with clans too, but very rarely I am getting "odd" numbered lance/star generation sometimes.  I have seen 5 unit lances, and 7 unit stars.  Not often, but often enough to notice.  I suppose it could be RAT related too - it could trying to roll units on a non-existant RAT and when it cant generate one it will just leave that spot empty - perhaps they are not 5 unit lances, but two lances with 3 missing...  Perhaps the Chaos March/Duchy of Small RAT isnt perfect during this transition period and it rolls up "empty" spots sometimes.

The issue with the Clan "odd" stars was in the 3056 timeframe, but I dont have that save to go back and look.  I THINK it was Smoke Jaguars, but not sure.

**Comment by Dylan-M** [comment]
Federated Commonwealth existed until 3067, when the FedSuns half renamed back to FedSuns.

**Comment by Thom293** [comment]
Ok - according to wiki Lyrans pulled out in 3057.  Regardless, there is no RAT associated with the Federated Commonwealth at least in 3059.  If you go to GM Tools, enter 3059 and select Federated Commonwealth and generate a unit, it cannot do so.  Or at least I cant.  So there is a RAT hole there it appears.

**Comment by pheonixstorm** [comment]
Don't forget. Sarna is not a canon source of information. While in most cases the information comes from canon sources and is fairly accurate the material in question must originate from a canon sourcebook, generally needed would be name and page reference.

**Comment by Dylan-M** [comment]
I looked at Sarna, and it includes the information about the naming of the FedSuns half heh. Just have to keep reading.

**Comment by Thom293** [comment]
I have all of the rulebooks, and some sourcebooks, but nothing on FedCom.  History or no - there is still a missing RAT. :)

**Comment by neoancient** [comment]
The actual dates for the Federated Commonwealth depend on whether you're looking at it as a political entity or a military one. As a political entity, it technically didn't exist as a single realm until 3055 with the death of Melissa Steiner, when Victor became Archon as well as First Prince. It continued until 3067, when the conclusion of the FedCom Civil War made official what had been reality since the Lyran secession a decade earlier, and the Commonwealth was formally desolved by renaming it to the Federated Suns.

From a military standpoint, it begins either with the close coordination of the AFFS and the LCAF starting in 3028 or the actual merger into the AFFC in the early 3040s and ends with the Lyran secession in 3057. Since we are concerned entirely with military matters, these are the dates that concern us. The dates for FC given in IOps are 3028-3057, and these are the dates used by the RAT generator. The Federated Commonwealth functions primarily as a merge of the FS and LA data, so I would have thought that it would still function outside that range. I'll look at the code when I get a chance and see why it's not doing that.

Separate issue: some scenario types limit the weight class of enemy units. If the opfor generation tables result in an assault (or sometimes heavy) unit, it is replaced by two smaller units. This is the reason for odd lance/star sizes.

**Comment by Thom293** [comment]
Thanks everyone for the answers, and the odd lance count thing.  

As an aside, out of all of the TROs and rulebooks and sourcebooks I have purchased over the years, I have never read a single BT novel.  Guess I should see if I can pick some up.

**Comment by neoancient** [comment]
Neither have I.

**Comment by Thom293** [comment]
FYI if it helps track it down more - as of June 1, 3060, AtB is generating contracts for BOTH Federated Commonwealth AND Lyran Alliance.
