### ISSUE TITLE
0.49-DEV-StratCon - VPs are not applied when battles are won

### ISSUE THREAD

**Issue by Kailan7401** [MegaMek/mekhq#2522]
### Environment
StratCon alpha test build (MekHQ CI with Gradle #1168: Pull request #2144)
Windows 10
OpenJDK 11.0.10

_Hey you stingy game
I worked real hard that win
Where's my VP point?!_

### Description
VPs do not appear to be added when victorious in scenarios. The issue appears to be present regardless of the scenario type. Manually resolving the pending Low Atmo - Destroy Dropship scenario in the attcahed save results in no gain in VPs.

### Files
[Campaign Info.zip](https://github.com/MegaMek/mekhq/files/6325813/Campaign.Info.zip)

**Comment by JonhyBurner** [comment]
Just to add that some scenarios victories add to the contract score, which I believe should no longer happen. And supposedly, multiple VP could be added, but so far, I haven't seen it.

An example here with a Pursuit scenario. Instead of a VP (2 VP?), it added 1 to the contract score.

[Void Corsairs Mission Score Bug Before.cpnx.gz](https://github.com/MegaMek/mekhq/files/6327919/Void.Corsairs.Mission.Score.Bug.Before.cpnx.gz)
[Void Corsairs Mission Score Bug After.cpnx.gz](https://github.com/MegaMek/mekhq/files/6327920/Void.Corsairs.Mission.Score.Bug.After.cpnx.gz)

**Comment by NickAragua** [comment]
I think I see the problem. Only scenarios marked as "required" (red text in the mini-briefing on the right side of the StratCon map) will affect VPs. Since the Marauders are on an Independent contract, you shouldn't actually be seeing any VPs.

I do need to adjust strategic objective tracking though, as it's showing 0/18 objectives.

**Comment by NickAragua** [comment]
The contract score is, at this point, irrelevant and I'm likely to have it no longer display when StratCon is enabled. 

Strategic objectives should now properly initialize/update for garrison type contracts as of commit 5d41cf620c66d5c182617d9f87fbf3c6e955a8dd
