### ISSUE TITLE
Cannot open context menu on children

### ISSUE THREAD

**Issue by monbvol** [MegaMek/mekhq#257]
[Experiment.zip](https://github.com/MegaMek/mekhq/files/614014/Experiment.zip)

I can open context menu on children of unit members up to 13 years old but older than that I can no longer right click to open the context menu on children of unit members.

Confirmed that this is not a problem for anyone else by GM adding new unit members using the bulk hire option to ensure they didn't suffer the same problem.

Attached before and after saves.
[ExperimentPart2.zip](https://github.com/MegaMek/mekhq/files/614016/ExperimentPart2.zip)
[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/614017/mekhqlog.txt)

**Comment by pheonixstorm** [comment]
I'm betting it has something to do with this
`Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at mekhq.campaign.personnel.Ancestors.checkMutualAncestors(Ancestors.java:113)
	at mekhq.campaign.personnel.Ancestors.checkMutualAncestors(Ancestors.java:99)
	at mekhq.campaign.personnel.Person.safeSpouse(Person.java:1004)`

I *think* after anyone turns 13 it starts making the safeSpouse check but something in yours is causing the code to barf. If I have the time I will look into the campaign file to see what the actual problem is.

**Comment by pheonixstorm** [comment]
Added a PR ( #258 ) that should fix this, just needs a dev to merge it.
