### ISSUE TITLE
RFE: Sort Personnel Tab Ranks Column by Rank Numeric, Rank Level, and then Natural Order Rank Name

### ISSUE THREAD

**Issue by Windchild292** [MegaMek/mekhq#2589]

**Comment by Duuvian** [comment]
Would it be possible to have the Unit Assigned column for a specific person be the same color the unit line in the Hanger would be due to damage? 

- [ ] Suggestion: It would be helpful if the Unit Assignment column in the Personnel tab was color coded according to the assigned unit's status (yellow for light damage etc), and even better if the same color coding could apply to the right click submenu in the assign to -> mek -> medium -> damaged/not full ammo Wolverine is yellow, inoperable Shadow Hawk is red; as an example.
