### ISSUE TITLE
[49.1+398] StratCon scn issues for build 398

### ISSUE THREAD

**Issue by Tecmes** [MegaMek/mekhq#2618]
This is a refresh of the #2575 for build +398.

** General issues**
- Maybe that's just me, and it's very useful for testing, but it feels like there's never a "basic" skirmish or stand-off, and also that there's always at least one and often many modifications. Two consquences is that some VP counts can become quite arcane, and also in quite a few scn your force end up crowded out by allies and enemies (in the provided screenshot, that's several minutes wait before each bot move....).  Is that the target mix for final release?

![CPU_killer_horde](https://user-images.githubusercontent.com/80174634/119067994-47ce8980-b9b1-11eb-9123-d1dcd4458f34.png)
(and THAT screenshot does not include the Tank Reinforcements, the Combat Drop, and the Pirate bombers that are due later! That's 75,000BV while my whole company is 23. I had to Remove that scn as it was unrunnable in my lifetime...)

- [ ] Succeeding at a mission brings a single VP regardless of the totals put forward by the debrief pane. For example I completed a DS destroy mission  (worth 3VP), but only got one. If it's a feature, it's not clear.
- [ ] In the same vein, non-StratCon scn such as Ambush don't seem to affect VP though the debrief pane lists VP results.
- [x] If you Manage Forces in a hex and send a lance, from then on, you can't access the Manage force context menu in that hex at all anymore, until you complete a scn, at which point it "resets". 
- [ ] Modifications showing as "Something.xml" rather than "Something" in MHQ.
- [ ] Not sure it is SC related. When saving a game in MHQ right before launching a mission, *after* assigning extra reinforcement, and then reloading and launching the scn, the game doesn't remember what was the main force and what was reinforcement and it groups everything in one bunch. This is obvious in deployement times; if you have a static slow lance and a reinforce scout lance, the delays will be quite short; but if you reload, they are bunched as one lance, and the scout units arrive at turn 0 and the slow lance units at turn 10 or much more, eventhough it's the same game with the same units). This basically cripples savegames made before combats with reinforcements (or you have to manually re-adjust all deployement delays). It doesn't seem to bungle OpFor deployements.
- [ ] With a permanent-deployed lance, it being also the selected main lance for a scn, I was "allowed" to deploy "extra" units because of my Leadership... except those units included those from the main deployed lance in question...

**Specific Scenario issues**

- [ ] Recon scenario: in many situations, this scn is surprisingly easy (which is not the StratCon norm!). You can often pull it off in 1-2 rounds. Maybe ask for a 4-hex scanning range like for turrets?
- [ ] Space - Blockade Run Escort. DS bot does not appear to be set to "Escape"
- [ ] Destroy Grounded DS - One of the obj is "Destroy or cripple or force to withdraw {enemy ground forces and DS}". What %? Also it is a bit confusing, because destroying the DS is the primary objective, so why is it part of that secondary?
- [ ] same - In a heavy fortress urban, the DS apparently didn't deploy at all.
- [x] Grounded DS modifier. The DS started at alt 5 (maybe a lobby bug, though). Maybe start it with zero fuel to prevent lift off attempts?
- [ ] Extract scn. The text appears mangled. It says "Extraction cannot be performed from destoyed buildings. [there's a period there and a line break, then:] for at least 28 turns". Also it's still not clear what to do, even if you have a mech or infantry near the building; also do you need to flee afterwards?
- [x] BadIntelAir. Not sure, but it seems the planes started at altitude zero. Also they started on EDG, which meant they deploye dright beside my units, which is not really good for them.
- [ ] EnemyTurrets modifier on a Allied - Defend scn is kind of weird!

**Comment by Duuvian** [comment]
This is my first post here so I thought I would piggyback on this issues thread with scenario things. I'll paste the ones I found. I'll upload a save too; I didn't make any customs so I think all you need is a campaign save or scenario save?

49.0 bugs:
MekHQ

Special Mission: Civilian Help
Civilian unit bot did not seem to auto-flee the board.. The bot also lacks a destination edge. Unsure if intended.

AlliedTraineesGround.xml: Three trainees will deploy alongside your lance. Keep them alive.
(This was listed twice in the scenario description in 49.0; but only one group of three is deployed in MM. Ihaven't tried a Cadre training contract in 49.1 so I don't know if earlier fixes caught this or not)

49.1 nightly May 19, 2021:
campaign savename: bugged dropship
Stratcon scenario deploys dropship correctly on first scenario attempt but it appears if megamek is closed without resolving the battle that the dropship will not deploy correctly on subsequent attempts. . Dropship missions also seem to tend to cause MM to lock up and require a forced exit from java.

If you gm remove a stratcon scenario on the briefing room tab, it persists on the stratcon map. There  also might be an issue with deployed forces being stuck in a removed scenario too but that might have been fixed in 49.1 (I began to manually undeploy forces and units before gm removing a scenario so I don't know if it was fixed in 49.1)

campaign savename: duplicateartillerybrokenmm
In the genscen, the friendly artillery unit is cloned in both MekHQ and MM lobby. MM fails at Transmitting game data... phase and does not load the MM map:

An allied facility has come under attack.

HouseOfficerGround.xml: The house commanding officer will deploy alongside your units. Keep them alive.

Evacuate: Get at least 75% of the designated units clear of the base.

AlliedArtySupport.xml: Allied artillery units will support your deployment with indirect fire.

HouseOfficerGround.xml: The house commanding officer will deploy alongside your units. Keep them alive.

Evacuate: Get at least 75% of the designated units clear of the base.

AlliedArtySupport.xml: Allied artillery units will support your deployment with indirect fire.


campaign savename: buggeddiversionscen
A diversion mission does not load opfor in lobby

A hostile force is attempting to delay your force from its objective. Destroy or bypass them quickly.

HouseOfficerGround.xml: The house commanding officer will deploy alongside your units. Keep them alive.

Destroy or rout 50% of the following enemy force(s) and unit(s):
	Capellan Confederation Primary Opfor
	 within at most 10 turns

Move at least 50% of the following force(s) and unit(s) to the destination edge and leave the battlefield:
	Fire Lance
	Crippled units do not count towards this objective.
	 within at most 10 turns

Preserve 100% of the following force(s) and unit(s):
	Lyran Commonwealth House Officer
	

Preserve 50% of the following force(s) and unit(s):
	Fire Lance
	Lyran Commonwealth House Officer

Sorry for the longish copy and pastes,

EDIT: Trying to upload the saves but github doesn't accept that file type. Is there a way to slam dunk the saves onto this post?

**Comment by sixlettervariables** [comment]
You can put them into a ZIP file with your customs.

**Comment by Duuvian** [comment]
Hey thanks, that seems like the kind of thing that, when told, a person suddenly realizes they should have realized already.

[savegames.zip](https://github.com/MegaMek/mekhq/files/6521679/savegames.zip)

**Comment by Tecmes** [comment]
Alright I think I'm done for now. I've played a few scn without encountering new issues.

**Comment by Tecmes** [comment]
It's the second time I get a Irregular forces scn with CRAZY OpFor. My auto-selected (integrated) lance is 2,400BV, allies are 1,800BV. The main Mech OpFor, alone, is 16,000BV, plus 14,000BV of troops, reinforcement and irregulars...

**Comment by Tecmes** [comment]
Here's a MM save for a very slow game. No log, though, sorry I overwrote it.
[slow_game.sav.gz](https://github.com/MegaMek/mekhq/files/6533354/slow_game.sav.gz)

**Comment by Tecmes** [comment]
I moved my part of this to #2633

**Comment by NickAragua** [comment]
Closing as the remaining issues are now a subset of #2633
