### ISSUE TITLE
Request: Ask before do something on File - New Campaign

### ISSUE THREAD

**Issue by binaryspica** [MegaMek/mekhq#2629]
### Environment
Ver 0.49.0

### Description
As title says. On File menu, there is the item 'New Campaign' just below of 'Save Campaign'. If you click it, it simply initiate the new campaign and there is no way to about the process. And it means, you are likely to accidentally click it when you are about to save the campaign(yes, I did it, although I didn't lose much).

So, can you add a warning popup to proceed, or about it and keep your current campaign?

**Comment by Windchild292** [comment]
This is invalid.
A) You can cancel out of the new campaign setup in the Campaign Options Dialog location.
B) The stuff that does get overwritten is due to #2335, which I will be fixing over the course of 0.49. It requires significant internal changes, which I have been doing backend changes to set the stage for.
