### ISSUE TITLE
[49.1] StratCon issues

### ISSUE THREAD

**Issue by Tecmes** [MegaMek/mekhq#2633]
(these are for the 49.1 official release)

- [x] Maybe there's something I don't get, but after six days in the mission, and scouting two places, I had already "completed one objective". At this point I had  done zero scenarios.
![objective_complete](https://user-images.githubusercontent.com/80174634/119366661-328e7f00-bc7f-11eb-988e-e5529c36fbec.png)
The same, after a single scn. I just don't get what's going on. It was a convoy escort, so I didn't "locate a facility" and I don't see how I would have completed any objective there? Also the "1/0" is odd.
![objective_after_one_scn](https://user-images.githubusercontent.com/80174634/119409015-a8610d80-bcb4-11eb-8fa2-c391f6aa874a.png)

- [x] Don't know if that's normal: an auto-assignment assigned my whole force (i.e. "My campaign") for a Prevent Recon mission (with massive opfor), including the ASF lance. I should note I had a loose unit in the root level of my forces, so maybe that's a cause.
Yep. Going to leave it as is for now, will revisit if it becomes a consistent problem.
- [x] Prevent Recon: I started in deployement "Any". Normal?
Yes, that's one of the possible deployment scenarios.
- [x] Still having turrets trying to deploy in maps with no buildings (e.g. "AlliedTurrets", "Searchandrescue"), though I suspect there's no way right now to change the map appropriately from MHQ.
Let's stop bringing this up for now, it's not going to change until major changes happen on the MegaMek side.
- [x] Irregular Force scn often generates insane amounts of OpFor, both in terms of counts and BV.
This one's weird - it's "unit count scaled", with 2x infantry and 2x "civilian" units as your primary force. It may have picked your root level force as the "primary" force. I'll revisit it at some point.
- [x] Succeeding at a mission brings a single VP regardless of the totals put forward by the debrief pane. I guess this is intentional. In that case, it could be written at the top of the objective part of scns: "Complete some or all of the following objective to gain up to 1VP".
  Added some descriptive text to "required" scenarios in StratCon tab to indicate that they will provide/lose 1 campaign VP.
- [x] In the same vein, non-StratCon scn such as Ambush don't seem to affect VP though the debrief pane lists VP results. 
  This is intended - scenario VP isn't the same as campaign VP. Mostly I left those in so that people could still get the occasional Star League Cache mission for (what is likely) an intro-tech bug mech.
- [x] Not sure it is SC related. When saving a game in MHQ right before launching a mission, *after* assigning extra SC reinforcement, and then reloading and launching the scn, the game doesn't remember what was the main force and what was reinforcement and it groups everything in one bunch.
Can't reproduce this with the most recent code.
- [x]  Leadership allows deploying extra vee/inf units... except the list shows units that are in the main deployed lances as well (and I don't think it changes deploy timing?).
This will likely be fixed with the next batch of changes. I think I'm going to say that the leadership auxiliaries deploy with the primary lance.
- [x] Recon scenario: in many situations, this scn is surprisingly easy (which is not the StratCon norm!). You can often pull it off in 1-2 rounds. Maybe ask for a 4-hex scanning range like for turrets?
- [x] Space - Blockade Run Escort. DS bot does not appear to be set to "Escape"
Can't reproduce this with the most recent code.
- [x] Destroy Grounded DS - One of the obj is "Destroy or cripple or force to withdraw {enemy ground forces and DS}". What %? Also it is a bit confusing, because destroying the DS is the primary objective, so why is it part of that secondary?
Text adjusted. Destroying the dropship and then retreating is intended to be one of the options. If you want battlefield control to capture the dropship or salvage the wreck, you'll need to rout the hostile forces and, since they're defending their ride, they're less likely to rout.
- [x] same - In a heavy fortress urban, the DS apparently didn't deploy at all.
Not much that can be done about it - sometimes there's no room to deploy it, similar to turrets. 
- [x] Extract scn. The text appears mangled. It says "Extraction cannot be performed from destoyed buildings. [there's a period there and a line break, then:] for at least 28 turns". Also it's still not clear what to do, even if you have a mech or infantry near the building; also do you need to flee afterwards?

**Comment by NickAragua** [comment]
Two questions:
1. Is this a brand new contract that was accepted in 49.1?
2. How many lances do you have in your TO&E? (It may be a rounding error)

**Comment by Tecmes** [comment]
1. Yes, I always restart fresh, new campaign, for a new version. 
2. I have two combined mech+BA lances and one ASF.

**Comment by JonhyBurner** [comment]
Adding an issue here to keep it tidy:

- [ ] On a Recon Raid contract, convoy escort scenario, description says: "50% of the following force(s) must reach the far edge of the map:" and then blank (the forces are obvious, but is still an omission)

**Comment by Tecmes** [comment]
Another odd StratCon situation (see save):
- just completed a scout recon.
- revealed two hostile bases
- no scn created
- Strategic  Objective things says to capture a facility at (6,6), but there's none there; it also says to defeat forces at (1,7), but they're not there... I'm not certain whether these objective were there before (why the [+] folding thing, btw?)
[odd_objectives.cpnx.gz](https://github.com/MegaMek/mekhq/files/6546696/odd_objectives.cpnx.gz)

**Comment by Tecmes** [comment]
The mine thing is cool, but (apart from the issue that the bot doesn't handle them so it's a hindrance) they're allowed in scn where it makes little sense. All those where you are the attacker... e.g. when attacking a hostile base you can plant mines right in the middle of their base. Maybe you have pretty good infiltrators, but I don't tihnk that's the intent.

**Comment by Tecmes** [comment]
These from [49.2 "small unit fix".]
- [ ]AlliedTraineeGround modifier doesn't seem to add anything. There's no force listed and no units in the lobby.

**Comment by Tecmes** [comment]
- [ ] Evacuating units in Allied - Evacuate scn are not set to ESCAPE.

**Comment by JonhyBurner** [comment]
- [ ] Capture scenario - allowed me to repair the deployed lance the same day, instead of the return date, 2 days later. Reloading the save shows that the lance is no longer deployed.

**Comment by Tecmes** [comment]
(The reason I'm not updating this is that I need to use the latest builds, and the nightly builds have failed for the past nine days...)

**Comment by Duuvian** [comment]
49.1 Snapshot
I have a mix of bugs to add, I haven't seen them posted after a quick glance aground so I'll throw them out on this post just to be sure:

I should mention I didn't realize that you can change tracks. I was confused why I couldn't find scenarios on the stratcon map sometimes until I realized you can change to the correct track to find it. It's possible that not knowing that until my most recent contract made me think there was a bug that was not present, so anywhere I mention not seeing a scenario on the stratcon map in the following descriptions it is likely to be that I hadn't figured out how to switch tracks yet.


- [ ] Campaign Save: bugclanmechgenerated

A Clan mech was generated for an Inner Sphere force decades before the Invasion. Lupus Prime in FWL enemy in the Big Battle: Free for All scenario

- [ ] Campaign Save: bugscengenemptyalliedair

The allied air appears to have failed to generate units for this scenario. I captured an enemy air base earlier in the contract that has been supplying allied aircraft for scenarios. It usually works as shown in the other pending scenario for this save, but the Diversion mission the training lance was autodeployed to does not have units in the Allied Air force in MekHQ.
Note: Another minor bug is apparent in the same save if you go to Personnel and look in the Cemetary. A deceased infantry officer was not removed from the infantry unit they were in when they died.

- [ ] Campaign Save: bugsgenscennotonmap, bugsgenscennotonmap2, bugsgenscennotonmap3

A generated scenario is unable to be deployed to from the Stratcon map, and when the scenario date arrives a warning about this pops up and the day of the scenario is pushed back a few days. (note: I think the following was because I didn't know you could change tracks on the map when I wrote it): There is a Recon scenario that I think is supposed to be on the Stratcon map, but I can't see it there. I had a force deployed as the Player force from the ToE (as I can't see the scenario on Stratcon map to deploy from there) and still received Stratcon warnings about not having a force deployed to the track when I advanced days until the day of the mission. In the third savegame, I have GM removed the broken genscen, but if you try to advance day MekHQ warns you that no unit is deployed on the deleted scenario's track. If you try to advance 7 days the warning appears again. Completing the contract seems to fix the problem.

- [ ] Campaign Save: buggenscennodropshipunit

A genscen failed to generate a dropship unit. 
Unnecessary information::The scenario generated a single aerospace fighter for the opposition bot. I gave my aerospace units to a princessbot on the same team as the player and they eventually shot down the lone enemy aerospace fighter after it went off map and returned several times. It was an interesting scenario, could be a good premise for another type. I marked it as a Marginal Victory in MekHQ.

- [ ] Campaign Save: bug2brokengenscens

Two generated scenarios failed to generate correctly. They also don't show on the Stratcon Map (note: may have been on other tracks and I didn't know). Neither generated opposing units and both have a mapsize of 0x0.

- [ ] Campaign Save: bugcannotcompletemission
The contract cannot be concluded as MekHQ says there are pending missions. There was a broken Stratcon scenario I had to gm remove to advance so I think it was that which broke the contract.

- [ ] Campaign Save: bugdoublesubunit
- [ ] If you deploy a subunit to a Stratcon scenario, you can deploy it a second time by deploying as reinforcements the formation it is part of. It would be cool if you still could do that but without duplicates arriving with the reinforcements, so you could represent a lance's company arriving as reinforcements.


[bugs.txt](https://github.com/MegaMek/mekhq/files/6654568/bugs.txt)
[mekhqlogbug2brokengenscens.txt](https://github.com/MegaMek/mekhq/files/6654569/mekhqlogbug2brokengenscens.txt)
[mekhqlogbugsgenscennotonmap2.txt](https://github.com/MegaMek/mekhq/files/6654570/mekhqlogbugsgenscennotonmap2.txt)
[mekhqlogcannotcompletemission2.txt](https://github.com/MegaMek/mekhq/files/6654571/mekhqlogcannotcompletemission2.txt)
[Riggs Raiders stratcon bugs2 saves.zip](https://github.com/MegaMek/mekhq/files/6654572/Riggs.Raiders.stratcon.bugs2.saves.zip)


Name; Rigg's Raiders

**Comment by NickAragua** [comment]
Out of curiosity, are you using one of the nightly builds or the 49.1 release?

**Comment by Duuvian** [comment]
The latest release actually, you are correct. My mistake. It's possible that I forgot this one wasn't a nightly and called it the wrong thing.

**Comment by NickAragua** [comment]
https://github.com/MegaMek/mekhq/pull/2701 contains the latest build of MekHQ that I'm using.

**Comment by Tecmes** [comment]
But as pointed out above, also by Duuvian, and in the forums, none of the nightlies have produced working builds for the past two weeks.

**Comment by Tecmes** [comment]
Oh! I see. I still don't quite see where the files are, but I'll get to it!

**Comment by NickAragua** [comment]
Scroll to the bottom, click on Details next to "MekHQ CI with Gradle". There's an "artifacts" dropdown in the top right.

**Comment by Duuvian** [comment]
Thanks, I'm downloading it now. I'll finish out the contract I'm on in the old version before bringing it over to that version.

**Comment by NickAragua** [comment]
Let's close this one down since it's getting a bit hard to manage and start opening up individual tickets for functional issues (game stoppers, things that put forces/units in an invalid/irrecoverable state, etc).
