### ISSUE TITLE
Eclipse reporting method getInstance is undefined for type MapSettings

### ISSUE THREAD

**Issue by pheonixstorm** [MegaMek/mekhq#27]
Description	Resource	Path	Location	Type

The method getInstance() is undefined for the type MapSettings	AtBGameThread.java	/MekHQ/src/mekhq	line 111	Java Problem

The method getInstance(File) is undefined for the type EntityVerifier	MekLabPanel.java	/MekHQ/src/mekhq/gui	line 107	Java Problem

The method getInstance(FileInputStream) is undefined for the type MapSettings	AtBGameThread.java	/MekHQ/src/mekhq	line 120	Java Problem

**Comment by arlith** [comment]
Where are you getting your MM src from?  I suspect it's pulling it from the MM jar included in MekHQ (this hasn't been updated since the TinyXML changes, so if you get MM from that jar, you will see these messages).  That jar could be updated.  This seems like the most likely culprit as it also explains why I haven't seen this issue (I have MML, MHQ and MM all added into Eclipse, and MHQ pulls its src directly from my MM repository).

**Comment by Dylan-M** [comment]
@arlith That is incorrect, I just updated it with new MM jar files this morning. This can now be closed as fixed. Doing so.
