### ISSUE TITLE
Tactics Campaign/MegMek  options bug

### ISSUE THREAD

**Issue by mnmib1** [MegaMek/mekhq#272]
MekHQ v41.27

There is a bug that if you turn commander's initiative off in the MM options in MekHQ, it also unchecks the Tactics box in campaign options.  In other words if you want to use Tactics with individual initiative rather than commander's initiative, you can't.

**Comment by pheonixstorm** [comment]
I don't think this is a bug as they work two entirely different ways.

**Comment by mnmib1** [comment]
This is certainly a bug.  I should not need to have commander's initiative on to be able to check the Tactics box in campaign options.  There are other uses for  the Tactics skill.  I may use it behind the scenes, having nothing to do with initiative at all.

**Comment by neoancient** [comment]
Rather than working in entirely different ways, they are actually the exact same thing -- they are two different ways of setting the same option. Unchecking it does not prevent you from developing the tactics skill in your personnel. I have changed the text of the label to indicate what the option actually does. Other than changing the MM game options, it also was used in generating a new `Person` to determine whether or not to roll for a possible starting tactics skill. I have changed this to roll for a possible tactics skill regardless of whether command initiative is used, since the settings for the likelihood of starting with tactics is actually controlled from the skill randomization tab.
