### ISSUE TITLE
RFE:  Option to have Daily Log always visible, and other Daily Log tailoring

### ISSUE THREAD

**Issue by Eruhin** [MegaMek/mekhq#2771]
In earlier versions of MekHQ, the Daily Log was always visible on the right hand side.  In more recent versions, it was moved to one screen.  

The Daily Log is possibly the screen I look at the most and was very useful on the right hand side of the display.  Since the Daily Log was put to one tab ("Command Center"), my flipping between tabs has gone up dramatically.

Can functionality be implemented to allow options for Daily Log location?  Options I would consider include:
1.  Use the new/current position (slaved to the "Command Center" tab)
2.  Slave to right hand side
3.  Slave to left hand side
4.   If slaved to one tab, have an option to turn on/off the highlighting of the tab when new info shows on the daily log, but you are not on that tab. 
5.  Define what information is displayed on the Daily Log.
6.  Detach from MekHQ ("Detach Daily Report Log" function as implemented in MekHQ 0.44.0).
7. Select which tab to be slaved to.
8. Select tab(s) to display the Daily Log (this would probably address items 1, 2, 3, and 7).

Those are the options I can think of considering.

Thank you!

**Comment by Windchild292** [comment]
This has been merged into the advance days dialog, which is now modeless and thus can be kept open at all times without causing any issues. I had the same issue with it, and found the advance days dialog was the perfect place for it.

I use it even when running a single screen, because that dialog is the main one for day advancement and thus the best pair for the daily log I can think of.

I did forget to make it start with the text from the base daily log, so I'll do that and then close this
