### ISSUE TITLE
Aerospace components repair time

### ISSUE THREAD

**Issue by EngelNUL** [MegaMek/mekhq#2854]
### Environment
0.49.3
Platform Windows 10 10.0 (amd64)
Java version 11.0.12
	

### Description
Aerospace asset repair times high or low.
FCS has 0 minute repair time
Other components in the 1000s of minutes

![image](https://user-images.githubusercontent.com/89315989/131522324-1b8b770f-c678-4756-a2f1-52cbac04ebb1.png)

[My Campaign30500114.cpnx.gz](https://github.com/MegaMek/mekhq/files/7084727/My.Campaign30500114.cpnx.gz)

**Comment by HammerGS** [comment]
Checking CampOps Second Printing, I think there is some weirdness with these repair times. 

Table starting on pg 205.

**Comment by mjbroekman** [comment]
Looking at the times in CamOps (3rd Printing) it looks like the Aerospace / Conventional Fighter times are using the Large Craft times.

**Comment by HammerGS** [comment]
Seem to recall the times where fixed for Campaign Ops as part of an errata.

**Comment by gsparks3** [comment]
I think the key here is that it is a "replacement" rather than a "repair" ... on page 206 of most recent CO, where the _replacement_ times are listed for Aerospace (Small Units), it does not seem to list a time to replace Avionics, FCS, or Landing Gear. Such times are listed for Large Craft, but they are extremely high (as might be expected for such large units). It seems here that the FCS is taking a value of 0 for "no entry", while the Avionics and Landing Gear replacements are instead using the values for Large Craft (which are rather absurdly high for an ASF).

I do not see any errata related to replacement of these integral components for small aerospace units. Repair (not replacement) times for these components are listed for all aerospace units on page 207. May need clarification from CGL here.

**Comment by mjbroekman** [comment]
Replacement times are listed on pg 206 (CamOps, 3rd printing) and I would think that Avionics, FCS, and landing gear are part of "Weapons and Other Equipment" (120 minutes).  **Repair times** for Aerospace units are on pg 207 (CamOps, 3rd printing) and have all parts listed out separately with no "Other Equipment" line.

**Comment by Saklad5** [comment]
This is clearly supposed to be 480 minutes, at least for repair, so I'm going to go ahead and fix that for the sake of my own sanity.

**Comment by Saklad5** [comment]
<img width="463" alt="image" src="https://github.com/MegaMek/mekhq/assets/4258823/1e0e12f5-21ff-4582-9812-6e676abd398d">
Is anything besides Avionics incorrect?

**Comment by HammerGS** [comment]
I think there was a bunch of these needing tweaks. We provided CGL with recommendations that got accepted into errata for them.
