### ISSUE TITLE
Pilots being generated with special abilities in the battle even though special abilities are turned off

### ISSUE THREAD

**Issue by Question2** [MegaMek/mekhq#291]
After spending xp to increase some pilot gunnery/piloting levels, some of them are now showing up in megamek with special abilities even though special abilities are turned off in both mekhq and the mekhq megamek settings.

MekHQ and the megamek lobby are both showing the pilots as having no special abilities, but once the battle starts (latest scenario in the list), the first 4 units have pilots with special abilities.

[test.gz](https://github.com/MegaMek/mekhq/files/673759/test.gz)

This is for 41.28, uploading the zip file as a .gz because github wont let me upload zip files for some reason.

**Comment by neoancient** [comment]
The AtB rules provide a possibility of gaining an SPA when reaching veteran and elite levels, which is where the new SPAs were coming from. I've added a check there so that the new SPAs are only awarded if SPAs are in use. I've also added a check to the unit market, which was automatically generating them for new crew.

In cases where special abilities have been disabled but some personnel previously had them, they still exist even if not shown in MekHQ and are transferred to MegaMek or written to a MUL file, so I added another check there.
