### ISSUE TITLE
Still capturing prisoners even though "random enemy capture" is set to off

### ISSUE THREAD

**Issue by Question2** [MegaMek/mekhq#297]
Even though i have random enemy capture set to off, i am still capturing prisoners for some reason? See the campaign save and daily log.

[test.gz](https://github.com/MegaMek/mekhq/files/679696/test.gz)

**Comment by neoancient** [comment]
There is a "capture prisoners in scenarios" option on the personnel tab that is checked. This uses a different method than AtB and is based on likelihood of escape rather than a random roll. It is possible to have both methods in operation simultaneously, but they really need to be consolidated with a choice of which method to use.
