### ISSUE TITLE
Comstar ranks do not take into account service years when determining the main "pilot" of a vehicle

### ISSUE THREAD

**Issue by Question2** [MegaMek/mekhq#300]
For vehicle crews, mekhq appears to use the highest ranking personnel to determine the main "pilot" of a vehicle (the one that the vehicle appears to be assigned to and which is shown in megamek, and to determine special abilities).

For example, if you had a crew of 4 assigned to a vehicle, 3 of which were privates and 1 of which is a sergeant, the sergeant would be the main "pilot".

With comstar ranks, you can assign them so that you have a crew of 4, one of which is an Acolyte II and three of which are Acoytle Is, but the Acolyte II which is more senior does not take priority.

Might be related : Vehicle personnel with comstar ranks only show "Acolyte" instead of "Acolyte Lambda II" in the personnel tab.

![megamek](https://cloud.githubusercontent.com/assets/1191378/21596926/86744d30-d196-11e6-821f-09fef862e8c5.jpg)

[test.gz](https://github.com/MegaMek/mekhq/files/681367/test.gz)

**Comment by Dylan-M** [comment]
Two Things:
1. Yes, I can guarantee this is just for Comstar ranks because the rank comparator doesn't take sub ranks into account. This should be relatively easy to fix.

2. That isn't the same issue at all, since as you can see it shows it for other personnel types. This is just a display issue, but should also be an easy one to fix.
