### ISSUE TITLE
RFE: Please add ability to customize camo of allied and opposing forces upon contract acceptance

### ISSUE THREAD

**Issue by OrbMonky** [MegaMek/mekhq#3044]
### Environment
0.49.6
Windows, Mac, or Linux? Windows 10
Java JDK 11.0.11.9-hots

### Description
Currently allies default to red and opponents default to green, which is all well and good for a Liao vs DC contract where you're aligned with Kurita, but otherwise becomes tedious and non thematic to have to manually configure every generic unit's camo (yes, you can select and configure multiple units at once but even with that it is often forgotten). This feature would help ease the burden on GM's and people playing personal campaigns to simplify configuration of matches.

Proposal; somewhere on contract acceptance screen or as a configurable option while in contract be able to adjust default camo schemes for allied/enemy/pirate/'unknown hostile' etc forces for that contract's duration.

### Files
N/A feature request

**Comment by SuperStucco** [comment]
You can already do that in the Briefing tab, under the "Edit Mission" button.  However that only controls the "Ally camo" and "Enemy camo".  It also resets during defense contracts where the enemy morale drops to rout and the OpFor is reset.

I would like that extended a bit, so that all the various forces that can appear in a scenario can be assigned camo e.g. 'Civilian Allies', 'Unknown forces', 'Allied base turrets', 'Allied liaison officer'.  As an idea, something in the campaign options where it provides a list of standard forces and the associated camo.  New force names could be added/removed to support custom-built scenarios.  There would always be three fixed rows, one each for the normal ally/enemy and one default for any force names not in the list.  The OOTB MekHQ configuration can keep the current red/green, or put in a bit of time to select decent defaults for the major factions.

**Comment by OrbMonky** [comment]
Yes, good point, I also included the 'etc' forces like civilians / unknown hostiles / what have you. Extending to every possible type of force might be good but also could be cluttery, I'd like to see it if it can be done though.

**Comment by SuperStucco** [comment]
That's where the mandatory defaults would come in - if it's not in the list, it picks up the appropriate ally/enemy/other default instead.

**Comment by Windchild292** [comment]
This RFE is solely relating to the graphical improvement request whereby you can customize the contract upon contract acceptance.

@SuperStucco
As I've said previously, do not attach a second RFE as a comment to a separate RFE, even one that would be somewhat related. One issue per issue, never more.

**Comment by IllianiCBT** [comment]
Closing as resolved (kinda, see above linked PR)
