### ISSUE TITLE
(0.49.6) AI Opposing Force Not Loading from MekHQ to MegaMek

### ISSUE THREAD

**Issue by Eruhin** [MegaMek/mekhq#3063]
### Environment
What version of MekHQ does your issue apply to?  0.49.6
What operating system are you using?  Windows 10
What java version are you using?  Java Version 16.0.2

### Description
When I launch MegaMek from inside MekHQ, my units will load, but not the AI opposing force.  

I encountered this yesterday when I started playing with 0.49.6.  Closed and re-launched the scenario from the Briefing Room, Start Game, button several times.  More of the AI opposing force populated until it transferred completely to MegaMek and I was able to play the mission.  After the mission, I shut down for the night.  Today I have tried several times (5-10 times at least) to launch MegaMek, and the AI opposing force units never load.

One thing that might be part of the issue is I was about to launch the second mission last night and noticed I had not healed my people, so delayed the mission using the Briefing Room's mission editing (right click on mission name, use the date button on the pop-up to adjust).   

### Files
Here are the log files.  I ran completely through the scenario where no mechs loaded. 
[Test Campaign--11 Jan 22.cpnx.gz](https://github.com/MegaMek/mekhq/files/7858413/Test.Campaign--11.Jan.22.cpnx.gz)
[megamek.log](https://github.com/MegaMek/mekhq/files/7858425/megamek.log)
[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/7858426/mekhqlog.txt)
[mekhq.log](https://github.com/MegaMek/mekhq/files/7858432/mekhq.log)

**Comment by kernhe** [comment]
similar to #2956 ?

**Comment by Eruhin** [comment]
Very similar.  I didn't see an issue specifically with friendly bots spawning on the other team.  I did encounter most of everything else described in 2956.
    On Friday, January 14, 2022, 03:18:00 PM CST, kernhe ***@***.***> wrote:  
 
 


similar to #2956 ?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Windchild292** [comment]
Java 16 is completely unsupported at this time. Please immediately downgrade to Java 11

**Comment by Eruhin** [comment]
Downgraded to Java 11.0.13.  Now when I launch MegaMek from MekHQ, I always disconnect from the server while MegaMek is launching. (10+ attempts)

**Comment by Windchild292** [comment]
That may be because of an issue in the downgrade or saved bad data from using Java 16. 

For the first, please use this guide: https://github.com/MegaMek/megamek/wiki/Updating-to-Adoptium.
For the second, please delete any .preferences file in mmconf and delete the client settings xml file.

If it persists with those two fixed, then please comment with the logs during the load.

**Comment by Eruhin** [comment]
Performed items 1 and 2 as requested.  
Started a brand new campaign to test.
Still disconnected every time MegaMek launched from MekHQ.  I performed ten (10) attempts with the same results.

Here are the files.
[Test--17 Jan 22.cpnx.gz](https://github.com/MegaMek/mekhq/files/7884331/Test--17.Jan.22.cpnx.gz)
[mekhq.log](https://github.com/MegaMek/mekhq/files/7884338/mekhq.log)
[megamek.log](https://github.com/MegaMek/mekhq/files/7884339/megamek.log)
[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/7884340/mekhqlog.txt)

**Comment by Windchild292** [comment]
```
13:40:45,609 ERROR [mekhq.AtBGameThread] {Test Campaign}
mekhq.AtBGameThread.run(AtBGameThread.java:381) - 
java.lang.IllegalArgumentException: Total board area must be positive
	at megamek.common.MapSettings.setBoardSize(MapSettings.java:545)
	at mekhq.AtBGameThread.run(AtBGameThread.java:119)
```

Regenerating the OpFor should fix that issue.

**Comment by Eruhin** [comment]
Not sure how to regenerate the OpFor...

I deleted the scenario and advanced in days.  Had more scenarios generate and ran into the issue described in incident 2956. 

Only once in several tries of launching MegaMek from MekHQ did all OpFors load, then closed MegaMek and nothing again except for my units.

Additionally, while writing this, I had a failed MegaMek load running.  After several minutes, the first enemy opfor still had not loaded, numbers 2 and 3 had loaded, but then MegaMek disconnected.

Here are the files:
  
[Test--17 Jan 22.cpnx.gz](https://github.com/MegaMek/mekhq/files/7884417/Test--17.Jan.22.cpnx.gz)
[mekhq.log](https://github.com/MegaMek/mekhq/files/7884420/mekhq.log)
[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/7884421/mekhqlog.txt)
[megamek.log](https://github.com/MegaMek/mekhq/files/7884422/megamek.log)

**Comment by Windchild292** [comment]
Regenerate is done in the scenario table, right click, edit, bottom buttons. However, it's not the cause of the new failure. This one is a player registration failure, in the connection between MekHQ and the lobby.

A few questions:
1) Did you use the default Windows zipper, 7Zip, or another zip software?
2) Are you running a VPN, Citrix, or similar software?
3) Have you run torrent software since your last computer restart?

Also, MekHQ Options, Miscellaneous Options, Delay Timer. Increase the value to 1,000 or 2,000. This may assist.

**Comment by Eruhin** [comment]
To answer your questions:
1.  I used the default Windows zip program.  The exact procedure I used to extract the files is: I double clicked on the zip folder, opened it, copied all files inside it, then pasted to the desired destination folder.
2. I am not currently running a VPN, Citrix, etc.
3.  I restarted my computer after fixing Java, then started MekHQ to run the test.  I rarely use torrent software anyway.

I set the delay to 2000, then 1000.  I launched MegaMek three times for each delay from MekHQ and OpFors loaded with no issues in MegaMek.

After the above testing, keeping the delay timer on 1000, I played through one complete battle, then repaired and advanced MekHQ to the next battle.  That battle launched with no issues as well.  Everything loaded and no disconnects.

**Comment by Windchild292** [comment]
Glad the restart and delay changes fixed your issues.

However, please extract a new install using 7Zip or another working zipper, and use that instead. This'll prevent some strange issues due to bugs in the broken Windows zipper (https://github.com/MegaMek/megamek/wiki/Slow-Unzipping-or-Errors-Unzipping).

I'm going to push up a default setting change for the delay timer, and consider this as resolved.

**Comment by Windchild292** [comment]
(Default value change is in https://github.com/MegaMek/mekhq/commit/61b44ec5b8543206fcf28b247befe7e31204a832)
