### ISSUE TITLE
Contract Payment Multiplier cannot be changed

### ISSUE THREAD

**Issue by kutagh** [MegaMek/mekhq#308]
Reported on Slack MegaMek-public by scjazz and verified by me, both on 0.42.0:

In GM mode, going to the briefing tab and adding a new mission/contract, you have a bunch of options including a payment multiplier. This multiplier is fixed to 1.2 (for me, for scjazz 1.125), using any method of editing there does not change it (neither arrows nor textual input, after the attempted change it changes back to 1.2). scjazz also reported that changing PaymentMultiplier in the CPNX does not affect the campaign.

**Comment by SirMegaV** [comment]
Made a similar feature request on sourceforge https://sourceforge.net/p/mekhq/feature-requests/304.

**Comment by pheonixstorm** [comment]
AtB itself is not very flexible about this so not sure of the likelihood of this request going anywhere. Though it could get its own option to toggle on/off. I know the pay under the FMMr rules is way too low but if using the Campaign Operations reputation and payment (5% value of combat units) the pay is more than adequate.

Perhaps a better option would be to base the multiplier on the system used (FMMr, CO) rather than just CO (which AtB was based on when the IO beta merc rules were released).
