### ISSUE TITLE
Change Unit Organization

### ISSUE THREAD

**Issue by Chichengunga** [MegaMek/mekhq#311]
The ATB documentation makes note of changing unit organization to level 2 or star if playing a structure that uses non lance based units. However if the present version, there is no option to unit organization in the ATB options while still playing as a mercenary unit. There is an option to change factio to Comstar/WoB to achive the change in unit organization however this does not allow for a novel merc force to have this non-standard structure.

Can this be added back? My current campaign backstory fluff uses a 6 unit structure however doing so with a mercenary funciton imposes a 390 ton limit and more importantly generates forces assuming im using heavier mechs than i am.

**Comment by Menzius** [comment]
If you are referring to the AtB documentation.txt, what I wrote are only opportunities of how to organise your TO&E within the current ruleset (3-6 units, 130-380tons). You can avoid these restriction by disabling Limit Lance deployment by weight/size in the AtB options. To adjust the OpFor generated use the Skill level and the options under Scenarios in the AtB Tab. As long as you are playing as Merc always use Mercenary as Faction.

As far as I can tell there is no feature to be added back because it was never in the programme - anything you want to do can be done by changing options.

**Comment by Windchild292** [comment]
Closing as this is already implemented between the AtB options "Limit lance deployment by weight" and "Limit lance deployment by size". Otherwise, the weight balancing is just how AtB is.
