### ISSUE TITLE
Purchasing aerospace sensors via 'purchase parts' are always 0 ton.

### ISSUE THREAD

**Issue by hodlum** [MegaMek/mekhq#314]
When purchasing "Aerospace Sensors, 5-200 tons" via the marketplace -> purchase parts option, an entry is added in the procurement list for 'Aero Sensors, 0 tons'.

This occurs regardless weight entry selected, from 5 tons to 200 tons. Selecting any weight entry will add multiples of the same incorrect procurement item.

This behavior also occurs via the Overview -> parts in use, purchase options.
additionally, the listed cost for all weights of 'Aerospace Sensors' in Overview is 0 c-bills. 

adding via GM mode does not cause this, and adds the correct item.
using the acquisitions options in the repair bay does not cause this, and adds the correct item.

Can be confirmed in a fresh game, no mods enabled. 0.42.0

**Comment by BLOODWOLF333** [comment]
I think thats just how @akjosch designed it.  Gyros are the same way, in the parts in use tab it clumps all the gyros into one entry but if you go into the warehouse tab you will still have 1-4 ton gryos same with Aerospace sensors.  You just have to go into the purchase parts dialog to get the specific tonnage you want instead of ordering from the parts in use tab.

**Comment by neoancient** [comment]
It's a legitimate bug. Parts on order are tracked the same way as missing equipment is, but `MissingAeroSensor` ignores the unit tonnage. I have a fix for this but I can't push it until I'm somewhere with Internet access for my laptop.
