### ISSUE TITLE
Unable to load campaign file after BattleArmor refit

### ISSUE THREAD

**Issue by Shenaldrac** [MegaMek/mekhq#317]
Attempting to load a saved campaign file, get a little popup window saying the save cannot be loaded and to see the log file. This seemed the appropriate place to report. MekHQ/Megamek/Meklab log files, custom units file for the campaign and the campaign file itself are included in the link below. Version 42.20

https://dl.dropboxusercontent.com/u/94245000/Regal%20Force%20bug%20report%20relevant%20files.rar

**Comment by HammerGS** [comment]
Relevant section from the Log:

Seems to be something with BattleArmor Parts.
```
Attempted to change ammo type of non-ammo
Attempted to change ammo type of non-ammo
java.lang.ArrayIndexOutOfBoundsException: -2
	at mekhq.campaign.unit.Unit.initializeParts(Unit.java:1805)
	at mekhq.campaign.Campaign.createCampaignFromXMLFileInputStream(Campaign.java:4108)
	at mekhq.gui.dialog.DataLoadingDialog$Task.doInBackground(DataLoadingDialog.java:188)
	at mekhq.gui.dialog.DataLoadingDialog$Task.doInBackground(DataLoadingDialog.java:115)
	at javax.swing.SwingWorker$1.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at javax.swing.SwingWorker.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
```

**Comment by honehe** [comment]
Same issue.
if it helps:  I can load early save with no unit assigned to lances, however everything past that stage is is crash without notification ( MekHQ 0.42.0
`Exception in thread "AWT-EventQueue-0" java.lang.ArrayIndexOutOfBoundsException: 120
	at mekhq.campaign.parts.EnginePart.getTonnage(EnginePart.java:77)
	at mekhq.campaign.parts.PartInUse.<init>(PartInUse.java:44)
	at mekhq.campaign.Campaign.getPartInUse(Campaign.java:1351)
	at mekhq.campaign.Campaign.getPartsInUse(Campaign.java:1393)
	at mekhq.gui.CampaignGUI.refreshOverviewPartsInUse(CampaignGUI.java:5114)
	at mekhq.gui.CampaignGUI.refreshOverview(CampaignGUI.java:4975)
	at mekhq.gui.CampaignGUI.initComponents(CampaignGUI.java:787)
	at mekhq.gui.CampaignGUI.<init>(CampaignGUI.java:566)
	at mekhq.MekHQ.showNewView(MekHQ.java:171)
	at mekhq.gui.dialog.DataLoadingDialog$Task.done(DataLoadingDialog.java:291)
	at javax.swing.SwingWorker$5.run(Unknown Source)
	at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.run(Unknown Source)
	at sun.swing.AccumulativeRunnable.run(Unknown Source)
	at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.actionPerformed(Unknown Source)
	at javax.swing.Timer.fireActionPerformed(Unknown Source)
	at javax.swing.Timer$DoPostEvent.run(Unknown Source)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)`

**Comment by Dylan-M** [comment]
Was this created on a significantly older version of MHQ?

**Comment by Shenaldrac** [comment]
Some of the personnel and units were imported from a significantly older version, yes. However all BA and infantry are from 42.20.

**Comment by Dylan-M** [comment]
There is no 42.20, there isn't even a 0.42.20. There's only 0.42.0.

Ignoring that, this is a unit issue likely caused by importing units from a much older version. It is not an actual issue with those code, though the error handling could be a lot better.

**Comment by Shenaldrac** [comment]
I'm so sorry, I mis-read the version number. Yes, it's 0.42.0.

And it might be an importing issue, however I can load an earlier campaign file from after stuff got imported and it works fine.

**Comment by pheonixstorm** [comment]
Can you post the earlier campaign as well?

Minor note. Some BA still cause issues while loading, or at least certain parts do from what I remember. 

@honehe you need to start your own ticket. Yours is a different issue from this one. Make sure to attach you log file and zip up your campaign file and any custom units you are using.

**Comment by Shenaldrac** [comment]
Sure, here's the last campaign file I can load. There's about a dozen more after that the game was able to successfully save during a long play session, then the next day when I tried to load latest file, well, it didn't. I tried loading previous saves until I found this one. 

https://dl.dropboxusercontent.com/u/94245000/Regal%20Force30760820.rar

**Comment by pheonixstorm** [comment]
Did you salvage any BA during any of those games?

**Comment by Shenaldrac** [comment]
I didn't salvage any BA, but I did recruit some BA squads from the hiring board, and refitted a few of them to different configs I preferred (IE, swapping from cavalier (Flamer) to cavalier (Small Laser)).

**Comment by pheonixstorm** [comment]
Its possible. If you were in the middle of a refit when you saved the last game that could also be the issue.

**Comment by Shenaldrac** [comment]
That might be the case.

**Comment by Dylan-M** [comment]
I'm fairly sure it's the refits, but I'm still debugging. I got called away. earlier.

**Comment by Dylan-M** [comment]
So yes, definitely the refits:
`Attempted to change ammo type of non-ammo
Attempted to change ammo type of non-ammo
There was an error with the following: Unit#11511940-dd80-4af4-a8e3-1f1868ae7b69, Cavalier Battle Armor [Flamer]
   Error caused by: Part#123132, Flamer
There was an error with the following: Unit#11511940-dd80-4af4-a8e3-1f1868ae7b69, Cavalier Battle Armor [Flamer]
   Error caused by: Part#123124, Cavalier Battle Armor [Flamer] Suit
There was an error with the following: Unit#11511940-dd80-4af4-a8e3-1f1868ae7b69, Cavalier Battle Armor [Flamer]
   Error caused by: Part#123116, Cavalier Battle Armor [Flamer] Suit
There was an error with the following: Unit#11511940-dd80-4af4-a8e3-1f1868ae7b69, Cavalier Battle Armor [Flamer]
   Error caused by: Part#123108, Cavalier Battle Armor [Flamer] Suit
There was an error with the following: Unit#11511940-dd80-4af4-a8e3-1f1868ae7b69, Cavalier Battle Armor [Flamer]
   Error caused by: Part#123100, Cavalier Battle Armor [Flamer] Suit
Trooper location -1 found on BattleArmorSuit attached to unit
Trooper location -1 found on BattleArmorSuit attached to unit
Trooper location -1 found on BattleArmorSuit attached to unit
Trooper location -1 found on BattleArmorSuit attached to unit
Attempted to change ammo type of non-ammo
Attempted to change ammo type of non-ammo
Attempted to change ammo type of non-ammo
There was an error with the following: Unit#9bf9d29c-c45a-4103-a258-c3a94e07d3c1, Fa Shih Battle Armor [LRR]
   Error caused by: Part#123212, Light Recoilless Rifle
There was an error with the following: Unit#9bf9d29c-c45a-4103-a258-c3a94e07d3c1, Fa Shih Battle Armor [LRR]
   Error caused by: Part#123193, Fa Shih Battle Armor [LRR] Suit
There was an error with the following: Unit#9bf9d29c-c45a-4103-a258-c3a94e07d3c1, Fa Shih Battle Armor [LRR]
   Error caused by: Part#123174, Fa Shih Battle Armor [LRR] Suit
There was an error with the following: Unit#9bf9d29c-c45a-4103-a258-c3a94e07d3c1, Fa Shih Battle Armor [LRR]
   Error caused by: Part#123155, Fa Shih Battle Armor [LRR] Suit
There was an error with the following: Unit#9bf9d29c-c45a-4103-a258-c3a94e07d3c1, Fa Shih Battle Armor [LRR]
   Error caused by: Part#123136, Fa Shih Battle Armor [LRR] Suit
Trooper location -1 found on BattleArmorSuit attached to unit
Trooper location -1 found on BattleArmorSuit attached to unit
Trooper location -1 found on BattleArmorSuit attached to unit
Trooper location -1 found on BattleArmorSuit attached to unit
There was an error with the following: Unit#c4e67181-45e2-40a7-b0fb-9d40e079ae8f, Cavalier Battle Armor [Flamer] #2
   Error caused by: Part#123059, Flamer
There was an error with the following: Unit#c4e67181-45e2-40a7-b0fb-9d40e079ae8f, Cavalier Battle Armor [Flamer] #2
   Error caused by: Part#123051, Cavalier Battle Armor [Flamer] Suit
There was an error with the following: Unit#c4e67181-45e2-40a7-b0fb-9d40e079ae8f, Cavalier Battle Armor [Flamer] #2
   Error caused by: Part#123043, Cavalier Battle Armor [Flamer] Suit
There was an error with the following: Unit#c4e67181-45e2-40a7-b0fb-9d40e079ae8f, Cavalier Battle Armor [Flamer] #2
   Error caused by: Part#123035, Cavalier Battle Armor [Flamer] Suit
There was an error with the following: Unit#c4e67181-45e2-40a7-b0fb-9d40e079ae8f, Cavalier Battle Armor [Flamer] #2
   Error caused by: Part#123027, Cavalier Battle Armor [Flamer] Suit
Trooper location -1 found on BattleArmorSuit attached to unit
Trooper location -1 found on BattleArmorSuit attached to unit
Trooper location -1 found on BattleArmorSuit attached to unit
Trooper location -1 found on BattleArmorSuit attached to unit
Attempted to change ammo type of non-ammo
Attempted to change ammo type of non-ammo
Attempted to change ammo type of non-ammo
Attempted to change ammo type of non-ammo
Attempted to change ammo type of non-ammo
Attempted to change ammo type of non-ammo
Attempted to change ammo type of non-ammo
Attempted to change ammo type of non-ammo
Attempted to change ammo type of non-ammo
There was an error with the following: Unit#85eea6ed-f93f-4507-ba85-f4f0d2b94530, Fa Shih Battle Armor (Support) [Plasma]
   Error caused by: Part#123257, Basic Manipulator
There was an error with the following: Unit#85eea6ed-f93f-4507-ba85-f4f0d2b94530, Fa Shih Battle Armor (Support) [Plasma]
   Error caused by: Part#123256, Basic Manipulator
There was an error with the following: Unit#85eea6ed-f93f-4507-ba85-f4f0d2b94530, Fa Shih Battle Armor (Support) [Plasma]
   Error caused by: Part#123252, Plasma Rifle
There was an error with the following: Unit#85eea6ed-f93f-4507-ba85-f4f0d2b94530, Fa Shih Battle Armor (Support) [Plasma]
   Error caused by: Part#123243, Fa Shih Battle Armor (Support) [Plasma] Suit
There was an error with the following: Unit#85eea6ed-f93f-4507-ba85-f4f0d2b94530, Fa Shih Battle Armor (Support) [Plasma]
   Error caused by: Part#123234, Fa Shih Battle Armor (Support) [Plasma] Suit
There was an error with the following: Unit#85eea6ed-f93f-4507-ba85-f4f0d2b94530, Fa Shih Battle Armor (Support) [Plasma]
   Error caused by: Part#123225, Fa Shih Battle Armor (Support) [Plasma] Suit
There was an error with the following: Unit#85eea6ed-f93f-4507-ba85-f4f0d2b94530, Fa Shih Battle Armor (Support) [Plasma]
   Error caused by: Part#123216, Fa Shih Battle Armor (Support) [Plasma] Suit
Trooper location -1 found on BattleArmorSuit attached to unit
Trooper location -1 found on BattleArmorSuit attached to unit
Trooper location -1 found on BattleArmorSuit attached to unit
Trooper location -1 found on BattleArmorSuit attached to unit`

**Comment by Dylan-M** [comment]
"Fixed" cpnx attached. To fix it, I simply used my dev version with some extra code to load the file successfully, GM remove the offending units, and then save again. I also added 1 of ever type of Cavalier and Fa Shih battle armor, and they work fine. Just keep in mind, BA aren't fully supported! They break things! Don't refit BA! Use MML to make the new Model, and then GM Remove the old ones/GM Add the new ones.

[Regal Force30770228.txt](https://github.com/MegaMek/mekhq/files/753454/Regal.Force30770228.txt)

**Comment by Dylan-M** [comment]
NOTE FOR DEVS: To bypass the loading error and allow the file to load, in Unit.java I added a try/catch inside `initializeParts(boolean addParts)'s` first `for(Part part : parts) {`

The catch for it just looks like this:
`catch (Exception ex) {
            System.out.println("There was an error with the following: Unit #"+this.getId()+", "+this.getName());
            System.out.println("   Error caused by: Part #"+part.getId()+", "+part.getName());
        }`

That makes it work, but is not a proper way to handle it.

**Comment by Shenaldrac** [comment]
Thank you VERY much! You don't know how much it means to me for you to have gone through this trouble for me. I'll be sure to be careful with BA from now on.

**Comment by Dylan-M** [comment]
No problem! It'd be nice to get BA fully working, but I don't think it's a priority for anyone.

**Comment by Shenaldrac** [comment]
Yeah, makes sense. Most people play BT for the mechs, after all.

**Comment by honehe** [comment]
re: my issue: i don't have BA, but i do have mech under refit. I can include savegeame later if you want ( or shall i log new issue?)

**Comment by VampireSeraphin** [comment]
Just got a report from my GM this this recurs in the new release.

**Comment by neoancient** [comment]
Was the refit attempted in the current version or is it an older campaign file that won't load in the new version?
