### ISSUE TITLE
[0.49.8-711] TO&E -- transparency issue

### ISSUE THREAD

**Issue by kernhe** [MegaMek/mekhq#3193]
### Environment
V: 0.49.8-711
O: linux x86_64 GNU/Linux
J: openjdk 11.0.14 2022-01-18

### Description
The screenshot shows on the left 0.49.8-711 and on the right 0.49.8-692. On the left you can see that the strings have a white background and not a transparent. 
This issue is present in all themes that do not have a white background color in the windows (also valid issue for all dark themes provided by mhq)

### Files
![Screenshot](https://user-images.githubusercontent.com/1056746/160291555-5ae793c7-c8c4-4fdb-b233-85a04df63e88.png)

**Comment by Windchild292** [comment]
This is due to a bug with the Nimbus theme, namely:
https://bugs.openjdk.java.net/browse/JDK-8041701
https://bugs.openjdk.java.net/browse/JDK-8249674
https://bugs.openjdk.java.net/browse/JDK-8271315
Closing as a JDK bug.

**Comment by kernhe** [comment]
It was affecting all themes (cde/motif, ... dark, etc). But I just restarted the game and it is gone.

I hate nondeterminism in software.

**Comment by Windchild292** [comment]
Select anything Nimbus and it will hold until a restart. Otherwise, it will not occur based on my testing and the above report.

Java 17.0.2 fixes this, but we can't support that version until Gradle builds are fixed, much less until we handle our many modernization issues.

I'm working on making this possible, but we've still got a ton of work left including huge rewrites..
