### ISSUE TITLE
Enemy pilot missing from the post match assign-kill screen if their mech falls over and destroys it's own head

### ISSUE THREAD

**Issue by Tamren** [MegaMek/mekhq#327]
MekHQ v42.0

This may be difficult to reproduce because it's so random. But basically an enemy mech got shot in the face by a medium laser and 1 SRM missile. This did a total of 7 damage to the HD location, he then fell over because he took +20 damage in that round and hit his head location for 5 falling damage which killed the pilot and destroyed the mech. When the match was over the pilot and the mech did not appear on the kill assignment screen. Evidently this counts as an accidental "environmental" death despite weapon fire being the reason the mech fell over in the first place.

**Comment by wildj79** [comment]
This is actually similar to this issue: [SourceForge #4360](https://sourceforge.net/p/megamek/bugs/4360/)

I want to say this is more of an issue with how MegaMek currently assigns kills instead of an issue with how MekHQ handles after action reports.  But, I'm not overly familiar with the MekHQ code base and could be completely wrong on this issue.

**Comment by pheonixstorm** [comment]
No, this is an issue in MM. This isn't the only case of MM not properly accounting for kills, even accidental ones.

This is one of those oddities in MM just like how sometimes you can't capture a pilot because for whatever reason he doesn't show up in the pilot list. This especially when you actively pick up an enemy pilot.

**Comment by neoancient** [comment]
This is not a MekHQ issue. It is related to MegaMek/megamek#417.
