### ISSUE TITLE
OpFor units are not loading in 0.48.0

### ISSUE THREAD

**Issue by Robonut61969** [MegaMek/mekhq#3452]
### Environment
What version of MekHQ does your issue apply to?  0.48.0
What operating system are you using?  Windows 10
What java version are you using?  Ver 8 update 341

### Description
When starting a new scenario. Only the player units are loading.
The OpFor bots load are on different teams, have start as "any" and have no units 

### Files

![Untitled](https://user-images.githubusercontent.com/113164884/189286361-b84f3ac9-70a9-45da-8653-636b424138fe.png)
[Dark Shadow30200211.cpnx.gz](https://github.com/MegaMek/mekhq/files/9532882/Dark.Shadow30200211.cpnx.gz)
[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/9532884/mekhqlog.txt)
[megameklog.txt](https://github.com/MegaMek/mekhq/files/9532893/megameklog.txt)

**Comment by Windchild292** [comment]
I'd recommend assigning more RAM to MHQ, as the issue is that the units are being sent too quickly for them to be initialized.

Changes since this point have resolved this issue, as there is now an options setup where the delays can be modified. Further, the entire region of code has been rewritten.
