### ISSUE TITLE
[RFE] Stratcon - Create an extra "Mission Complete" option, equivalent to a Draw

### ISSUE THREAD

**Issue by JonhyBurner** [MegaMek/mekhq#3478]
With Stratcon objective-based game play, it is entirely possible to fail some of the contract objectives - and therefore the mission - while also managing to finish some of them.

That means that the current mission ending dialogue, with only Success, Failed and Contract Breach, is missing a more neutral solution.

Something like "Unsuccessful", "Draw", "Missed Objectives", could fill that gap.

**Comment by pheonixstorm** [comment]
Under Campaign Operations it lists, Success, partial success, failed, and breach.

Success 5pts
Partial Success ?
Failed -10pts
Breach -25pts

Per CO pg47 "A partial failure does not affect Reputation". Never noticed this until now since it isn't with the rest of the text for a partial success/failure. It shouldn't be hard to add a partial success and the 0 pts awarded for the contract.

For now you can add a rating modifier in the HQ settings, general tab iirc. The one where you set the rating system and date.

**Comment by pheonixstorm** [comment]
I have a PR up for this one, just waiting for someone to look it over and approve it.
