### ISSUE TITLE
Offensive name in random callsign list

### ISSUE THREAD

**Issue by dewardthesteward** [MegaMek/mekhq#3854]
Hey just quickly popped in to make a tiny little request: could you please remove w* nd* go from the list of random potential callsigns in later versions, if you have not already done so? Attached is context, truth be told, it honestly was really unpleasant for me to find, and I'd highly prefer to not be jumpscared by it again.

MOD NOTE
Removing the social media link per our internal policies

**Comment by pheonixstorm** [comment]
What exactly is offensive about it and what does the twitter post have to do about it.  As far as I can tell there is nothing in the twitter post that even vaguely explains anything.

**Comment by dewardthesteward** [comment]
In particular, what’s offensive about it, per the thread itself which is explicitly about the w* nd *go, that it is in direct violation of a specific taboo held by multiple Algonquin tribes, and its repeated presence is a form of cultural appropriation. That twitter post is entirely about why using w* nd * go is offensive, it just doesn’t refer to it by name because the person writing the thread believes it would break the taboo to do so.I do not ask for much. Please try and take this into account.Sincerely,EduardoOn Feb 24, 2024, at 5:12 AM, pheonixstorm ***@***.***> wrote:﻿
What exactly is offensive about it and what does the twitter post have to do about it.  As far as I can tell there is nothing in the twitter post that even vaguely explains anything.

**Comment by dewardthesteward** [comment]
@HammerGS does that thumbs down mean that you are ignoring this in it's entirety? What is so difficult about simply removing a single random name from the callsign list, why does my request cause you so much trouble? Why do I need to provide constant proof to have one less-than-miniscule thing changed? It's not like I'm asking to have the game remade or anything, I've already been constantly condescended to by being forced to provide academic proof. Why is this so much trouble?

**Comment by dewardthesteward** [comment]
[A+Creature+Without+a+Cave.pdf](https://github.com/MegaMek/mekhq/files/14438739/A%2BCreature%2BWithout%2Ba%2BCave.pdf)
Here is an academic article showing how it's usage is offensive. Please take this into account, I do not understand why this is considered such an issue.

**Comment by maikilangiolo** [comment]
You can freely remove all the names you consider problematic from your own MM download

**Comment by dewardthesteward** [comment]
> You can freely remove all the names you consider problematic from your own MM download

I'll do that, but I just wanted to bring this to your attention, and am bluntly straight up insulted at how much disrespect and bad faith I have been subject to for a simple and easy request. A major moderator literally told me to provide an ACADEMIC SOURCE for this claim, because clearly if you want to say that you find something offensive or problematic, you need a fucking JSTOR source to back it up, and then immediately shut down the conversation when I tried to give a five paragraph explanation on my own. It's bluntly, extremely shitty how much hay was made with me for such a small request.

Anyways, how do I do that myself?

**Comment by Sleet01** [comment]
> > You can freely remove all the names you consider problematic from your own MM download
> 
> Anyways, how do I do that myself?

You can edit this file to remove just the the callsign:
```
<MegaMek install dir>/data/names/callsigns.csv
```

To completely expunge mentions of the offending term from MegaMek, you'll need to:
1. Edit the callsigns file as above,
2. Remove all lines containing the term from `<MegaMek install dir>/data/forcegenerator/*.xml`,
3. Remove all lines containing the term from `<MegaMek install dir>/data/rat/*.txt`,
4. Delete all files whose names contain the term,

which should prevent MegaMek from selecting or displaying any of these instances.  For MML and MekHQ you would use a similar approach, but this depends on how you have installed the apps (piecemeal or using the combined package).

BTW I've been observing your behavior, and the only person displaying rudeness here is you.  Please try to restrain yourself while demanding favors from volunteers on the project.

**Comment by dewardthesteward** [comment]
> > > You can freely remove all the names you consider problematic from your own MM download
> > 
> > 
> > Anyways, how do I do that myself?
> 
> You can edit this file to remove just the the callsign:
> 
> ```
> <MegaMek install dir>/data/names/callsigns.csv
> ```
> 
> To completely expunge mentions of the offending term from MegaMek, you'll need to:
> 
> 1. Edit the callsigns file as above,
> 2. Remove all lines containing the term from `<MegaMek install dir>/data/forcegenerator/*.xml`,
> 3. Remove all lines containing the term from `<MegaMek install dir>/data/rat/*.txt`,
> 4. Delete all files whose names contain the term,
> 
> which should prevent MegaMek from selecting or displaying any of these instances. For MML and MekHQ you would use a similar approach, but this depends on how you have installed the apps (piecemeal or using the combined package).
> 
> BTW I've been observing your behavior, and the only person displaying rudeness here is you. Please try to restrain yourself while demanding favors from volunteers on the project.

I understand, and thank you for giving me the instructions, but what I'm referring to is a particular incident in which a moderator in the discord explicitly told me to provide an academic source for saying that this certain thing is offensive in use, and then immediately shutting me down when I explained that I wasn't going to be able to give him one, gave him a literal online article, and then wrote a five paragraph post explaining what was offensive here. I'm sorry if I've been demanding, but it's because one of you demanded that I give the burden of literal academic proof, for something that literally boils down to editing a single CSV file on your end. It felt really backhanded and condescending, and like so much was being made over so little.

**Comment by dewardthesteward** [comment]
I would have honestly been... well, fine is the wrong word, but if you had just ignored me or it hadn't gone anywhere, that would have made sense. But no: to definitively prove that this one text in this one CSV file is offensive, I needed to provide an academic source and if you don't we're no longer listening to you. It's ridiculous!

I get that I'm being aggressive here but like, how else am I supposed to react? I was being asked to provide literal paperwork to prove that this one line of text in a csv file should be changed.

**Comment by HammerGS** [comment]
@dewardthesteward Lets start by making one things CRYSTAL clear, I DID NOT thumb down that was Thom293.

We are a project that is 100% managed by volunteers who do this for the love of the game, and love of universe. You as a player are entitled to open bug reports and RFE's. But as a dev team we decided what, and WHEN we'll handle the issues. 

Next, you are fully entitled to your beliefs as I am entitled to mine and as everyone in our community is.  So, what happens when we agree to your "demand" and remove it. What happens to the player that uses that name and loves it (as is their right). How about the potential broken campaign that becomes a bug report, which in turn takes development time away from a volunteer to address. 

You came into our Discord, demanded we do something - again your right as is ours to do nothing. You are a user of our product and entitled to use or not use what is provided.  When you didn't get an answer that YOU approved of, and when Tex asked for a scientific reason for why this needed to happen, you responded with ignorant comments and extremely foul language that violated the rules of OUR Discord with multiple posts Auto-Modded. You proceeded to argue and ignore Mod directives and were banned.
 
You then waited 4 days, to again resume the demands here.

> @HammerGS does that thumbs down mean that you are ignoring this in it's entirety? What is so difficult about simply removing a single random name from the callsign list, why does my request cause you so much trouble? Why do I need to provide constant proof to have one less-than-miniscule thing changed? It's not like I'm asking to have the game remade or anything . Why is this so much trouble?

Did it occur to you I might be busy with my real life, real job, and I VOLUNTEER to do this. 

This was not me who posted.

> What exactly is offensive about it and what does the twitter post have to do about it. As far as I can tell there is nothing in the twitter post that even vaguely explains anything.

This is what is going to happen.  We will NOT be removing the call sign. You have been provided a workaround by Sleet01. It is your right to continue to use our software, but you'll need to do the workaround for every release.

This thread will be closed, and no further comment will be allowed. I would recommend you reflect on your toned and approach, as it is not welcome here.  One final thought for you in your own words _"one less-than-miniscule thing changed"_
