### ISSUE TITLE
[49.19 Nightly] ASF units are not being tracked correctly by MHQ/StratCon

### ISSUE THREAD

**Issue by Thom293** [MegaMek/mekhq#3882]
Title.  I have a wing of 2 ASF in my TOE.  They dont show in the unit rating, and dont appear as options on the SC map to deploy or reinforce with.  (They DO show up in the transport capacity report, however).  I assume somehow related to recent ASF changes.

May be related to #3861 

Screens are Unit Rating, Transport Capacity, and SC map showing they dont show up as deployable from SC map (can deploy them from TOE though).

![image](https://github.com/MegaMek/mekhq/assets/23645569/56fd8b0f-0c4e-43d7-8a73-f8bb1aa01fe0)
![image](https://github.com/MegaMek/mekhq/assets/23645569/b106b57f-438d-4a8e-ab2d-54cd0439cf43)
![image](https://github.com/MegaMek/mekhq/assets/23645569/673dd533-cd0c-4d26-976d-1f4d826e7119)

[Crazed Profanity30690705.cpnx.gz](https://github.com/MegaMek/mekhq/files/14609621/Crazed.Profanity30690705.cpnx.gz)

[Customs.zip](https://github.com/MegaMek/mekhq/files/14609641/Customs.zip)

**Comment by Thom293** [comment]
Ok.  So advanced a few weeks and my ASF "Arc Wing" got pulled as a seed lance for a ground battle.  So I guess it somehow sees them as a ground unit?  Not sure.  Just another datapoint.  

![image](https://github.com/MegaMek/mekhq/assets/23645569/33a12ca9-ca93-4ab9-8058-13cc941c9af2)
[Crazed Profanity30690719.cpnx.gz](https://github.com/MegaMek/mekhq/files/14610138/Crazed.Profanity30690719.cpnx.gz)

**Comment by robgrahamau** [comment]
Have the same happening in 49.18, something I noticed though is that it doesn't seem to be recognizing the Aerospace units as being able to be assigned to transport either:

![image](https://github.com/MegaMek/mekhq/assets/28775608/978d1b35-d6c8-48bf-8dd5-b12a2987d8af)

There is more than enough aerospace carriage in this unit (it has multiple overlords plus a Riga II (SLDF campaign) but I can't assign any of them and when you look at the TO&E summary like above 

Fighter Bays:                0 needed /  50 available (plus 9 excess Small Craft)

Yet if you look at Transport Capacity Report.. 

![image](https://github.com/MegaMek/mekhq/assets/28775608/80069b81-ea38-4bc6-9afe-9a059ee92c6d)

It shows 24 Occupied of the 50 available.

**Comment by Sleet01** [comment]
@robgrahamau  I believe the ASF transport assignment issue you are seeing has already been solved in 0.49.19-dev.  If you have a chance, please see about downloading a recent Nightly build and checking that (you can get assistance on the Discord if necessary).

@Thom293 I have a fix for the report issue, but it looks like the RAT / ASF misallocation issue is rooted in MM code rather than MHQ.  That will require a separate fix in the MM codebase, which should be up soon as well.  There was also an issue with random unit generation for ASF; that will also be fixed.

Regarding deploying the ASF from the StratCon map, I was unable to make that work but perhaps I don't know the right preconditions.  I was able to add the Arc Wing contingent to missions via the TOE, as you reported.

**Comment by Sleet01** [comment]
There may also be an issue derived from these problems where AeroSpaceFighter units are listed under salary expenses rather than upkeep / maintenance; I'll see if I can repro that.
