### ISSUE TITLE
RFE - New hired mechwarriors 'personality'?

### ISSUE THREAD

**Issue by molemanBT** [MegaMek/mekhq#3913]
More of a feature idea.

Would it be possible to set up a 'character generator' system for new characters/hires?

I currently do this manually, using the character generator sheet in my Noble ruleset Excel doc, and it generates a bunch of characteristics which I cut and paste, and manually apply to each new mechwarrior, these characteristics are pasted at the end of this RFE, they are just suggestions. Myself and Battleclad created a backend which has random number selections of up to 100 possible permutations for some of the characteristics, may make a decent starting point.

Starting/Preferred   Mech Class:
--
Bonus:
Special Ability 1:
Special Ability 2:
Background:
Wealth:
Confidence:
Likeability:
IQ:
Married:

**Comment by Thom293** [comment]
I love this for fluff only reasons.  It's possible to generate very good random backstories this way with enough Nested lists/options.

But aside from the fluff - are there any rules related to any of these so they have a gameplay effect?  Because that would be cool too. 

More random stuff like marriages and random death will add to making campaigns more "alive."

**Comment by IllianiCBT** [comment]
See also #3939

**Comment by IllianiCBT** [comment]
This is mostly resolved by #4446 so I'm going to go ahead and close it. The remaining features will be resolved by the upcoming backgrounds module.
