### ISSUE TITLE
RFE (atb) reflection of assigned roles to units in briefing room...

### ISSUE THREAD

**Issue by purpledragon2** [MegaMek/mekhq#398]
It seems to me that regardless of the role a unit in the briefing room is assigned, they all get the same percentage of a random encounter of any given type.  

I would like to see some weight put to the type of role the unit is assigned; e.g. more recon missions for units assigned to scout, but with the possiblities of other mission types still happening.  

More weight put towards base defense and hold the line for units set to defend but may still get that "go scout this" mission.

**Comment by kipstafoo** [comment]
The code actually does do this. If you're java-ly inclined, you can look at mekhq.campaign.force.Lance.java -> checkForBattle()

Based upon the role, different fights are more or less likely to happen.

Now, does it do it well/right? That's bringing in a bit of subjectiveness. :) But it does do it.

**Comment by purpledragon2** [comment]
Okay, so then maybe the weight needs to be adjusted?  I have not ever gotten a scout mission for my recon units when they get assigned that role.  Units in training, more often than not, are the ones involved in battles.  

I'm not saying its broke; just that it doesn't seem, from the results I've seen, to have the weights set more for role assignment.

**Comment by NickAragua** [comment]
Looking at the AtB rules, a Scout lance has a 10% chance of drawing each of: Chase (Attacker), Hide and Seek (Defender), Probe (Attacker), Probe (Defender), Extraction (Attacker) and Recon Raid (Attacker).  And 0% chance of drawing any of the other fights, except Base Attack (Defender) in certain low-morale situations.  These odds are modified somewhat by low or high enemy morale, however, you should never get scenarios other than the ones listed above. Here are what other lance assignments should be able to get for battles:

Fight: Breakthrough (Attacker), Standup (Both), Chase (Defender), Hold the Line (Defender), Base Attack (Attacker)
Defend: Hold the Line (Defender), Recon Raid (Defender), Extraction (Defender), Hide and Seek (Attacker), Breakthrough (Defender) 
Training: Hold the Line (Defender), Breakthrough (Attacker), Chase (Both), Hide and Seek (Defender)

Note that Base Attack (Defender) will happen every week to a randomly selected lance regardless of orders if enemy morale hits invincible. I had one game where this went on for about two months before the contract mercifully ended. 

Looking at the code, I did find that scout lances will never get Probe (Defender) missions, getting Probe (Attacker) missions instead. Not that it matters much since the objectives are identical on both ends. 
I'll be making that change soonish, once I get some source control issues sorted out. Otherwise, as Kipstafoo mentioned, the scenario likelyhood weights conform to AtB rules as far as I can tell.

If you (or anyone else) could provide a saved game where a scout lance has drawn something other than one of those scenarios (or any other saved game where a lance has gotten an inappropriate scenario), that'll help determine if there are any other issues with random scenario generation.
