### ISSUE TITLE
MHQ wont save, sometimes

### ISSUE THREAD

**Issue by Thom293** [MegaMek/mekhq#3986]
Discussed in Discord.  WARNING.  Was testing some units for someone.  Im posting this with those, because I didnt want to lose my stuff, but after posting this I will delete those and test again to make sure its not related to them.

This save is on a Sunday.  Advancing day will get you a base attack mission because they are on invincible morale.  Sometimes, you can save after that. Sometimes, you cannot.  

EDIT:  You can ignore the turret file below as it seems unrelated. 

![image](https://github.com/MegaMek/mekhq/assets/23645569/f3cf5f93-3b7d-46ca-ba9d-777b85d954d4)

[Crazed Profanity30700206.cpnx.gz](https://github.com/MegaMek/mekhq/files/14913562/Crazed.Profanity30700206.cpnx.gz)

[mekhq.log](https://github.com/MegaMek/mekhq/files/14913571/mekhq.log)

[Customs.zip](https://github.com/MegaMek/mekhq/files/14913580/Customs.zip)

[Turret_Updates_Alpha_V0.1.3.2_3067_Bugfix.zip](https://github.com/MegaMek/mekhq/files/14913622/Turret_Updates_Alpha_V0.1.3.2_3067_Bugfix.zip)

**Comment by Thom293** [comment]
Did it again even with those turrets deleted, from same save as posted before.  

![image](https://github.com/MegaMek/mekhq/assets/23645569/db4d95e6-5e1b-4ef8-9ded-9adc3dc9b08f)

Here is the unit list for the only pending scenario, if it matters.
![image](https://github.com/MegaMek/mekhq/assets/23645569/431ec59a-c470-4b2a-9bdd-e4c7aec4f57f)

and the log.  
[mekhq.log](https://github.com/MegaMek/mekhq/files/14913699/mekhq.log)

**Comment by Thom293** [comment]
Another log, just in case.

[mekhq.log](https://github.com/MegaMek/mekhq/files/14913768/mekhq.log)

**Comment by AaronGullickson** [comment]
Problem is here:

```java
java.lang.NullPointerException: Cannot invoke "String.length()" because "s" is null
	at java.base/java.io.PrintWriter.write(PrintWriter.java:558)
	at megamek.common.EntityListFile.writeEntityList(EntityListFile.java:757)
	at mekhq.campaign.mission.BotForce.writeToXML(BotForce.java:329)
        at mekhq.campaign.mission.Scenario.writeToXMLBegin(Scenario.java:784)
	at mekhq.campaign.mission.Scenario.writeToXML(Scenario.java:755)
	at mekhq.campaign.mission.Mission.writeToXMLBegin(Mission.java:220)
	at mekhq.campaign.mission.Contract.writeToXMLBegin(Contract.java:661)
	at mekhq.campaign.mission.AtBContract.writeToXMLBegin(AtBContract.java:770)
	at mekhq.campaign.mission.Mission.writeToXML(Mission.java:202)
	at mekhq.campaign.Campaign.writeToXML(Campaign.java:4154)

```

This is happening when trying to write an entity from a BotForce.

That line of EntityListFile is:

```java
output.write(entity.getC3UUIDAsString());
```

Which is part of a larger if statement:

```java
if (entity.hasC3() || entity.hasC3i() || entity.hasNavalC3()) {
    output.write("\" " + MULParser.ATTR_C3UUID + "=\"");
     output.write(entity.getC3UUIDAsString());
}
```

So the entity is returning a NULL value for the C3UUID string.

This seems to be clearly related to the switch from using `MHQXMLUtility.writeEntitytoXmlString()` to write BotForce entities, but I am a bit confused because this is how it is written out in that method:

```java
if (tgtEnt.hasC3() || tgtEnt.hasC3i() || tgtEnt.hasNavalC3()) {
    retVal.append("\" " + MULParser.ATTR_C3UUID + "=\"").append(tgtEnt.getC3UUIDAsString());
}
```

I don't see any meaningful difference between the two methods. 

I am guessing the reason that this is happening only sometimes is that not all entities are triggering it. So whether you get a problem or not depends whether the randomization of the OpFor produces certain units.

**Comment by AaronGullickson** [comment]
So, there are two different entity writers in MHQXMLUtility. `writeEntityWithCrewXML` and `writeEntityToXmlString`. The `writeEntitywithCrewXML` is what was used to write all BotForces and it doesn't break on the C3 issue because ... it doesn't write it. It is also missing a TON of other stuff. Both of these entity writers are used at different places in the MHQ code as well. What an absolute nightmare. 

I think this just shows how desperately we need to consolidate entity XML writing and reading. However, that should all be a post 39.19 goal as it will require some significant reworking and likely breaking. The short term solution will be just to check the null condition on the offending variable before writing in EntityListFile. While I am at it, I will check for other potential offenders.
