### ISSUE TITLE
Change of VP terminology

### ISSUE THREAD

**Issue by molemanBT** [MegaMek/mekhq#4043]
Sorry for reopening an old issue, I'm just not sure that operational VP is solving a problem with confusion? As a non military man, an operation seems like a long running thing, I think battle VP or scenario VP (in keeping with the terminology used within MHQ, although I never remember which is a mission and which is a scenario (and thus would prefer BVP)) would be much less confusing?

**Comment by PhoenixHeart512** [comment]
Personally I'm in favor of using "Scenario VP" so that it matches exactly with the terminology MekHQ uses for scenarios. Battle VP would also be unambigous, but I am a fan of consistency, so my vote is for "Scenario VP" instead of "operational VP" since "operation" is not used anywhere else in MekHQ at this time
