### ISSUE TITLE
MegaMek fails to load dropship sent from MekHQ

### ISSUE THREAD

**Issue by BlueThing00** [MegaMek/mekhq#4085]
### Environment
49.19.1 (campaign started and bug first seen on 49.19)
Windows 10
Java Version: 11.0.16

### Description
I'm playing a Stratcon campaign.

A "Defend Grounded Dropship - Heavy" mission was generated.  It pulled a dropship from my OOB to defend, but that dropship fails to load in MM.  

To make sure that there isn't a problem with my custom dropship, I tried loading it in a standalone MM, and it loads fine.  

I also tried adding in a vanilla Union dropship and using it instead, but the same error occurs.

When I add the same dropships to the MM spawned by MekHQ manually, they load without a problem.

Steps to replicate:
Briefing Room > Pending Mission (Defend Grounded Dropship - Heavy)
Start Game
Wait for the error in loading the dropship (see below).

![image](https://github.com/MegaMek/mekhq/assets/21363819/70c29ace-8d5e-4434-af56-2b5279013ac2)

### Files

[mekhq.log](https://github.com/MegaMek/mekhq/files/15326522/mekhq.log)
[megamek.log](https://github.com/MegaMek/mekhq/files/15326526/megamek.log)
[Bluethings30250921_dropship_bug.cpnx.gz](https://github.com/MegaMek/mekhq/files/15326558/Bluethings30250921_dropship_bug.cpnx.gz)
[Meks.zip](https://github.com/MegaMek/mekhq/files/15326570/Meks.zip)

**Comment by Thom293** [comment]
Perhaps related. 

https://github.com/MegaMek/megamek/issues/5356

**Comment by BlueThing00** [comment]
I saw the same thing happen with a mission generated in 49.19.1.  I was again able to play it by removing my dropship and defending the employer's.

This appears to be an active bug in the milestone release.

**Comment by BlueThing00** [comment]
I'm still seeing this with a new campaign created and played exclusively in 0.50.0.

**Comment by eventsbeyondme** [comment]
If you export the .mul from MekHQ, then delete your force in MM and reload from the .mul, it loads correctly most of the time.
I have noticed on a few instances that the Ammo bins are not aligned correctly in the .mul, when that is the case it fails to laod the dropship.

ex: AC/5 Ammo on the Union totalling to the correct amount, but the individual bins having different amounts like 28 and 12 instead of 20 and 20
next time that this happens I'll capture the .muls
