### ISSUE TITLE
C3i creating large illegal networks in MekHQ and generating huge BV values for lances.

### ISSUE THREAD

**Issue by Daishi-5** [MegaMek/mekhq#4103]
What version of MekHQ does your issue apply to?
49.19
What operating system are you using? Windows, Mac, or Linux?
Windows

What java version are you using? If unsure it will state your java version at the top of the mekhq.log file.
Java Vendor: Eclipse Adoptium
Java Version: 11.0.16.1

I am seeing weird behavior with c3i in my lances.  

1.  I cannot join c3i units to networks unless they are already in a network.  The option is not available.  In these screenshots, the first mech is listed in a network and has network options, the second mech is not in a network and has no network options.
![image](https://github.com/MegaMek/mekhq/assets/168131032/964001d2-74d1-4ab9-8eba-ce990c6f8c41)
![image](https://github.com/MegaMek/mekhq/assets/168131032/689b91aa-2fdf-46bb-969a-bc82abb07fe3)

2.  Mechs seem to be joining networks on their own somehow.  In this screenshot, this is a recently rebuilt force, I customized almost all of these mechs at a planet recently, and most of them have never been in a fight with their c3i equipped. You can see most of them are in a network number 5, a few are not in a network, and there are a few other networks listed. 
![image](https://github.com/MegaMek/mekhq/assets/168131032/a83c3704-0073-4a06-a792-1c73e017bcc1)

3. The networks seem to be creating a lot of lag in the mekhq interface while these networks exist.  I am experiencing delays until I remove all the mechs from their networks.

4. When I got to deploy lances, I am getting ridiculous BV levels for my lances, and I am guessing they are coming from so many of my mechs being part of a giant illegal c3i network.  

- In the screenshot Archer lance has 46K BV, when looking at the above shot from the TO&E, that lance has 9.5k BV.  All of archer is in the c3i.5 network.  
- The Atlas command lance is all clan mechs, its BV in the screenshot is 16k which matches its BV from the TO&E.  
- The screenshot shows Awesome lance having a BV of 25K, but in the TO&E that lance has 8500 BV.  Awesome lance has 2 mechs in the C3i.5 network, and two not connected.   
- It seems that each mech connected to the network in a lance is giving the lance between 8.25K - 9.5K BV on the stratcon tab.

![image](https://github.com/MegaMek/mekhq/assets/168131032/f800d244-497b-4e62-b514-ded36c86cb21)

### Files
[customs.zip](https://github.com/MegaMek/mekhq/files/15421518/customs.zip)
[Bugged-c3i.cpnx.gz](https://github.com/MegaMek/mekhq/files/15421537/Bugged-c3i.cpnx.gz)

**Comment by NickAragua** [comment]
The ridiculous BVs and performance issues are due to the fact that you've somehow got 78 units in the "c3i.5" network. When calculating BV, c3 networks add some percentage of the linked units' BV to the unit BV being calculated; 50% of 78 units is a lot of BV. My suggestion is to disband all networks (5 and 41 seem to be the "problem" networks) and then re-create. Unfortunately, it's almost impossible to figure out why they were created like this in the first place, as we lack a "before" state and steps to get to the "after" state. If you do stumble upon this behavior again and are able to provide a "before" state, that will allow the underlying cause to be addressed.

I've created a PR to address the inability to add a non-c3I-networked unit to a network (or create new network when selecting more than one non-networked unit).
