### ISSUE TITLE
43.3 - Longinus (WoB) not showing in Hanger

### ISSUE THREAD

**Issue by pjfarland** [MegaMek/mekhq#414]
The BA suit don't show and don't highlight correctly in the Hanger.  Other BA suits seem to be functional.

**Comment by HammerGS** [comment]
Do you have a campaign file you can upload here. Makes troubleshooting easier.

**Comment by pjfarland** [comment]
[49th Shadow Division30750101-22.zip](https://github.com/MegaMek/mekhq/files/1163835/49th.Shadow.Division30750101-22.zip)

There are some customs in, but not relevant.

**Comment by pjfarland** [comment]
I was working on it, lol

**Comment by HammerGS** [comment]
Need all the customs as well.

**Comment by pjfarland** [comment]
[_Customs.zip](https://github.com/MegaMek/mekhq/files/1166024/_Customs.zip)

**Comment by pjfarland** [comment]
It happens with a clean build and most likely is related to the issue with BA not loading in MM.

**Comment by HammerGS** [comment]
This is an issue, as a result of Sprites not making it into the repo for this release.

Fixed with - 
https://github.com/MegaMek/megamek/commit/7e23967340313bd5a7b9428b8c1c8d569e89feb0
https://github.com/MegaMek/megamek/commit/e96878f05899a8eacd03bca813decc14d3dcdab7
https://github.com/MegaMek/megamek/commit/0a8b17d0b530677fc1c9c5abc29223f308d314da
https://github.com/MegaMek/megamek/commit/0d2f1418666a963f1c0199c75e923f6913bddafc
https://github.com/MegaMek/megamek/commit/4dfcd7842e6d9eb9ee2496142822af00108079d3
https://github.com/MegaMek/megamek/commit/004cfbfdbf093cd158e7079c17bbc9173f12729a

I'm going to see if I can build replacement atlases and attach them here, but that won't till tomorrow at the earliest.

**Comment by HammerGS** [comment]
@pjfarland Try unzipping this Replacement images folder and copying the data folder over and over writing whats their and try loading your campaign.

[Replacement Images.zip](https://github.com/MegaMek/mekhq/files/1167729/Replacement.Images.zip)
