### ISSUE TITLE
[Nightly] Kills tracking broken

### ISSUE THREAD

**Issue by kernhe** [MegaMek/mekhq#4211]
# Environment

V: 0.49.20 Snapshot-8138370
O: linux (Ubuntu 20.04.4)
J: openjdk 11.0.23+9-1ubuntu1~20.04.2
Window Manager: Xfwm4 4.14
Desktop Environment: Xfce 4.14

# Description

Fluff information "kills" will be overwritten with the value of the last battle.

## Before
![before](https://github.com/MegaMek/mekhq/assets/1056746/fd6a66ef-c2b1-4c53-a1c9-dddfeb93848f)

## After
![after](https://github.com/MegaMek/mekhq/assets/1056746/5678b518-343b-4925-aa92-e5074a6f11d3)

(Edit: added screenshots)

**Comment by IllianiCBT** [comment]
Can you include your save and customs folder (if applicable) to aid testing?

**Comment by IllianiCBT** [comment]
[killTrackingBug.zip](https://github.com/user-attachments/files/15794569/killTrackingBug.zip)
Here is a save and customs folder from Thom that shows the issue.

**Comment by IllianiCBT** [comment]
This is proving to be a really hard bug to fix. I've found where in the code that the error is occurring, but I'm struggling to identify _why_ it's occurring.

The short version is that autoAwards is overwriting the list of kills for individual persons; however nothing in the code that I've spotted so far explains why that is happening. autoAwards only reads the kill list, it doesn't write to it. I've run out of dev time for today, but I'm going to try and figure this out tomorrow. If I can't figure it out, I might have to bat phone one of the senior Devs.

**Comment by kernhe** [comment]
@IllianiCBT thanks for stepping in with save and custom folder.

**Comment by IllianiCBT** [comment]
So, I've managed to resolve this issue, though I'm no less confused as to why it happened. The short version is that mhq was writing to a list with an identical name to the list I was writing to; however, by my reckoning, the original list of kills should have been out of scope (not able to be written to by autoAwards).

This proved difficult to track down, as the bug was occurring in two places: the handling of post-scenario kill awards (that one was obvious), and also the handling of the Medal of Honor award in misc awards (this was the less obvious case and why it took so long to track down the culprit).

The downside is that autoAwards was permanently deleting kill records, so the original kills are gone for good. The only way to recover them would be to reload a save prior to 49.20.

**Comment by kernhe** [comment]
I think you have to live with downsides when you want to use bleeding edge development releases. ... That's what testing is for and that's what I do.
