### ISSUE TITLE
49.20 Nightly - Most MW have disappeared.

### ISSUE THREAD

**Issue by Thom293** [MegaMek/mekhq#4235]
Title.  Picture of Roster from 6.9.24 Nightly:

![image](https://github.com/MegaMek/mekhq/assets/23645569/285f97fc-bf3d-4288-88bf-a78de7969dab)

Pic of Roster from Tonights Nightly, same save:

![image](https://github.com/MegaMek/mekhq/assets/23645569/e5135c79-9b11-42b9-92ef-483d0c55321e)

[Titanium Tide30700727.cpnx.gz](https://github.com/user-attachments/files/15880724/Titanium.Tide30700727.cpnx.gz)
[CustomsThom6.10.24b.zip](https://github.com/user-attachments/files/15880725/CustomsThom6.10.24b.zip)

**Comment by repligator** [comment]
This is a strange one. All the pilots are still in the save file (at least when I read it in a text editor). Captain Thom Campion is on line 1105. Everything suggests that he should be showing up, but he isn't. Do you have a save from before they disappeared?

**Comment by Thom293** [comment]
Any save all the way back to the beginning of the contract, they have disappeared.  Not as many, but still most. This is a save from the start of my contract:

![image](https://github.com/MegaMek/mekhq/assets/23645569/93d2aebb-0152-458d-86af-8ce626302d61)


The best way to check it is to load the save in the nightly from last week, (my version was from 6.9.24) and they are there.  But load exact same save on nightly from last night and they are gone.

**Comment by IllianiCBT** [comment]
This happens when personnel fail to load for whatever reason. In this case I suspect the refactoring of the education system is to blame. I’ll investigate momentarily

**Comment by IllianiCBT** [comment]
It was what I thought: mhq was stumbling when trying to load some of the personnel because they had a highest education listed. To fix, all I needed to do was do a replace all:

<eduHighestEducation>1</eduHighestEducation> becomes <eduHighestEducation>Early Childhood</eduHighestEducation>
<eduHighestEducation>2</eduHighestEducation> becomes <eduHighestEducation>High School</eduHighestEducation>
<eduHighestEducation>3</eduHighestEducation> becomes <eduHighestEducation>College</eduHighestEducation>
<eduHighestEducation>4</eduHighestEducation> becomes <eduHighestEducation>Post-Graduate</eduHighestEducation>
<eduHighestEducation>5</eduHighestEducation> becomes <eduHighestEducation>Doctorate</eduHighestEducation>

This is an issue that will only affect campaigns started in nightlies prior to the recent education refactoring, so I will not be adding automated handling at this time - as it'll only be relevant for a very small window of time.

Instead, if anyone else runs into this issue, just reply with your campaign save file (I don't need customs) and I'll send you a fixed version.

**Comment by Thom293** [comment]
So do I need to wait on a new nightly to use the fixed save?  Will it re-disappear them if I advance a day?

**Comment by IllianiCBT** [comment]
> So do I need to wait on a new nightly to use the fixed save? Will it re-disappear them if I advance a day?

Just use the save I sent you, with the latest nightly, and you'll be golden

**Comment by Thom293** [comment]
The fix save still loads with just 2 MWs.

**Comment by IllianiCBT** [comment]
The log shows that 'early childhood' wasn't being read as a valid education level. I'll have a fix pushed momentarily.
