### ISSUE TITLE
Oblique artilleryman SPA should have a pre requisite of at least regular in artillery?

### ISSUE THREAD

**Issue by molemanBT** [MegaMek/mekhq#4417]
as per title, currently has no pre requisites, which is weird for people who don;t artillery, and could lead to pointless SPA gain upon reg>vet experience gain

**Comment by gsparks3** [comment]
A specific Artillery skill prerequisite would likely cause issues for people who don't use the separate Artillery skill, which is an option. However, a prerequisite of at least Regular in Artillery _or_ any Gunnery skill would stop it from showing up so often on non-combat personnel. 

I'm not sure if it's possible to set it up so that Artillery skill becomes the only valid prerequisite if the campaign _is_ using the separate Artillery skill option, but that would be ideal.

**Comment by IllianiCBT** [comment]
Resolved by #4582

**Comment by repligator** [comment]
Reopening. As of MHQ Code Revision: ab52c2e15ffce1aecdf583da820223f7d7c1ca4a (built the 23rd of August) Artillery does _not_ fulfill the prerequisites of Oblique Artillery.

**Comment by IllianiCBT** [comment]
Closing as resolved
