### ISSUE TITLE
RFE: GUI - Personnel tab side panel scales poorly to content, does not remember resizing.

### ISSUE THREAD

**Issue by Tzahr** [MegaMek/mekhq#4433]
In MekHQ's Personnel tab the side panel scales poorly, meaning some of the data is not easily readable when opened unless resized.
Resizing is also lost when the panel is closed and opened by double-clicking any entry. 

-> Remember resizing when opening/closing.
-> Improve default scaling of side panel to show additional content.

**Comment by IllianiCBT** [comment]
Can you take a look at this Action: https://github.com/MegaMek/mekhq/actions/runs/10326994396. The file at the bottom of the page works exactly like a Nightly. Lemme know if you see an improvement and if not, post a screen-grab so I can see what you're dealing with.

Note that I didn't include saving of pane width, because frankly I don't know how. :D

**Comment by Tzahr** [comment]
Happy to say this looks much better!
All info is now readable by default.

**Comment by IllianiCBT** [comment]
Closing as resolved - happy to help :)
