### ISSUE TITLE
RFE: Education Module - further refine text clarity highlighting. 

### ISSUE THREAD

**Issue by Tzahr** [MegaMek/mekhq#4515]
A refinement of the changes introduced with #4452 - messages are now negative/neutral/positive colour-coded but can benefit from additional tweaks in formatting to increase clarity. 

Specfically colour-coding the whole text element in the report has the downside of also colour-coding the character's name, which is less than ideally readable, and also hihglights a lot of miscellaneous text, rather than picking out the specific key term relevant. I further suggest to confine colour-coding to specific text segments, and to selectively bold said text segments to enhance readability. I have provided an example: 

![image](https://github.com/user-attachments/assets/589fc579-5207-438d-8c02-7399a52184c3)

This should further improve at-a-glance clarity.

**Comment by IllianiCBT** [comment]
This is very doable, but would require reformatting how these messages are parsed into MekHQ, as currently it's done as a String, whereas this would likely require using StringBuilder and then parsing it into a String. Not terribly difficult, will just require a little elbow grease due to the number of possible messages. I'll take a look and see what I can do.

**Comment by IllianiCBT** [comment]
Closing as resolved
