### ISSUE TITLE
Repair bay uses the wrong ammo bin

### ISSUE THREAD

**Issue by Question2** [MegaMek/mekhq#455]
In this save I have a damaged Vulture in the repair bay whch uses ATMs, and two missing ATM ammo bins, one of which is a normal ATM ammo bin and the other is a ATM HE ammo bin. I only have ATM HE Ammo bins in my warehouse, but the repair bay thinks i have normal ATM ammo bins available as well. If i go ahead with the repair, the repair bay will replace the ATM ammo bin with a ATM HE ammo bin.

Im pretty sure this wasnt the case in a previous version, if you didnt have the exact ammo bin, the repair bay would tell you and you could order the part manually. The way it works now, users will often do mass repairs and not have any idea that the ammo bin replaced is the wrong one unless they manually check every unit after every repair.

[#battletech.zip](https://github.com/MegaMek/mekhq/files/1308732/battletech.zip)

**Comment by Bonepart** [comment]
ATM and ATM HE ammo bins are compatible, they are essentially the same thing, just getting loaded with a different variant of the same missiles. As such I made a fix that checks the munitions type of the replacement part and will change it before replacing it. In this case it will change the ATM HE bin to a standard ATM bin so that after it's replaced you are reloading the ammo you expect.

I should be able to put up the pull request by tomorrow.
