### ISSUE TITLE
Custom OMNI Mechs throwing error in MekHQ

### ISSUE THREAD

**Issue by TheLegendBoss** [MegaMek/mekhq#4687]
### Environment
What version of MekHQ does your issue apply to?
MekHQ v0.49.19.1

**What operating system are you using?**
Windows 10 Home - Version: 10.0.19045 Build 19045

**What java version are you using?** 
Java Version: 17.0.5

### Description
I created a custom unit(s) (Timber Wolf X in the logs provided), and I'm getting an Uncaught java.lang.NullPointerException (attached image), and the logs are showing errors. 

![image](https://github.com/user-attachments/assets/974fef00-8f9e-4823-93e1-ec95e121d5f5)

As you can see in the log file, I have a custom and non-custom units, but both are throwing this error. I do have other custom clan mechs that don't have this issue, but it only affects OMNI mechs with the Puma and Timber Wolf both seeming to be the source of the issue. When I add either to procurement/buy lists I get the error when proceeding to the next day and the procurement request fails to complete. 

```
15:04:02,662 ERROR [mekhq.campaign.unit.UnitOrder] {AWT-EventQueue-0}
mekhq.campaign.unit.UnitOrder.getNewEquipment(UnitOrder.java:122) - Could not find a mech summary for Mad Cat X

15:04:02,662 ERROR [mekhq.campaign.unit.UnitOrder] {AWT-EventQueue-0}
mekhq.campaign.unit.UnitOrder.getNewEquipment(UnitOrder.java:122) - Could not find a mech summary for Puma Prime
```
### Files
Attached is the campaign save files and the autosave around it as well. 
Custom.zip contains all the custom mechs from Mechlab and the Campaign. 
And the log is provided. 

[Campaign Files.zip](https://github.com/user-attachments/files/16700870/Campaign.Files.zip)
[customs.zip](https://github.com/user-attachments/files/16700871/customs.zip)
[mekhq.log](https://github.com/user-attachments/files/16700872/mekhq.log)

**Comment by Sleet01** [comment]
Takin' a look...

**Comment by repligator** [comment]
I'm 99% sure this is https://github.com/MegaMek/mekhq/issues/4057 or closely related.

**Comment by Sleet01** [comment]
On loading this into the latest dev code, I'm actually seeing it complain about the Mowang and Manatee, but not the Mad Cat X or Puma Prime.

<img width="784" alt="image" src="https://github.com/user-attachments/assets/f2736ea2-2fbf-4c6d-85eb-beeefeeddbce">

Are those customs; if not, they might have simply been caught up in a renaming pass as wll.

**Comment by TheLegendBoss** [comment]
Here is the updated customs file, sorry about the miss
[customs.zip](https://github.com/user-attachments/files/16701107/customs.zip)

**Comment by Sleet01** [comment]
This is definitely related to #4057 .  The main issue is that we changed a lot of unit names (and the methods that load them) in 0.49.19[.1] but a few spots were missed - specifically, IIRC, handling old filenames correctly after the transition.

Rather than do a lot of manual fiddling, I tried loading the latest campaign save into 0.49.20, which should have all the updates and fixes for this code path (I did have to advance the day to get the damaged units to show up in the repair bay).
I then saved the as a new file, and loaded it back into 0.49.19.1.  This appears to have corrected the file name issues.

file:///home/martin/Documents/MegaMek_dev/MekHQ_4687_NPE_loading_old_campaign/Campaign.Files/Rickard's Royal Guards32641208_loaded_into_0.49.20.cpnx.gz

I'd say give this a try; if it's broken / doesn't work for you, we can try something else.

**Comment by Sleet01** [comment]
@TheLegendBoss Try this save:
[Rickard's Royal Guards32641208_loaded_into_0.49.20.cpnx.gz](https://github.com/user-attachments/files/16701984/Rickard.s.Royal.Guards32641208_loaded_into_0.49.20.cpnx.gz)

**Comment by TheLegendBoss** [comment]
The save works, thank you!

**Comment by Sleet01** [comment]
Okay, let's close this for now.  It'll still be accessible in case we need to re-open the issue with more info later, but I think we understand the underlying issue, and it's resolved in later releases.
