### ISSUE TITLE
Custom Ranks not loading. defaulting to second star league

### ISSUE THREAD

**Issue by Docwade** [MegaMek/mekhq#4704]
### Environment
-49.20
-windows
java17

Wont load custom ranks. it seems to default to second star league

[individualRankSystem.zip](https://github.com/user-attachments/files/16740775/individualRankSystem.zip)
@IllianiCBT
[mekhq.log](https://github.com/user-attachments/files/16740785/mekhq.log)

**Comment by IllianiCBT** [comment]
I managed to track down the issue to the final entry in your rank system

![image](https://github.com/user-attachments/assets/7d2a3ffb-bf31-4a25-93ab-85d0b09e4901)

This is telling mhq that one of the role categories should inherit the MechWarrior rank, however as the MechWarrior rank is null, mhq silently fails to load the rank system. I'm also somewhat confident that the file should be called 'ranks' and that the opening tag should be `rankSystems` however, I could be wrong there.

I also noticed you had a lot of duplicate rank names, instead of using the inherit rank option.

I've included a cleaned up, working, copy of your rank system below.

[ranks.xml.zip](https://github.com/user-attachments/files/16740989/ranks.xml.zip)

Closing as non-valid issue :)
