### ISSUE TITLE
[0.50.0] Save files not loading on fresh campaign

### ISSUE THREAD

**Issue by LadyAdia** [MegaMek/mekhq#4728]
Fill out the fields below with as much pertinent information as possible to help the developers solve the issue.
Search for your issue inside open and closed issues first before reporting so as not to make duplicates.
(Delete the above lines)

### Environment
What version of MekHQ does your issue apply to? 0.50.0-Snapshot
What operating system are you using?  MacOS 14.5
What java version are you using? 17.0.12

### Description
- Upon loading a saved campaign, an error shows. This has so far only happened with new campaigns started in this version. Error message mentions this is an academy error and suggests changing students to "active," but error shows even when no personnel are students.

### Files
[MekHQ Save Bug 24-08-27.zip](https://github.com/user-attachments/files/16767241/MekHQ.Save.Bug.24-08-27.zip)
[MekHQ Custom Files 24-08-27.zip](https://github.com/user-attachments/files/16767242/MekHQ.Custom.Files.24-08-27.zip)
<img width="1440" alt="Error Screenshot 24-08-27" src="https://github.com/user-attachments/assets/809a6f25-5cec-4a37-8b67-a541a3712d6e">

**Comment by IllianiCBT** [comment]
Can I confirm what version this campaign was started in?

**Comment by IllianiCBT** [comment]
I've removing my assignment from this task and flagging it with the other, more experienced devs. I've been able to confirm it's not related to academies (that was just a poorly worded error message that I've since corrected). And I've tracked down _where_ the error is occurring, but I'll be darned if I can figure out _why_ it's occurring.

**Comment by Sleet01** [comment]
Whoof, that is a lot of transportation -_-;

It looks like this issue is caused by the way we parse and store transport bays _as parts_, separately from how we load transports bays _as bays_ when reading a unit out of XML.
The root cause is that we're trying to log an error about loading a bay part with child parts that cannot be instantiated, but we immediately throw those child parts away so it's not really important that we know exactly what its bay number is.
Furthermore, all of this info gets reconstituted later in the loading process _anyhow_, so it doesn't even matter if we can't glean the specific bay # at the point where this error is occurring.

@LadyAdia Do you recall if you loaded your dropships onto the jumpships recently in your campaign history, or have they been set up like that for a while?
If the latter, can you recall the last version of MHQ that let you load this campaign without throwing an error?

**Comment by LadyAdia** [comment]
This campaign was created on 0.50, so it hasn't happened on other versions. And every campaign I create on .50 eventually gets that error. Oddly enough, the campaign I ported over from .49.20 doesn't get this error, and I regularly try to assign units to transports because I like getting into those details.

**Comment by Sleet01** [comment]
@LadyAdia Do you find that you get a lot of destroyed doors on your DropShips, at load time?  I'm seeing that in this campaign but I'm not sure what the cause is.

**Comment by LadyAdia** [comment]
That's happened to me once in .49.19.1 but not recently.

**Comment by LadyAdia** [comment]
I downloaded this build to test it out and it loaded successfully on my end.

**Comment by Clappie** [comment]
I've been getting a pretty similar error on my part from MekHQ Nightly Build #1597.

I have a campaign I started in Nightly Build #1591 some days ago, and decided to update to #1597 today.

My saved campaign loads perfectly fine the first time, but if I then make a new save in 1597, and then try to load it agian, an error pops up. So far in my campaign I have not yet touched the education module. 

What version of MekHQ does your issue apply to? 0.50.0-Snapshot Nightly Build #1597
What operating system are you using? Windows 10 Pro
What java version are you using? 17.0.12

![image](https://github.com/user-attachments/assets/6a3ad234-16ba-4cd0-a6c2-75b3e1e5d3ec)

[MekHQ.zip](https://github.com/user-attachments/files/16778471/MekHQ.zip)

I have attached the save file (the one I saved in build 1597), custom mech folder and MekHQ log. 

First time trying to report a bug, so please let me know if there is anything else I should include.

**Comment by LadyAdia** [comment]
I just tried to load my save and got the exact same error message. I'm using the fix from earlier. I'm attaching my latest save and logs for more data points.
[MekHQ Save Error 24-08-28.zip](https://github.com/user-attachments/files/16782635/MekHQ.Save.Error.24-08-28.zip)

**Comment by UlyssesSockdrawer** [comment]
I am also hitting this issue. Attaching my save from CI1597 nightly in case it helps.
[The Nova Dragoons30000826.cpnx.gz](https://github.com/user-attachments/files/16785489/The.Nova.Dragoons30000826.cpnx.gz)

**Comment by Sleet01** [comment]
@UlyssesSockdrawer @LadyAdia @Clappie Would one of you be willing to file a new issue on the `getCommander()` error?  It looks like a different issue from this one, and combining the two will make tracking fixes more difficult.
Thanks!

**Comment by UlyssesSockdrawer** [comment]
On it - will link it here ASAP.

**Comment by UlyssesSockdrawer** [comment]
https://github.com/MegaMek/mekhq/issues/4738 @Sleet01
