### ISSUE TITLE
[mek-hq-0.42.2 : Bug] Element type portr Error

### ISSUE THREAD

**Issue by SirMegaV** [MegaMek/mekhq#473]
All the sudden my campaign file cannot load due to this error. Campaign and log file attached.

[Element_type_portr_Error.zip](https://github.com/MegaMek/mekhq/files/1339327/Element_type_portr_Error.zip)

**Comment by pheonixstorm** [comment]
First section `org.xml.sax.SAXParseException` It looks like this did not save correctly and is missing a few things. Digging into the file it would appear that the save is broken after it tried to save and somehow did not fully save the base defense scenario at one of the portraits. You should fire Sergeant Cheng-en Zha, that is where the problem happened. This could also be the reason for the NPE since the last line in this section is `<portr` instead of `<portraitFileName>`

I will see if I can salvage the file, though it would be easier to revert to a previous save

**Comment by SirMegaV** [comment]
Thanks. No need to save the campaign, it was between scenario so no games
were played.

Is this a one time occurrence?

**Comment by neoancient** [comment]
It's possible. If not, any relevant error would be in the log file from the session when you saved the campaign, which I suspect is long gone.

**Comment by SirMegaV** [comment]
Yes it's long gone. Close the ticket?
