### ISSUE TITLE
Combat Action being awarded multiple times

### ISSUE THREAD

**Issue by repligator** [MegaMek/mekhq#4919]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Medium (Gameplay Limitation): Non-core functionality is impaired, providing a suboptimal but playable experience.

### Brief Description *

The combat action award is being issued after every scenario, and possibly every month as well, even if the pilot already has the award.

### Steps to Reproduce

1. Load the 1st MHQ save.
2. Note that all 5 pilots in the pending scenario have combat experience.
3. Start the pending scenario. /victory on the first turn.
4. Observe as all the pilots are issued with combat action awards.

### Operating System *

Linux

### Java Version *

17

### MekHQ Suite Version *

Free Text (type manually)

### Custom MekHQ Version

https://github.com/MegaMek/mekhq/commit/7779b817d1b00ec50c9dd1912913caed20774cd2

### Attach Files

[CBS302530250409.cpnx.gz](https://github.com/user-attachments/files/17165954/CBS302530250409.cpnx.gz)
[mekhq.log](https://github.com/user-attachments/files/17165960/mekhq.log)

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by IllianiCBT** [comment]
To confirm: you are not using any custom award sets?

**Comment by repligator** [comment]
Everything is vanilla, nothing custom.

**Comment by IllianiCBT** [comment]
So, what's happened is these awards were issued prior to the fix I put in the other day, so they weren't being stored correctly. This means that while the characters got the awards from their Awards, when you next loaded the save all those Awards were lost, so when autoAwards checked to see if the characters were eligible it found that they were, because insofar as mhq is concerned, they haven't received any awards.

The workaround is to turn off xp and edge awards in campaign options, manually run the award ceremony, issue all the awards it recommends. Turn back on xp and edge awards (if you use those settings), and you'll be good from now on.

Closing as resolved.
