### ISSUE TITLE
Cant leave system keeps adding another day

### ISSUE THREAD

**Issue by Rocolid** [MegaMek/mekhq#5199]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

High (Major Disruption): A major feature is broken or incorrect, but a workaround exists.

### Brief Description *

i cant leave the system I'm on and Gming to a different system also doesn't help either
![Screenshot 2024-11-14 123919](https://github.com/user-attachments/assets/ca704d0c-88a0-4c36-b6cd-dbd04b684a68)
![Screenshot 2024-11-14 124031](https://github.com/user-attachments/assets/dd2a5b41-85ad-47d2-a89a-1285d56a3fa4)

### Operating System *

Windows 11

### Java Version *

11.0.22

### MekHQ Suite Version *

v0.49.19.1

### Attach Files

[logs.zip](https://github.com/user-attachments/files/17744653/logs.zip)

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by Rocolid** [comment]
I'm on the planet trying to go to another system and every time advance day it adds another day to the travel

**Comment by Rocolid** [comment]
Like i start on the planet then I chart course and transit I press advance day and I don't move at all and just a day get added to my travel

**Comment by Setsul** [comment]
It's showing x days out from the planet x days after you've left the planet. That is entirely correct, if confusing, and not exactly useful.
Going from the jump point to the planet it would be counting down.
In newer versions MekHQ counts down both ways, which I assume is what you expected.

In the Dieudonné system it's going to take 18 days (17.36 technically) to the jump point and then you'll jump.
Unless you can show us a screenshot where you're 18 or more days out and still haven't jumped, this is working entirely as it should.
We also can't even attempt to replicate the problem because you did not attach the save file.

**Comment by Rocolid** [comment]
Im out right now I'll send the save when I get back. This isn't the first time this happened last I fixed it by going to  a much older save on the campaign

**Comment by Rocolid** [comment]
[Qades Authority30280818.cpnx.gz](https://github.com/user-attachments/files/17751292/Qades.Authority30280818.cpnx.gz)

**Comment by RaozSpaz** [comment]
So since you seemed to miss the point of what Setsul and I was saying, Dieudonne [the planet you are on] is 17.37 days away from the jump point. The reason you are not travelling away from the system after clicking is because you are getting to said jump point. After you've passed 18 days your ship will either be at the jump point or actually have made its first jump.

IF you pass 19 days and it still hasnt moved you to the next system, then there is actually an issue.

**Comment by Rocolid** [comment]
![image](https://github.com/user-attachments/assets/84fb761f-5ceb-45d9-adaf-dd3b393116d5)

**Comment by Rocolid** [comment]
yeah it works now im stupid

**Comment by RaozSpaz** [comment]
Its all good. Everyone makes mistakes sometimes XD

**Comment by Rocolid** [comment]
Thx
