### ISSUE TITLE
RFE: Select Portrait when promoting personnel

### ISSUE THREAD

**Issue by scJazz2** [MegaMek/mekhq#526]
If, because of options, a portrait is not selected and then you purchase skills and change Primary Role that promote a Person into a group that does use portraits... please select a portrait.

**Comment by Qwertronix** [comment]
By "Select" here you mean "have MHQ randomly select one for me" right? That's what I understood based on our discussion in Slack at least.

**Comment by scJazz2** [comment]
yes

**Comment by Qwertronix** [comment]
If I can figure out how the Campaign Options UI works and how to add the option in there, I can probably do this sometime this weekend. The actual portrait assignation process itself should be just an extra 3-4 lines since all the code to check for a portrait and randomly assign one is already available. Making it a selectable option in the menus is actually the more difficult part for me :rofl:

**Comment by Windchild292** [comment]
This has been implemented and can be closed

**Comment by Windchild292** [comment]
Reopening and reclosing to see if that fixes a github state issue.
