### ISSUE TITLE
V50.01 - Lance Commanders are not persisting upon loading of a save

### ISSUE THREAD

**Issue by RaozSpaz** [MegaMek/mekhq#5304]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Medium (Gameplay Limitation): Non-core functionality is impaired, providing a suboptimal but playable experience.

### Brief Description *

![image](https://github.com/user-attachments/assets/69172f58-fd7e-46f7-9e65-7ab080864f80)

Upon loading any save, MekHQ will revert any settings relative to the commander of a lance. Or will readjust even the default settings of the commander [highest rank]. As shown in the picture above, the commander of the first tank should be the lance commander as they are the only Sergeant in the lance, but instead the MekWarrior is set as the commander instead.

NOTE: This reversion happens even if you use the built in system of HQ to override the default commander.

### Operating System *

Windows 10

### Java Version *

V17 Adoptium

### MekHQ Suite Version *

Free Text (type manually)

### Custom MekHQ Version

V50.01

### Attach Files

[Issue Package.zip](https://github.com/user-attachments/files/18018025/Issue.Package.zip)

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by Setsul** [comment]
This is an issue with multi-crew units.
The Force Commander is correctly saved and loaded from the save file and then replaced by a driver here
https://github.com/MegaMek/mekhq/blob/be7b4b934b39846b5aa913fb86fe6d87c78c43c2/MekHQ/src/mekhq/campaign/force/Force.java#L776
if they are not a driver.

Specifically, the saved and correct Force Commander is checked against the output of `getEligibleCommanders()`, which is garbage for multi-crew units at this point in the loading process. It's supposed to return the commander of each unit, but at this point `getCommander()` only has access to dummy Persons with only the UUID and every think else, including the rank, is 0 or null, so it will return the driver instead of the highest-ranked crewmember.

I can see at least 3 ways of fixing this:
1. Loading the ranks earlier.
2. Running `updateCommander()` later.
3. Modifying `updateCommander()` to only add a commander when a save file did not specify one, never replace them.

1 seems like a major rework of the save loading logic.
2 is a more minor rework since it only involves moving that call to after personnel records have been loaded completely. It does mean spreading the loading of the force organisation across multiple places, which is not ideal.
3 feels a bit like a kludge but should be the easiest. The one problem I can foresee is that it might run into issues with highlighting the commander's unit in the GUI, if that logic is run before ranks have been loaded and tries to find the commander's unit by commander their UUID against the output of `getCommander()`.

I'll leave the choice (and work) up to @IllianiCBT since they wanted to fix this and `getEligibleCommanders()` is currently their code.

**Comment by IllianiCBT** [comment]
Closing as resolved
