### ISSUE TITLE
Implemented Resupply Module #4518 - MekHQ not recognizing Cargo Mek's cargo capacity, relevant for Logistics Overhaul/Upgrade

### ISSUE THREAD

**Issue by OrbMonky** [MegaMek/mekhq#5324]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Medium (Gameplay Limitation): Non-core functionality is impaired, providing a suboptimal but playable experience.

### Brief Description *

Using two salvaged Daedalus 'meks, I was trying to get a convoy working, and got it set up and assigned. The issue presents in MekHQ - it does not recognize the meks as having any cargo capacity. It picks up 4.35 tons from an insulated cargo space on a Coolant Truck (Hover) and truncates to 4 tons, but does not pick up the combined 30 tons in the two stock Daedalus GTX2A 'Stevedore' meks. This is relevant for satisfying logistical requirements for the resupply feature.
![image](https://github.com/user-attachments/assets/df733e8d-c617-4238-9278-0329d9d4f02b)
![image](https://github.com/user-attachments/assets/e50d1d32-81ed-4e1b-a692-db57a73afa65)
![image](https://github.com/user-attachments/assets/377ee5d1-4f6d-43a0-b358-46578b2902d3)
![image](https://github.com/user-attachments/assets/9620fd51-a57b-4f0b-a3a0-cd75ae59062e)

### Operating System *

Windows 10

### Java Version *

17

### MekHQ Suite Version *

None

### Custom MekHQ Version

 Implemented Resupply Module #4518 

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by IllianiCBT** [comment]
So the issue here is that these _aren't_ cargo bays, they're fixed values of 'cargo'. So it's not saying that the unit has `x` cargo capacity, it's saying that the unit has `y` cargo.

I suspect this is a legacy decision, but @HammerGS might be able to weigh in as to how best to handle this. Because quite rightfully, players are going to see this and mentally parse it as cargo capacity.

**Comment by OrbMonky** [comment]
To put my two cents in; the unit obviously isn't carrying around a black box that is labelled 'cargo' - it seems that it could only function as a container that could be reasonably filled, used to transport, and then emptied. I think it definitely should count as cargo capacity for the purposes of Mekhq/stratcon if nothing else.

**Comment by IllianiCBT** [comment]
This issue is one of internals - I'm inclined to agree with you - but this value _appears_ to be just stored as a String and not as a definitive Part we can directly interact with. Meaning any parsing would need to be String-based -- i.e. checking whether the String `Cargo (` appears in the parts list (if it appears in that list at all, I'm making the assumption it does). String comparison is one of, if not _the_, weakest form of comparison because if the String ever changes we'd need to go in and fix any instance where it's being parsed.

Not to mention we'd need to parse _every_ part on the unit to find the 'cargo' parts.
