### ISSUE TITLE
[v0.50.02 Nightly] Infantry taking more personnel than specified to fill unit

### ISSUE THREAD

**Issue by LadyAdia** [MegaMek/mekhq#5372]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Critical (Game-breaking/Crash): The game crashes or a core feature (like saving, loading, or network connection) is completely unusable.

### Brief Description *

08:09:11,286 INFO  [mekhq.MekHQ] {main}
mekhq.MekHQ.initializeLogging(MekHQ.java:309) - Starting MekHQ v0.50.02-SNAPSHOT
    Build Date: 2024-12-13T03:35:44.686398237
    Today: 2024-12-14
    Origin Project: MekHQ
    Java Vendor: Eclipse Adoptium
    Java Version: 17.0.12
    Platform: Mac OS X 15.1.1 (x86_64)
    System Locale: en_US
    Total memory available to MekHQ: 2 GB
    MM Code Revision: b049c9a13fdd9cd53e2e94aa279446656259f913
    MML Code Revision: 97444ab86cff224d0ac82377932d42eb472b447b
    MHQ Code Revision: ec5f60783439c6f52ff4fb8a4f66f3453fd9b119

Infantry platoons set to use (for example) 24 soldiers are taking nearly double that number to fill the unit. Despite this, unit is still listed as "Crippled."

![Image 12-14-24 at 8 16 AM](https://github.com/user-attachments/assets/267d78d8-1519-4aea-af46-5644fcce6181)

Included in archive is the screenshot, all requited customs and user files, MHQ log, and the save file.

### Steps to Reproduce

Load the save

### Operating System *

Mac

### Java Version *

17.0.12

### MekHQ Suite Version *

Free Text (type manually)

### Custom MekHQ Version

0.50.02 Nightly

### Attach Files

[MHQ Infantry Bug 24-12-14.zip](https://github.com/user-attachments/files/18136248/MHQ.Infantry.Bug.24-12-14.zip)

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by IllianiCBT** [comment]
@psikomonkie I suspect this is related to your recent changes. I know you pushed a fix for the report Adia cites above, so might be worth seeing if it fixed this, too.

**Comment by psikomonkie** [comment]
When the nightly loads, it will improperly replace gunner references - it will lose the assigned gunners. If you save with the nightly without manually fixing it, the save will be missing gunners. 

After loading the save with the fix #5374 I saw the infantry units had more units in them than they should, but some were still missing gunner slots. I removed all the personnel, and reassigned them, and was left with many additional unassigned soldiers. I saved, and reloaded, and the infantry squads were still properly filled.

That aligns with the bug introduced by #5295 and fixed by #5374. My advice would be to not load MekHQ saves using the nightly until #5374 is merged.

**Comment by IllianiCBT** [comment]
To confirm, once the fix is in the issue will be resolved, or do players need to do anything to fix the issue if they have saved while the bug is in effect?

**Comment by psikomonkie** [comment]
> To confirm, once the fix is in the issue will be resolved, or do players need to do anything to fix the issue if they have saved while the bug is in effect?

If they saved while the bug was in effect, there's (at least) two different issues, both are resolved by unassigning and reassigning the crew.

- Gunners were misplaced when the save was loaded with the bug. You should unassign your gunners from your personnel menu, and reassign them. This also applies to Mekwarriors and other one-seated units where the driver is also the "gunner". It looks like infantry work this way too. 
- Some weird stuff happened if the user loaded the save with the bug in effect and tried to assign new gunners, including infantry. This could result in infantry squads with more people than there should be. This is resolved by unassigning and reassigning the soldiers.

**Comment by IllianiCBT** [comment]
Perfect. Once the fix is merged can you post in the nightlies channel letting folks know what the bug is and how to fix it in their campaigns?
