### ISSUE TITLE
12/26 Nightly / 0.50.02 SNAPSHOT - completed contracts show all scenarios 'pending', some have bizarre number of assigned units, no contract currently active.

### ISSUE THREAD

**Issue by OrbMonky** [MegaMek/mekhq#5543]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Low (Minor/Nuisance): Minor glitches or cosmetic issues that don’t affect gameplay and occur rarely.

### Brief Description *

I doubt this has any real impact outside of records loss, but I am out of a contract and upgraded to 12/26's nightly. Upon reviewing my Briefing Room, I found this;
![image](https://github.com/user-attachments/assets/ccbd683e-4cbf-46ae-933a-cc78e2889a9d)
Dropship Raid on the latter 3026 contract has 477 units assigned somehow

![image](https://github.com/user-attachments/assets/b4c0b0f8-831f-4810-8222-3a51e635ac32)
All scenarios are set to pending

Again, not on an active contract, but nothing should be showing as pending from what I'm aware of, even if it's meaningless. I guess the question is 'where did the data go?'
[logs.zip](https://github.com/user-attachments/files/18264511/logs.zip)

### Operating System *

Windows 10

### Java Version *

17

### MekHQ Suite Version *

None

### Custom MekHQ Version

12/26 Nightly / 0.50.02 SNAPSHOT

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by IllianiCBT** [comment]
Do you have a save from before you noticed this issue?

**Comment by OrbMonky** [comment]
That save is from the initial load into the nightly

**Comment by IllianiCBT** [comment]
We had a bug a few days ago that resulted from contracts failing to load correctly - it was a whole thing. Because the contract failed to load fully it didn't update the status of scenarios (which default to Pending) and, for some reason, dumped the entire TO&E into whatever scenario appears last (possibly first) in the internal array of scenarios for that contract.

This bug was fixed the day it was found, but it looks like you played on the broken version, resulting in the bugged records being enshrined in your save file.

To resolve this error you'd need to roll your campaign back to before the nightly of the 12th. However, this should just be a historical data issue and not cause any negative effects if you chose to continue this campaign - other than looking a bit weird.

Sorry about this one, I know it's a pain.

Closing as resolved.

**Comment by IllianiCBT** [comment]
Ignore my earlier message. I've figured out how to fix this retroactively.
