### ISSUE TITLE
43.5betaNov11 Dragoon Rating Support Manhours needed growing daily

### ISSUE THREAD

**Issue by SnyderPhilip** [MegaMek/mekhq#557]
Playing a campaign with Field Manual Mercenaries Revised Dragoon Rating.  This is especially noticeable in the Battle Armor support manhours needed.  Every time Advance day is clicked my support manhours needed would grow by a couple hundred manhours a day.  But this is only a temporary problem as if the game is saved, closed, and re-opened the manhours required goes back to normal.

**Comment by dericpage** [comment]
Can you upload a save game showing this problem?

**Comment by jslater89** [comment]
FYI, I fixed a similar issue for CamOps reputation here: https://github.com/jslater89/mekhq/commit/6c0d168137f394b861cbfb77eb39fa91035636fc

**Comment by SnyderPhilip** [comment]
Had a couple of missions to run so you could click it without it barking
[1st Kentwood Cavaliers.zip](https://github.com/MegaMek/mekhq/files/1557093/1st.Kentwood.Cavaliers.zip)
IIRC, you need the custom infantry unit in there for it to run.  I was playing with the customize Infantry Platoon feature in 43.4 and when I opened the game in 43.5Beta it wanted the file in the customs or it wouldn't load.

**Comment by Qwertronix** [comment]
`reInitialize()` is called in `Campaign.newDay()`, but what reinitialization does for the unit rating is simply `initialized` to false and then calls `initValues()`, which at least for DragoonsRating assumes it's a fresh unit and doesn't reset any values. 

Rather than resetting values manually I think it may be saner to simply wipe the old reference and gen a new instance of the unit rating in these situations, unless these objects are used elsewhere important that I'm missing. It would be practically the same amount of work for the JVM from what I understand.

**Comment by jslater89** [comment]
I believe @NickAragua changed it from 'new instance whenever needed' for performance reasons, although I may be misremembering.

CamOps rating behaves correctly; that is, it can be reused. I'd vote for fixing Dragoons rating, too. I can tackle that, if need be. I was in the unit rating code recently anyway.

**Comment by NickAragua** [comment]
Yeah, it used to fully recalculate the unit rating every time the user did... pretty much anything. Hire a new mechwarrior? Full recalc. Complete a scenario? Full recalc. Reload some ammo on a mech? You bet that's a full recalc.

**Comment by SnyderPhilip** [comment]
I should note that it still occurs in the main .43.5 release.

**Comment by NickAragua** [comment]
Fixed with PR #565
