### ISSUE TITLE
Ammunition Reload Issues

### ISSUE THREAD

**Issue by innocenteric** [MegaMek/mekhq#583]
### Environment
What version of MekHQ does your issue apply to? **0.43.6**
What operating system are you using?  Windows, Mac, or Linux? **windows**
What java version are you using?  If unsure it will state your java version at the top of the mekhqlog.txt file. **Version 8 Update 151**

### Description
 Some Mechs stay in the Repair Bay requiring additional ammunition. No matter how many times I try to replace the ammunition it stays. After many times of adding ammunition, I discovered that the ammunition was accumulating without limit.
![mad cat mk ii 2 ammunition issue](https://user-images.githubusercontent.com/34926411/34427096-2a3913d4-ec0c-11e7-8f5d-1e0b5abf356b.JPG)
### Files
Provide the .cpnx campaign file that this issue occurs in.
[Rascally Rabbits30720226.zip](https://github.com/MegaMek/mekhq/files/1592425/Rascally.Rabbits30720226.zip)
Provide any custom units that you are using in this campaign so that it will load on the developers machine.
[Rascally Rabbits.zip](https://github.com/MegaMek/mekhq/files/1592427/Rascally.Rabbits.zip)
Provide any other files that you have customized in this campaign like the factions.xml for example.
And provide the mekhqlog.txt file for any NPE's or errors that MekHQ might be reporting.
Do not paste the entire logfile text into this ticket. Just attach the actual mekhqlog.txt file
[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/1592428/mekhqlog.txt)

**Comment by purpledragon2** [comment]
I had this same issue with a dropship that had never seen combat with me.  needed ammo reloads.  took all my reloads and never changed the status.

**Comment by innocenteric** [comment]
I tried using one of the mechs with the ammo overload today and it shows I have zero ammunition for the type in question.

**Comment by neoancient** [comment]
The campaign file is not a valid zip file.

**Comment by innocenteric** [comment]
[Rascally Rabbits30720917.zip](https://github.com/MegaMek/mekhq/files/1597452/Rascally.Rabbits30720917.zip)

try this one

**Comment by Jesterr** [comment]
This problem seems to still exists in mekhq-0.44.0-windows.

(for me) Meks with "advanced" gear seem to be affected, while meks and vees with introductory gear seem to be unaffected.

For me, all mechs that utilize Artemis ammo 'consume' the right number of reloads, but do not reload the bay.  Swapping to standard does the same thing, but for the standard ammo.  (Ie, it consumes the ammo from the warehouse, but does not actually fill the bay or clear the task.)  Works with Mass Repair in a group, Mass Repair individual mek, or selecting the reload job and then clicking Do Task.  GM Mode-> Complete Task has the same behavior.

Just this week I upgraded my version from 0.42.2, and loaded my current campaign save.  All meks appeared "okay" without repair jobs.  Each mek, as it comes out of a mission, becomes impossible to reload, but only for meks with Artemis or "advanced" gear like a gauss rifle.  Standard gear only meks/vees seem to work fine.  (Ie, my Von Luck tank, with SRM6 and SRM4s reload fine.  My Battlemaster customer with SRM6 and artemis, will not reload the SRM6 ammo.  My Highlander HGN-732b won't reload its LRM20 (std not artemis).  )

So far, the actions have persisted across restarts of mekhq.  Campaign file, and mekhq log file provided.

[Jester's Fools30470530.zip](https://github.com/MegaMek/mekhq/files/2238425/Jester.s.Fools30470530.zip)
[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/2238426/mekhqlog.txt)
