### ISSUE TITLE
Using 43.6 on mac Os X using the advanced mech search option, you have no way to access ....

### ISSUE THREAD

**Issue by Mekslayer** [MegaMek/mekhq#587]
... the "accept parameters of search" button so its useless. 
I am running El Capitan Os X version 10.11.6

My Java is one of the latest. The macbook pro is an i7.

What version of MekHQ does your issue apply to?
What operating system are you using?  Windows, Mac, or Linux?
What java version are you using?  If unsure it will state your java version at the top of the mekhqlog.txt file.

### Description
Describe the issue and provide screenshots ingame if able.
Provide the rulebook, page number, and text if you feel like this is a rules issue.
And provide the steps you have taken to reproduce the issue in the campaign file if applicable.

### Files
Provide the .cpnx campaign file that this issue occurs in.
Provide any custom units that you are using in this campaign so that it will load on the developers machine.
Provide any other files that you have customized in this campaign like the factions.xml for example.
And provide the mekhqlog.txt file for any NPE's or errors that MekHQ might be reporting.
Do not paste the entire logfile text into this ticket. Just attach the actual mekhqlog.txt file

**Comment by BLOODWOLF333** [comment]
![image](https://user-images.githubusercontent.com/16950832/35185284-ae1a8eea-fdc7-11e7-9c32-2a8d7e8f94ef.png)

Is this what your talking about?  At least provide a screenshot and put just a little bit of effort into the bug report if you want the developers to put any effort into addressing your concern.  Yes that window size is too big for low resolutions but the work around is to click the filter expression box then use TAB to advance the cursor behind the taskbar and hit enter on [Okay].  Its the same way in megamek, the whole thing has to be redesigned, and eventually somebody will address it.

**Comment by Dylan-M** [comment]
There actually needs to be a discussion among the team about minimum resolution support. The reason that the window has a large minimum size is that there is a lot going on in that dialog. I personally wouldn't want this dialog any smaller than it is already. A complete layout redesign would be the only potential way to make it smaller.

Anyway, it is 2018, and the number of people with tiny monitors and tiny resolutions is rapidly dwindling. Even my 15" laptop monitor (the smaller of my 2 laptops) can fix the whole dialog at the resolution I run it at. There are, sadly, several dialogs like this across the programs.

**Comment by scJazz2** [comment]
All of the Windows and Dialogues should respect the size of the Monitor they are displaying on... minus Taskbar. This is the real issue.

**Comment by Dylan-M** [comment]
@scJazz2 I'm going to disagree with you, the real issue is what I said, we may need to decide to have a minimum resolution requirement for our programs like many, many other games do. It would be very difficult to "respect" monitor resolutions that are very small. Should we still support 640x480? I don't think so. Sometimes things just need more real estate, and coding scrollbars around that would get ridiculous.

I would expect 1440x900 to be a reasonable minimum resolution. Steam stats from last year show that less than 20% of users are running resolutions lower than that.

**Comment by scJazz2** [comment]
@Dylan-M I am going to respectfully disagree with you. My laptops main rez is... 1366 x 768. Java already includes the ability to respect Monitor size. Use it plz.

**Comment by Dylan-M** [comment]
I'm not sure what ability you're talking about, feel free to link to the relevant documentation. None of the scaling methods I know of to do what you're suggesting work well.

**Comment by swang300** [comment]
One solution is to make all dialogs have scrollbars, and center/maximize with the following code (or similar)
```
GraphicsConfiguration gc = dialog.getGraphicsConfiguration();

Rectangle bounds = gc.getBounds();

Insets screenInsets = Toolkit.getDefaultToolkit().getScreenInsets(gc);

Rectangle effectiveScreenArea = new Rectangle();

effectiveScreenArea.x = bounds.x + screenInsets.left;
effectiveScreenArea.y = bounds.y + screenInsets.top;
effectiveScreenArea.height = bounds.height - screenInsets.top - screenInsets.bottom;        
effectiveScreenArea.width = bounds.width - screenInsets.left - screenInsets.right;
```

**Comment by Dylan-M** [comment]
Another solution would involve people not using computers and resolutions that are 2 decades old ;)

Besides which, I'm working to _**Eliminate**_ the use of Toolkit because it's very bad joojoo. It was an internal API that never should have made it into the wild. There are proper ways to do the same things, and in fact I have a testing branch using those proper ways.

Regardless, that is a hack solution to a problem that exists purely because people won't upgrade, and I'll return to my earlier point about statistics pointing that very few people are running on such outdated resolutions. I do understand that it can be expensive to upgrade, hell I was dirt poor (below poverty level) for much of my life because my parents were and it took me awhile to pick myself up by my bootstraps. But, I didn't blame the game manufacturers for moving on with newer technology when I couldn't play oh... MW3 or Morrowind for examples. It was my own issue that I was using outdated equipment, and game studios/developers should not have been responsible for that. Nor should this team be responsible for players who fall behind because we're adjusting to the world as it currently is.

Finally, there are certainly better ways to handle this than forcing a resize that messes up the neatly laid out components or uses unsupported hacky code. Once more important things are done, this can be addressed, but for now the point of my long diatribe is: Take responsibility for owning outdated hardware and stop blaming the software for moving on without you. That is a blanket statement with no specific "you" and coming from someone who only got a 1080p monitor a couple years ago and 4K a few months ago (dual 4K purchased by my job, hallelujah).

**Comment by Dylan-M** [comment]
I should mention that I'm also slightly irritated due to the same tripe complaints from people about the HBS BT game and not being able to play it on their 7 year old computer. Seriously, you can't have it both ways no matter how much we wish we could.

**Comment by sixlettervariables** [comment]
Most of these dialogs have been updated to work on smaller monitors as of the 0.45.X line. Please open a new issue if there is a specific dialog that does not work on a lower res screen.
