### ISSUE TITLE
Clan Techs penalized for work on Clan Units

### ISSUE THREAD

**Issue by scJazz2** [MegaMek/mekhq#588]
0.43.6

Clan Techs are getting non-Clan Tech penalties for maintenance/repair.

The Clan Tech Knowledge (Unofficial) SPA is not operative.

Does/Should Ghost Bear Dominion faction deserve non-Clan penalty?

Attached is some chat on subject from Slack MHQ

[ClanTechnician.txt](https://github.com/MegaMek/mekhq/files/1594902/ClanTechnician.txt)

**Comment by neoancient** [comment]
Since you didn't provide a campaign file I tried to reproduce it using the Fist and Falcon sample campaign files.

From Kewran Wolfhounds, IS tech working on Mad Cat Mk II:
![image](https://user-images.githubusercontent.com/16927464/35120040-731c5a60-fc5c-11e7-9b78-07d28f29d3da.png)

From Binary Bravo, Clan tech working on Kodiak:
![image](https://user-images.githubusercontent.com/16927464/35119998-516e6be2-fc5c-11e7-91f9-00beaac4b2d1.png)

The IS tech gets a penalty for working on a Clan unit but the Clan tech does not. If you have seen otherwise, please provide a campaign file.
