### ISSUE TITLE
[RFE] - Mass Mothball/Activate UI interface

### ISSUE THREAD

**Issue by NickAragua** [MegaMek/mekhq#601]
This is mostly here so I don't forget about it.

Given the amount of mothballing/reactivation that a player might undertake to cut down on transport costs (to hire Mule-class dropships instead of a bunch of Unions), it may improve usability to have an interface that allows many mechs to be mothballed/activated at a time.

**Comment by purpledragon2** [comment]
I agree with this idea.  However, I wonder if there might need to be a mission or rather a scenario type that requires dropping or landing units in a hot zone.  Just to cut back on people taking advantage of not ever needing to have a military dropship.

**Comment by pheonixstorm** [comment]
The need for a military dropship lies best in its transport bays. Without them you are at a +1 or +2 penalty to maintenance and repairs due to the lack, especially when playing AtB which enforces this for the most part.

Leasing a Mule over a Union won't save you a lot, but often times dropships are expensive and hard to come by. The difficulty will only increase once I get the rest of the Campaign Operations rules entered into HQ.

**Comment by NickAragua** [comment]
Features has been implemented in PR #811
