### ISSUE TITLE
Jihad-era mech available in market in 3025

### ISSUE THREAD

**Issue by RexPearce** [MegaMek/mekhq#618]
To reproduce:

1. start a campaign in 3025
2. Ensure "Limit units and parts by year" is enable in Campaign Options -> Tech Limits
3. Enable GM mode
4. Add some funds (so you can hire)
5. Hire a logistics admin (so you can buy things)
6. Go to Marketplace -> Purchase unit
7. Search for Phoenix Hawk LAM PHX-HK1RB and see that it's available.

Looks like the intro date and extinct dates are incorrect. Might be related to issue #617

**Comment by BLOODWOLF333** [comment]
![slack](https://user-images.githubusercontent.com/16950832/35242969-e79dc7d0-ff80-11e7-9a0d-b03f14f18ae9.png)

Not able to duplicate.  Yeah it shows the unit but its impossible to buy.  Seems to be working as designed.

**Comment by BLOODWOLF333** [comment]
![image](https://user-images.githubusercontent.com/16950832/35243144-7870a34a-ff81-11e7-8561-ce30b6c180c7.png)

Actually my bad, there are other rules you have to turn on other than limit parts and units by year (allow purchasing of units I didnt have on).

**Comment by RexPearce** [comment]
I don't think it shouldn't be listed at all in 3025 (no other Jihad units are listed...)

Also, in your screen shot, the intro date on left (2701) does not match the earliest date on the right "3052", or the extinct date range "2790-3067".

I'm guessing some sort of copy&paste error occurred here.

**Comment by RexPearce** [comment]
http://www.masterunitlist.info/Unit/Details/4821/phoenix-hawk-lam-phx-hk1rb

According to MUL, this unit was actually introduced in 3077, so none of the dates here (except it being extinct 3085+)

**Comment by neoancient** [comment]
There are a number of units that have intro dates earlier than some of the equipment they mount. Sometimes it's just a couple of years, but I think there are some with snub-nose PPCs a century or so before it was introduced. This may have been another such unit, having an intro date over three centuries before the C3i was developed. If so, they have since corrected it but they don't tell us when the dates are fixed so we only make the change when somebody happens to notice it.
