### ISSUE TITLE
0.43.8 ATB: RAT/Contract Generation Error (Federated Suns/Commonwealth)

### ISSUE THREAD

**Issue by SnyderPhilip** [MegaMek/mekhq#663]
Between the years 3058 and 3067 there is a naming error in either the RAT and/or the Contract Generator  This is likely a result of the RAT being updated to newer information while the Contract Generator remains with older data.  Contracts are generated using the Federated Commonwealth as Employer/Enemy, but there is no Federated Commonwealth in the RAT generator for that time period, they are referred to as Federated Suns instead.  This causes an issue in mission generation in which no Opfor is generated in the case of the Federated Commonwealth being the enemy, or no ally units being generated in the case of the Federated Commonwealth being the employer.  Prior to 3058, this issue does not occur, as the Federated Commonwealth has a RAT at that point, and after 3067 the Federated Commonwealth ceases to be a valid employer/enemy. (though hold over contracts could still occur in the example of a 24 month garrison contract signed in 3066)

**Comment by jayof9s** [comment]
So, the Lyran half split off in late '57 but the Fed Suns half of the nation continued to call itself the FedCom until a decade later in '67. Planets.xml reflects this which is where AtB is pulling the factions from.

We either need to relabel the FedSun rats to FedCom for that time-frame or point the FedCom faction to the FS rats when a dedicated FC rat is otherwise unavailable.

**Comment by Dylan-M** [comment]
Changing this to post-stable, and we're not going to be able to fix it without a campaign file that is set up to replicate it.

**Comment by Windchild292** [comment]
This duplicates #251
