### ISSUE TITLE
Mech Refit breaks Day Progression

### ISSUE THREAD

**Issue by SVNaas** [MegaMek/mekhq#664]
Fill out the fields below with as much pertinent information as possible to help the developers solve the issue.
Search for your issue inside open and closed issues first before reporting so as not to make duplicates.

### Environment
MekHQ v0.43.8
Windows 10
(Incorrect, java version not present in mekhqlog.txt) - Java 1.8.0_161

### Description
Custom mech refit breaks day progression, to replicate start a refit from within MekHQ.
![image](https://user-images.githubusercontent.com/37005983/37067456-c3f6d4aa-21a1-11e8-9084-ec32d536d9fb.png)

### Files
[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/1787328/mekhqlog.txt)
[mekhq.zip](https://github.com/MegaMek/mekhq/files/1787337/mekhq.zip)
Two campaigns with error, also of note in the log is units with invalid quirks. Further I was unsure if my portraits folder was needed so please let me know if so.

**Comment by pheonixstorm** [comment]
Known issue and should already have a ticket. If not on github then over on sourceforge

**Comment by Battleclad** [comment]
Just filing it as asked.

**Comment by NickAragua** [comment]
I'll take a look at the save file anyway, just to make sure.

**Comment by NickAragua** [comment]
Looks like the day advances properly with that fix, but there's still some kind of "part not found" error still that prevents the refits from progressing. You should be able to work around it by gm-completing the refit though.

**Comment by Dylan-M** [comment]
@NickAragua What's your status with this?

**Comment by NickAragua** [comment]
I'll look into it today.

**Comment by NickAragua** [comment]
Looks like it's possible to get a unit to stay in "refit" mode indefinitely by undertaking the following steps:

1) Customize a unit in meklab, but either don't have enough money or fail part acquisition rolls
2) Remove the necessary parts from the procurement list

At this point, the unit will be stuck in refit mode until the cows come home. The workarounds include:
- gm-completing the refit
- re-introducing the missing parts to the procurement list (although there's no way to tell what parts you need)
- canceling the refit and doing it again.

It'd be nice to have some kind of UI element telling the user the parts that are required for a refit and are missing, but since there are plenty of workarounds available, I don't think this is "stable-breaking" as such.

**Comment by sixlettervariables** [comment]
I added some code to prevent this problems and just commited a fix which should have addressed the part issues. Please reopen this if it persists.
