### ISSUE TITLE
Loading forces from a MUL file produces incorrect results

### ISSUE THREAD

**Issue by crazys1** [MegaMek/mekhq#691]
### Environment
What version of MekHQ does your issue apply to?

0.43.9-RC3

What operating system are you using?  Windows, Mac, or Linux?

Windows 10

What java version are you using?

Version 8 Update 161, build 1.8.0_161b12

### Description

When you use the "Load forces from a MUL file" feature of the MekHQ, the resulting pilots have some incorrect results, as follows:

1. The gender is random. The MUL files don't store the pilot's gender, even if exported from the MekHQ. When the MUL file is imported, the gender is determined randomly. This can result in some hilarity when you get a male pilot named "Angela" or "Cynthia." :)
2. SPAs (advantages) are lost upon importing.
3. If the campaign is set to assign random portraits, the portraits are chosen randomly even if the pilot already had an assigned portrait.
4. If the pilot had a rank, the name and rank of the pilot does not get set properly when you import the MUL file. The name is saved as "_rank_ _name_" in the MUL file. For example, "Private John Doe." As such, when you import the MUL file, the pilot's name becomes "Private John Doe" in the MekHQ, and his rank is "None."

You can observe all of these behaviors by important the a.mul file in the attached .zip file. See the Files section of this bug report.

### Suggested Fixes

1. Add gender to the MUL files.
2. This one is presumably a bug. Ensure that the advantages get properly imported.
3. If the pilot is already assigned a portrait, do not randomize the portrait.
4. Either save the rank separately in the MUL file, or else enhance the MekHQ to be able to parse the rank from the name. In either case, during the import, have the rank get set properly and exclude the rank from the name.

### Files
[test_mul.zip](https://github.com/MegaMek/mekhq/files/1866009/test_mul.zip)

**Comment by crazys1** [comment]
I see that issue 2 was also reported in #108 and will be fixed in PR #692. So, you can ignore issue 2.

**Comment by Dylan-M** [comment]
@crazys1 This is something I had already planned to work on during the next development cycle. Essentially I'm going to make it so that "Crew" and "MechWarrior" in MegaMek can have a generic "object" added of any type for "extra data" in order to handle these extraneous edge cases. However, the import from MUL file may also be removed, as it's really been unsupported for a long time and I've not yet made up my mind nor discussed with other team members whether we want to keep it. It would be just as easy when bringing in prisoners from another campaign to have all of that data pulled from the other campaign file.

**Comment by crazys1** [comment]
@Dylan-M If you implement the object idea in MegaMek and MekHQ, and remove the MUL import from MekHQ, is your idea to implement the equivalent ability to import the crew and MechWarrior objects from a file that you can save from MegaMek?

I ask because my use case when I encountered these issues was to use MegaMek to create a random force rather than manually hiring or creating pilots and manually adding or buying 'Mechs, then assigning pilots the to the 'Mechs. It was much easier to auto-generate the 'Mechs, pilots, and pilot assignments using MegaMek, then import them into MekHQ.

**Comment by Dylan-M** [comment]
MHQ now includes some of the random generators; so that use case is now at least partually invalid. One of the reasons I've considered just removing the MUL import. Remove it, and bring in the rest of MM's random unit generation capabilities.

**Comment by crazys1** [comment]
@Dylan-M That solution sounds great to me. Thank you!

**Comment by jbhuddleston** [comment]
Something else that is missing when you import from an MUL is the force structure; everything is imported flat.
If adding the force gen functionality to mhq would allow the force structure to be retained that would be a huge time saver. I am in the process of creating a combined arms regt and it is mildly tedious to recreate the force structure in TO&E then add the units one at a time into it.

**Comment by Windchild292** [comment]
I guess you can assign this to me, I've fixed the main two remaining issues, the third was split off to https://github.com/MegaMek/megamek/issues/1742. This will close when #1545 is merged

1) Gender will be added in https://github.com/MegaMek/megamek/pull/1728
2) was fixed by #692 
3) Will be fixed by #1545 (small fix, but it will requires #1533 because I merged the solution with a modification to the crew migration in MekHQ)
4) This one is could be fixed by implementing a GUI for the extraData option, so I've opened https://github.com/MegaMek/megamek/issues/1742. The command will be added in #1533, while the backend code is TBD.

Other parts from the conversation: 
ExtraData will also be added in https://github.com/MegaMek/megamek/pull/1728 , albeit without a way to modify from the GUI. At the current moment it is only used for names, phenotypes, and bloodnames.
As for MUL files retaining force structure, that would require a full rewrite while killing current functionality and therefore is infeasible.
