### ISSUE TITLE
Minor text color display issue with Person text in Personnel and Hangar "Graphic" views 

### ISSUE THREAD

**Issue by Qwertronix** [MegaMek/mekhq#773]
### Environment
Version: 0.43.11-RC5
Windows 10
JRE 1.8.0_151

### Description
![2018-06-24 16_26_01-wardancers mercenary - monday march 1 3030 late succession war - renaissance](https://user-images.githubusercontent.com/360217/41823400-61566180-77cd-11e8-8d30-793cb9777a3b.png)
![2018-06-24 16_41_08-wardancers mercenary - monday march 1 3030 late succession war - renaissance](https://user-images.githubusercontent.com/360217/41823403-69ee3d9a-77cd-11e8-8213-4ac5173107ea.png)

As displayed above, the color of the rank/name/role text of the persons next to their portrait remains black when selection darkens the row, as with unselected rows, unlike the text of other entries (e.g. Unit) that changes color for better contrast.

**Comment by firefly2442** [comment]
It's somewhere in here:

https://github.com/MegaMek/mekhq/blob/097b7bd3ff5d4325056f461408a173571ce4ab5d/MekHQ/src/mekhq/gui/BasicInfo.java#L78
https://github.com/MegaMek/mekhq/blob/097b7bd3ff5d4325056f461408a173571ce4ab5d/MekHQ/src/mekhq/gui/model/PersonnelTableModel.java#L672

There seems to be something different about how the mechwarriors are being displayed than everyone else?  The issue seems to only occur for them.

Out of ideas, maybe someone else can take a look.
