### ISSUE TITLE
Doctors use wrong ranks

### ISSUE THREAD

**Issue by TonicArtos** [MegaMek/mekhq#793]
### Environment
MekHQ 0.44.0 - Linux

### Description
Doctors are using Mechwarrior ranks instead of Technical ranks.

**Comment by firefly2442** [comment]
Can you provide more details?  What are the ranks now?  What should they be?  Do you have documentation/references/websites to validate the recommended changes?

**Comment by CormacAers** [comment]
accidentally stumbled on this post, and i have to second it. 
fresh install 0.44.0, windows. 
starting a new game, everything just click ok until you are inside the "main game",
file > Campain options
Rank system (let's start with Star league here).
delete all ranks (read: replace them with '-')
give as unique name to every bracket (i.e. Mechwarrior, ASF, Vehicle and so on)

when hiring a doctor/medic now, you can see that they get the ranks of a Mechwarrior instead of Tech/Support ranks. 

i don't think we can find any real evidence what ranks medical personal gets within the Battletech universe, in our world, they gain a rank within their companie/whatever (a doctor on a ship get's a navy rank, one within the airforce an airforce rank and so on)
within the battletech universe, we can asume that it may be similar, while looking at the star league ranks, the MW would be the first i would place them in. when i'm getting to the clans, it get's more complicated, here, i wouldn't be able to place them in any ranking system. 

but asuming i create my own set of ranks, where every bracket get's their own ranks. i would not place the medical personal within the ranking system of the MW, i would place them either within the infantrie, naval or tech bracket (where i read the 'tech' as 'support personal) even if some brackets share the same ranks.

**Comment by Patriot1776** [comment]
In the SLDF, the only rank a doctor or a person with technical skills gets is Warrant Officer.

**Comment by pheonixstorm** [comment]
So what are you posting then?? Its not a bug. If you know of a BT book that shows medical ranks should fall in with technical ranks post a source and page number.

**Comment by TonicArtos** [comment]
Having a look through aToW, SO, CO, CBT:RPG. TO, and TW, I see no reference for where medical staff fits in the rank systems. There is only rank references for technical staff, ground forces, aerospace, and naval, with special mentions for mechwarriors. Admin staff and medical staff are left out. However, in MekHQ the Admin staff take ranks from the Technical service branch, so I expected medical staff to also do so.

**Comment by pheonixstorm** [comment]
For whatever reason admin are coded for the tech ranks while drs/medic are coded for MW. Best we could do would be to move both over to the infantry ranks. I already do that for my own fork.

**Comment by Patriot1776** [comment]
You need to look in the original House sourcebook or FM for each House and Periphery state. What I said about the SLDF is true as it comes directly from both Star League Sourcebook (1630) and FM SLDF. 

http://www.sarna.net/wiki/Warrant_Officer#SLDF

It appears that LC/LA and DCMS use a similar system by granting technical ranks to those in technical fields.

**Comment by TonicArtos** [comment]
It's no big deal. I just thought it a bit odd and that an issue should be raised. It is also super easy to work around, so it doesn't matter to me much at all either. I was curious to see if there was anything mentioned in the source books, but since I imagine the target audience were much interesting in playing MASH or ER, there really isn't too much discussion about the medical discipline. Surprising really, since there is so much of everything else.

**Comment by wildj79** [comment]
> Anyway, in the real world, typically doctors have civilian ranks within the command structure as they are drawn from civilian society.

Well, not in all cases. I can't speak for other branches, or other militaries in other countries, but in the US Army, doctors are usually _not_ civilian, and they have a commissioned rank. The way it works now seems fine to me.

**Comment by neoancient** [comment]
I think it would be a trivial matter to be able to set the branch for personnel. The current behavior would be the default, but if you wanted to, for instance, distinguish between army and navy doctors, you could do that. Or, though canon BT factions generally use naval ranks for fighter pilots, you could assign mech/armor/infantry ranks to ground-based pilots (army/air force) and naval ranks to carrier-based (navy).

**Comment by Windchild292** [comment]
Subsumed by #2205
