### ISSUE TITLE
Awards use Clusters

### ISSUE THREAD

**Issue by VampireSeraphin** [MegaMek/mekhq#852]
I discovered that when you assign an award multiple times, it adds the ribbon image multiple times. It should assign the ribbon only on the first instance. I assume you guys don't want to add images for each ribbon with dozens of clusters on them. So, Mekhq could support adding the award more than once in the personnel event log and only once as an image.

**Comment by BLOODWOLF333** [comment]
Im getting to it.  Will create duplicate ribbon and medal images with bronze, silver, and gold stars for multiple awarded awards unless bandildo wants to code the program to array the stars or devices over the ribbons, medals but, making new images will be easier.  and also am going to throw my ranks and service stripe images in the misc folder so those will display below the medals.

**Comment by bandildo** [comment]
what we could do, for multiple awards is have something like:
purple_heart_ribbon.png
purple_heart_ribbon_2.png
purple_heart_ribbon_3.png

And code it so it will automatically look for #2, #3, etc, depending the previously awarded amounts. But then we have to answer these questions: what happens when you award it 5 times and there is only the _4.png? And what will it do with the medals/misc? Will it award only one medal/misc or multiple medals/miscs too?

**Comment by Schugger** [comment]
For awards available multiple times you can reduce the number of medals/ribbons in your folder if the program would handle it like this:
wound badge ribbon - after being wounded for the first time
wound badge ribbon bronze - after being wounded for the second time (replaces wound ribbon)
wound badge ribbon silver - after being wounded for the third time (replaces wound ribbon bronze)
wound badge ribbon gold - after being wounded for the fourth time (replaces wound ribbon silver)
wound medal bronze - after being wounded for the second time (replaces wound badge gold)

for each additional wound you start with the wound badge ribbon again until you get gold again and upon recieving the another wound you get another medal (wound medal silver for example) which replaces all Wound medals and ribbons recieved so far.

Unfortunatly I have no idea how to code this...

**Comment by BLOODWOLF333** [comment]
This is being taken care of.  As soon as bandildo returns we can polish it some more since the new xml format depends on his PR's being pulled in but there is a graphical glitch right now.  I may end up breaking everyones campaign who is currently using the awards we have right now but.....
![github3](https://user-images.githubusercontent.com/16950832/45387726-8abee900-b5dc-11e8-87be-86989e5130f5.png)

![image](https://user-images.githubusercontent.com/16950832/45387796-cb1e6700-b5dc-11e8-803e-852427066ab1.png)

![image](https://user-images.githubusercontent.com/16950832/45387815-db364680-b5dc-11e8-9a5c-cc79d1456b81.png)

**Comment by sixlettervariables** [comment]
Closed by #881.
