### ISSUE TITLE
Allow HTML formatted news in the historical daily log

### ISSUE THREAD

**Issue by firefly2442** [MegaMek/mekhq#858]
The recent [addition of the Historical Daily Log](https://github.com/MegaMek/mekhq/pull/792) [strips out the HTML](https://github.com/MegaMek/mekhq/pull/792/commits/e385a39e81c9204a8734a8adf47b9db107dc6950#diff-7147823e21e3a3306a81d504c995465cR3182).  However, this removes potentially important information such as news events and other items.  Try to add back in the ability to have clickable links.

**Comment by giorgiga** [comment]
@firefly2442 , can you clarify why the HTML is being stripped?

The comments around [where the HTML is stripped](
https://github.com/MegaMek/mekhq/pull/792/commits/e385a39e81c9204a8734a8adf47b9db107dc6950#diff-7147823e21e3a3306a81d504c995465cR3182) seem to point at some memory issue that doesn't add up for me...

If the symptom is that HTML is not correctly retrieved from xml-marshalled LogEntries, that might be due to [LogEntry.generateInstanceFromXML()](https://github.com/MegaMek/mekhq/blob/master/MekHQ/src/mekhq/campaign/LogEntry.java#L108) not correctly  unescaping XML tags (that should be fixed in the fork at giorgiga/mekhq).

**Comment by firefly2442** [comment]
If I remember correctly, I removed the HTML because the links didn't seem to work.  You can see on that line 3182 that it uses a regular expression to remove them.  I tried re-enabling them back when this issue cropped up and they seem to be stored just fine but clicking on them does nothing.  Is this fix that you mention around the XML something that you could put a pull request in for?

**Comment by giorgiga** [comment]
Had to close the PR because... I got carried away and added way too much stuff into it :-)
I'll follow up with a new, surgical one.
