### ISSUE TITLE
Assign/Remove tech to force causes techs to get stuck and become non-removable

### ISSUE THREAD

**Issue by Question2** [MegaMek/mekhq#87]
I tried out the Assign tech to force feature and it caused techs to get stuck. This is what I did : 

1. I right clicked Alpha Lance and assigned Gormly Panton (Mech Tech) to it. I then used remove tech from force to remove him from the force.

2. I then noticed that my vehicles in Alpha lance were listed as having no techs assigned to them in the hangar...but the techs showed that they were assigned to them.

For example, the mechanic "Osman Sadozai" in the personnels tab is listed as being assigned to LRM Carrier IIC. But the hangar shows the same vehicle as having no techs assigned to it. I can double assign the tech to the same unit, but it eats up double of his maintenance time. Right clicking and doing "assign to none" doesnt work, he is still stuck there as a ghost tech. 

All the techs that were assigned to vehicles in Alpha Lance are similarly bugged. Im guessing its because the assign tech to lance option didnt take into account what would happen if you tried to assign a mech tech to a mixed lance.

[#battletech.zip](https://github.com/MegaMek/mekhq/files/285047/battletech.zip)

**Comment by pheonixstorm** [comment]
The lance tech feature was not designed for mixed unit lances and should have had checks in place to keep units from being assigned to the wrong tech type from being assigned. Will have to look that up but the double assignment issue has been fixed already.

Additionally this feature does not work well with heavy weight stars or level II unit sizes due to the amount of maintenance time used up by individual units and the 480 minute limit.

A bonus feature/bug to this is that you can assign a tech to the company/squadron level and that tech will be assigned to all sub forces. The buggy side is it doesn't check for the time used (which I should probably add a nag about it) so it is easy to go over your techs limit.

Will test this with the current code and see what improvements can be made for mixed unit forces.

**Comment by BLOODWOLF333** [comment]
I think I am having this same issue with 0.3.29 but, did not assign a tech to a force.  Just assigning techs to individual mechs and then saving and reloading HQ causes the techs to be cleared from the mechs they were assigned to.  Each tech's log still states where they were assigned but the data gets cleared and have to reassign them again or the 'unmaintained units" nag pops up.  Didnt see anything relevant in the log.

[AssignTech.zip](https://github.com/MegaMek/mekhq/files/338531/AssignTech.zip)

**Comment by BLOODWOLF333** [comment]
This is the issue I am having as well but, did you import your mechs as well Question2?

**Comment by pheonixstorm** [comment]
This should be fixed when #181 is merged.
@Question2 if you have any problems after the fix is applied open a new issue
@BLOODWOLF333 Test this as well and let me know. I haven't tried importing mechs or any unit but this should (I think) fix your issue as well or it could be some else entirely.
