### ISSUE TITLE
[0.45.0 : Feature Request] Enhance after combat resolution to support medal/ribbon awards

### ISSUE THREAD

**Issue by SirMegaV** [MegaMek/mekhq#871]
Enhance after combat resolution to support medal/ribbon awards. 

1. Show total kills per individual/unit, hits taken or any other ‘special’ achievement that can be captured from MM round report

2. Auto suggest medals/ribbons

3. A new tab in campaign setup to setup medals/ribbons and its requirements

This will make life a lot easier for big games.

Thanks.

**Comment by BullseyeSmith** [comment]
Hello All,

I submitted Pull #1670 to add more ribbons that will appear in the proper order of precedence.  It also corrects some errors in the original default set.  It also includes an excel file to import .cpnx files to see which awards were earned during a campaign.  This is a useful interim tool until Issues #850 & #851 are implemented.
[AwardTracker.xlsx](https://github.com/MegaMek/mekhq/files/4467298/AwardTracker.xlsx)

I have several ideas on suggesting award assignments based on automated criteria identification, such as marksmanship awards based on gunnery skills, Purple Heart based on injuries, campaign and special service ribbons based on random generated origin info, and the like.  The easier it is to give characters, well, some character, the more appeal the game will have.  I even added an additional tab to the Official AtB TT Rules that automates a background story based on the dev tab tables.  I'll put that in another Pull later.
[Official AtB TT Rules 2.31.xlsx](https://github.com/MegaMek/mekhq/files/4467326/Official.AtB.TT.Rules.2.31.xlsx)

I'm strong with Excel and decent at VBA.  Cleaning up an XML file and creating some pics is one thing, editing java is another.  I want to add the features I can create in Excel directly into MekHQ.  I've been learning the basics of java and want to spearhead these types of changes.  I see that all three Awards-labeled issues were assigned to @bandildo back in Aug 2018, and he hasn't posted anything on github since Apr 2019.  I've installed GitHub Desktop and have been working with my own clone of the latest snapshot for these simple non-java improvements, but I'm having trouble actually building a MekHQ.exe or MekHQ.jar from the files, either with gradlew.bat or CMD or Netbeans.  Is anyone willing to help me figure out how to get the thing working so I can move on to code editing and plugin creation?  Perhaps @Windchild292 or @sixlettervariables ?  Github does not appear to have a direct chat feature, so I figured I could use this open issue thread to reach out for help in order get me going with fixing this issue myself (Lord willing).

**Comment by HammerGS** [comment]
You can reach the devs via our Slack channel - https://megamek.org/community.html

See the top link.

**Comment by Windchild292** [comment]
@BullseyeSmith 
I've already implemented #850 in the upcoming PR #1629, but the others (this one and #851) do appear to be abandoned and are useful improvements to have. Especially this one, and your ideas do sound solid (I personally didn't even know about the awards until I was around 8 years and hundreds of hours into my campaign, and the implementation you described would significantly improve that design issue). Also, your Excel skills are pretty solid (understating a bit) based on those two sheets.

Please join the slack, as it is far easier to talk about things there than on here. From there, I can help explain how to do your install better than over GitHub, because of the reaction time.
