### ISSUE TITLE
Time in Service Tracker Logs incorrectly for personnel born into the unit. 

### ISSUE THREAD

**Issue by VampireSeraphin** [MegaMek/mekhq#925]
So, I noticed this morning that the time in service tracker is counting from when an NPC was added to the unit, not from when they were first assigned a rank or role. While normally this is pretty trivial, it has given some of the NPCs born into the unit impressive (and pretty hilarious) time in service for 18 year olds.

My suggestion would be that newly born personnel are automatically assigned as dependents with no role, and the tracker is reworked to track from first assigned roll/skill.

**Comment by VampireSeraphin** [comment]
Related to this, I just discovered that deceased personnel continue to accrue time in service. I think its nice for MM to be branching out into the zombie genre.

**Comment by giorgiga** [comment]
Really, MekHQ just remembers the date someone has joined :-)

The zombie army effect is caused by `mekhq.campaign.personnel.Person.getTimeInService(GregorianCalendar)` not taking `Person.deathday` into consideration.

The initial issue must be caused by `Person.recruitment` being set to the birth date, but I couldn't determine how that can happen... as far as my understanding goes, `Person.recruitment` is initialised with the current campaign date when a person is not a dependant anymore (and newborns are dependants).

**Comment by VampireSeraphin** [comment]
Sometimes newborns are assigned skills by MeHq. Perhaps this is overriding the dependents flag?

**Comment by pheonixstorm** [comment]
Its possible this is due to turning the feature on AFTER the dependent flag has been set to false but before any job was given. I don't remember what log entry a child gets when born but if its joined then that might confuse it in this edge case. Unless someone accidentally  modified the code while fixing bugs or adding another feature. There should be a check during init to keep dependents from getting a TiS.

I will look into it this weekend if I get a chance since this is a 4 day weekend for the kids.

**Comment by Windchild292** [comment]
I've tackled this as a break from my wider personnel changes.

Zombie time in service has been fixed, and I've investigated any cause of dependents having a recruitment date set before they become a member of the unit and found nothing.
